// Code generated by protoc-gen-go.
// source: table_store.proto
// DO NOT EDIT!

package tsprotocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PrimaryKeyType int32

const (
	PrimaryKeyType_INTEGER PrimaryKeyType = 1
	PrimaryKeyType_STRING  PrimaryKeyType = 2
	PrimaryKeyType_BINARY  PrimaryKeyType = 3
)

var PrimaryKeyType_name = map[int32]string{
	1: "INTEGER",
	2: "STRING",
	3: "BINARY",
}
var PrimaryKeyType_value = map[string]int32{
	"INTEGER": 1,
	"STRING":  2,
	"BINARY":  3,
}

func (x PrimaryKeyType) Enum() *PrimaryKeyType {
	p := new(PrimaryKeyType)
	*p = x
	return p
}
func (x PrimaryKeyType) String() string {
	return proto.EnumName(PrimaryKeyType_name, int32(x))
}
func (x *PrimaryKeyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PrimaryKeyType_value, data, "PrimaryKeyType")
	if err != nil {
		return err
	}
	*x = PrimaryKeyType(value)
	return nil
}
func (PrimaryKeyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type PrimaryKeyOption int32

const (
	PrimaryKeyOption_AUTO_INCREMENT PrimaryKeyOption = 1
)

var PrimaryKeyOption_name = map[int32]string{
	1: "AUTO_INCREMENT",
}
var PrimaryKeyOption_value = map[string]int32{
	"AUTO_INCREMENT": 1,
}

func (x PrimaryKeyOption) Enum() *PrimaryKeyOption {
	p := new(PrimaryKeyOption)
	*p = x
	return p
}
func (x PrimaryKeyOption) String() string {
	return proto.EnumName(PrimaryKeyOption_name, int32(x))
}
func (x *PrimaryKeyOption) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PrimaryKeyOption_value, data, "PrimaryKeyOption")
	if err != nil {
		return err
	}
	*x = PrimaryKeyOption(value)
	return nil
}
func (PrimaryKeyOption) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type BloomFilterType int32

const (
	BloomFilterType_NONE BloomFilterType = 1
	BloomFilterType_CELL BloomFilterType = 2
	BloomFilterType_ROW  BloomFilterType = 3
)

var BloomFilterType_name = map[int32]string{
	1: "NONE",
	2: "CELL",
	3: "ROW",
}
var BloomFilterType_value = map[string]int32{
	"NONE": 1,
	"CELL": 2,
	"ROW":  3,
}

func (x BloomFilterType) Enum() *BloomFilterType {
	p := new(BloomFilterType)
	*p = x
	return p
}
func (x BloomFilterType) String() string {
	return proto.EnumName(BloomFilterType_name, int32(x))
}
func (x *BloomFilterType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BloomFilterType_value, data, "BloomFilterType")
	if err != nil {
		return err
	}
	*x = BloomFilterType(value)
	return nil
}
func (BloomFilterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// *
// 表的状态变更只与用户的操作对应，内部的机器failover等状况不对应表的状态变更。
// 有三个考虑：
//     一是一般场景下用户只会在做了对表的修改操作后才会去检查表的状态；
//     二是内部机器failover导致访问异常到用户能够查看到表的状态变更这两个时刻之间会有一段延迟，无法将表的不可服务状态与用户查看到的表的状态完全匹配上。
//     三是内部机器failover后不能说是表的整个状态变更，而应该是partition的状态变更，对应表的状态就是PARTIAL_FAILOVER，这个partial的粒度无法体现，会让用户更加困惑。
type TableStatus int32

const (
	TableStatus_ACTIVE    TableStatus = 1
	TableStatus_INACTIVE  TableStatus = 2
	TableStatus_LOADING   TableStatus = 3
	TableStatus_UNLOADING TableStatus = 4
	TableStatus_UPDATING  TableStatus = 5
)

var TableStatus_name = map[int32]string{
	1: "ACTIVE",
	2: "INACTIVE",
	3: "LOADING",
	4: "UNLOADING",
	5: "UPDATING",
}
var TableStatus_value = map[string]int32{
	"ACTIVE":    1,
	"INACTIVE":  2,
	"LOADING":   3,
	"UNLOADING": 4,
	"UPDATING":  5,
}

func (x TableStatus) Enum() *TableStatus {
	p := new(TableStatus)
	*p = x
	return p
}
func (x TableStatus) String() string {
	return proto.EnumName(TableStatus_name, int32(x))
}
func (x *TableStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TableStatus_value, data, "TableStatus")
	if err != nil {
		return err
	}
	*x = TableStatus(value)
	return nil
}
func (TableStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type RowExistenceExpectation int32

const (
	RowExistenceExpectation_IGNORE           RowExistenceExpectation = 0
	RowExistenceExpectation_EXPECT_EXIST     RowExistenceExpectation = 1
	RowExistenceExpectation_EXPECT_NOT_EXIST RowExistenceExpectation = 2
)

var RowExistenceExpectation_name = map[int32]string{
	0: "IGNORE",
	1: "EXPECT_EXIST",
	2: "EXPECT_NOT_EXIST",
}
var RowExistenceExpectation_value = map[string]int32{
	"IGNORE":           0,
	"EXPECT_EXIST":     1,
	"EXPECT_NOT_EXIST": 2,
}

func (x RowExistenceExpectation) Enum() *RowExistenceExpectation {
	p := new(RowExistenceExpectation)
	*p = x
	return p
}
func (x RowExistenceExpectation) String() string {
	return proto.EnumName(RowExistenceExpectation_name, int32(x))
}
func (x *RowExistenceExpectation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RowExistenceExpectation_value, data, "RowExistenceExpectation")
	if err != nil {
		return err
	}
	*x = RowExistenceExpectation(value)
	return nil
}
func (RowExistenceExpectation) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type ReturnType int32

const (
	ReturnType_RT_NONE ReturnType = 0
	ReturnType_RT_PK   ReturnType = 1
)

var ReturnType_name = map[int32]string{
	0: "RT_NONE",
	1: "RT_PK",
}
var ReturnType_value = map[string]int32{
	"RT_NONE": 0,
	"RT_PK":   1,
}

func (x ReturnType) Enum() *ReturnType {
	p := new(ReturnType)
	*p = x
	return p
}
func (x ReturnType) String() string {
	return proto.EnumName(ReturnType_name, int32(x))
}
func (x *ReturnType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReturnType_value, data, "ReturnType")
	if err != nil {
		return err
	}
	*x = ReturnType(value)
	return nil
}
func (ReturnType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type OperationType int32

const (
	OperationType_PUT    OperationType = 1
	OperationType_UPDATE OperationType = 2
	OperationType_DELETE OperationType = 3
)

var OperationType_name = map[int32]string{
	1: "PUT",
	2: "UPDATE",
	3: "DELETE",
}
var OperationType_value = map[string]int32{
	"PUT":    1,
	"UPDATE": 2,
	"DELETE": 3,
}

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}
func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (x *OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OperationType_value, data, "OperationType")
	if err != nil {
		return err
	}
	*x = OperationType(value)
	return nil
}
func (OperationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

// #############################################  GetRange  #############################################
type Direction int32

const (
	Direction_FORWARD  Direction = 0
	Direction_BACKWARD Direction = 1
)

var Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
}
var Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
}

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}
func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (x *Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Direction_value, data, "Direction")
	if err != nil {
		return err
	}
	*x = Direction(value)
	return nil
}
func (Direction) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type Error struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Error) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type PrimaryKeySchema struct {
	Name             *string           `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type             *PrimaryKeyType   `protobuf:"varint,2,req,name=type,enum=otsprotocol.PrimaryKeyType" json:"type,omitempty"`
	Option           *PrimaryKeyOption `protobuf:"varint,3,opt,name=option,enum=otsprotocol.PrimaryKeyOption" json:"option,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PrimaryKeySchema) Reset()                    { *m = PrimaryKeySchema{} }
func (m *PrimaryKeySchema) String() string            { return proto.CompactTextString(m) }
func (*PrimaryKeySchema) ProtoMessage()               {}
func (*PrimaryKeySchema) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PrimaryKeySchema) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PrimaryKeySchema) GetType() PrimaryKeyType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PrimaryKeyType_INTEGER
}

func (m *PrimaryKeySchema) GetOption() PrimaryKeyOption {
	if m != nil && m.Option != nil {
		return *m.Option
	}
	return PrimaryKeyOption_AUTO_INCREMENT
}

type PartitionRange struct {
	Begin            []byte `protobuf:"bytes,1,req,name=begin" json:"begin,omitempty"`
	End              []byte `protobuf:"bytes,2,req,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PartitionRange) Reset()                    { *m = PartitionRange{} }
func (m *PartitionRange) String() string            { return proto.CompactTextString(m) }
func (*PartitionRange) ProtoMessage()               {}
func (*PartitionRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *PartitionRange) GetBegin() []byte {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *PartitionRange) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

type TableOptions struct {
	TimeToLive                *int32           `protobuf:"varint,1,opt,name=time_to_live" json:"time_to_live,omitempty"`
	MaxVersions               *int32           `protobuf:"varint,2,opt,name=max_versions" json:"max_versions,omitempty"`
	BloomFilterType           *BloomFilterType `protobuf:"varint,3,opt,name=bloom_filter_type,enum=otsprotocol.BloomFilterType" json:"bloom_filter_type,omitempty"`
	BlockSize                 *int32           `protobuf:"varint,4,opt,name=block_size" json:"block_size,omitempty"`
	DeviationCellVersionInSec *int64           `protobuf:"varint,5,opt,name=deviation_cell_version_in_sec" json:"deviation_cell_version_in_sec,omitempty"`
	XXX_unrecognized          []byte           `json:"-"`
}

func (m *TableOptions) Reset()                    { *m = TableOptions{} }
func (m *TableOptions) String() string            { return proto.CompactTextString(m) }
func (*TableOptions) ProtoMessage()               {}
func (*TableOptions) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *TableOptions) GetTimeToLive() int32 {
	if m != nil && m.TimeToLive != nil {
		return *m.TimeToLive
	}
	return 0
}

func (m *TableOptions) GetMaxVersions() int32 {
	if m != nil && m.MaxVersions != nil {
		return *m.MaxVersions
	}
	return 0
}

func (m *TableOptions) GetBloomFilterType() BloomFilterType {
	if m != nil && m.BloomFilterType != nil {
		return *m.BloomFilterType
	}
	return BloomFilterType_NONE
}

func (m *TableOptions) GetBlockSize() int32 {
	if m != nil && m.BlockSize != nil {
		return *m.BlockSize
	}
	return 0
}

func (m *TableOptions) GetDeviationCellVersionInSec() int64 {
	if m != nil && m.DeviationCellVersionInSec != nil {
		return *m.DeviationCellVersionInSec
	}
	return 0
}

type TableMeta struct {
	TableName        *string             `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []*PrimaryKeySchema `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *TableMeta) Reset()                    { *m = TableMeta{} }
func (m *TableMeta) String() string            { return proto.CompactTextString(m) }
func (*TableMeta) ProtoMessage()               {}
func (*TableMeta) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *TableMeta) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableMeta) GetPrimaryKey() []*PrimaryKeySchema {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

type Condition struct {
	RowExistence     *RowExistenceExpectation `protobuf:"varint,1,req,name=row_existence,enum=otsprotocol.RowExistenceExpectation" json:"row_existence,omitempty"`
	ColumnCondition  []byte                   `protobuf:"bytes,2,opt,name=column_condition" json:"column_condition,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Condition) Reset()                    { *m = Condition{} }
func (m *Condition) String() string            { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()               {}
func (*Condition) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Condition) GetRowExistence() RowExistenceExpectation {
	if m != nil && m.RowExistence != nil {
		return *m.RowExistence
	}
	return RowExistenceExpectation_IGNORE
}

func (m *Condition) GetColumnCondition() []byte {
	if m != nil {
		return m.ColumnCondition
	}
	return nil
}

type CapacityUnit struct {
	Read             *int32 `protobuf:"varint,1,opt,name=read" json:"read,omitempty"`
	Write            *int32 `protobuf:"varint,2,opt,name=write" json:"write,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CapacityUnit) Reset()                    { *m = CapacityUnit{} }
func (m *CapacityUnit) String() string            { return proto.CompactTextString(m) }
func (*CapacityUnit) ProtoMessage()               {}
func (*CapacityUnit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *CapacityUnit) GetRead() int32 {
	if m != nil && m.Read != nil {
		return *m.Read
	}
	return 0
}

func (m *CapacityUnit) GetWrite() int32 {
	if m != nil && m.Write != nil {
		return *m.Write
	}
	return 0
}

type ReservedThroughputDetails struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	LastIncreaseTime *int64        `protobuf:"varint,2,req,name=last_increase_time" json:"last_increase_time,omitempty"`
	LastDecreaseTime *int64        `protobuf:"varint,3,opt,name=last_decrease_time" json:"last_decrease_time,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ReservedThroughputDetails) Reset()                    { *m = ReservedThroughputDetails{} }
func (m *ReservedThroughputDetails) String() string            { return proto.CompactTextString(m) }
func (*ReservedThroughputDetails) ProtoMessage()               {}
func (*ReservedThroughputDetails) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ReservedThroughputDetails) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

func (m *ReservedThroughputDetails) GetLastIncreaseTime() int64 {
	if m != nil && m.LastIncreaseTime != nil {
		return *m.LastIncreaseTime
	}
	return 0
}

func (m *ReservedThroughputDetails) GetLastDecreaseTime() int64 {
	if m != nil && m.LastDecreaseTime != nil {
		return *m.LastDecreaseTime
	}
	return 0
}

type ReservedThroughput struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ReservedThroughput) Reset()                    { *m = ReservedThroughput{} }
func (m *ReservedThroughput) String() string            { return proto.CompactTextString(m) }
func (*ReservedThroughput) ProtoMessage()               {}
func (*ReservedThroughput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ReservedThroughput) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

type ConsumedCapacity struct {
	CapacityUnit     *CapacityUnit `protobuf:"bytes,1,req,name=capacity_unit" json:"capacity_unit,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ConsumedCapacity) Reset()                    { *m = ConsumedCapacity{} }
func (m *ConsumedCapacity) String() string            { return proto.CompactTextString(m) }
func (*ConsumedCapacity) ProtoMessage()               {}
func (*ConsumedCapacity) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ConsumedCapacity) GetCapacityUnit() *CapacityUnit {
	if m != nil {
		return m.CapacityUnit
	}
	return nil
}

// *
// table_meta用于存储表中不可更改的schema属性，可以更改的ReservedThroughput和TableOptions独立出来，作为UpdateTable的参数。
// 加入GlobalIndex和LocalIndex之后，结构会变为：
// message CreateTableRequest {
//         required TableMeta table_meta = 1;
//         required ReservedThroughput reserved_throughput = 2;
//         required TableOptions table_options = 3;
//         repeated LocalIndex local_indexes = 4; // LocalIndex不再单独包含ReservedThroughput和TableOptions，其与主表共享配置。
//         repeated GlobalIndex global_indexes = 5; // GlobalIndex内单独包含ReservedThroughput和TableOptions
// }
type CreateTableRequest struct {
	TableMeta          *TableMeta          `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,req,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	TableOptions       *TableOptions       `protobuf:"bytes,3,opt,name=table_options" json:"table_options,omitempty"`
	Partitions         []*PartitionRange   `protobuf:"bytes,4,rep,name=partitions" json:"partitions,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *CreateTableRequest) Reset()                    { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()               {}
func (*CreateTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *CreateTableRequest) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *CreateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

func (m *CreateTableRequest) GetTableOptions() *TableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

func (m *CreateTableRequest) GetPartitions() []*PartitionRange {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type CreateTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateTableResponse) Reset()                    { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()               {}
func (*CreateTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

// #############################################  UpdateTable  #############################################
type UpdateTableRequest struct {
	TableName          *string             `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	ReservedThroughput *ReservedThroughput `protobuf:"bytes,2,opt,name=reserved_throughput" json:"reserved_throughput,omitempty"`
	TableOptions       *TableOptions       `protobuf:"bytes,3,opt,name=table_options" json:"table_options,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *UpdateTableRequest) Reset()                    { *m = UpdateTableRequest{} }
func (m *UpdateTableRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableRequest) ProtoMessage()               {}
func (*UpdateTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *UpdateTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateTableRequest) GetReservedThroughput() *ReservedThroughput {
	if m != nil {
		return m.ReservedThroughput
	}
	return nil
}

func (m *UpdateTableRequest) GetTableOptions() *TableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

type UpdateTableResponse struct {
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,1,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	TableOptions              *TableOptions              `protobuf:"bytes,2,req,name=table_options" json:"table_options,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *UpdateTableResponse) Reset()                    { *m = UpdateTableResponse{} }
func (m *UpdateTableResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateTableResponse) ProtoMessage()               {}
func (*UpdateTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *UpdateTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

func (m *UpdateTableResponse) GetTableOptions() *TableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

// #############################################  DescribeTable  #############################################
type DescribeTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DescribeTableRequest) Reset()                    { *m = DescribeTableRequest{} }
func (m *DescribeTableRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeTableRequest) ProtoMessage()               {}
func (*DescribeTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *DescribeTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DescribeTableResponse struct {
	TableMeta                 *TableMeta                 `protobuf:"bytes,1,req,name=table_meta" json:"table_meta,omitempty"`
	ReservedThroughputDetails *ReservedThroughputDetails `protobuf:"bytes,2,req,name=reserved_throughput_details" json:"reserved_throughput_details,omitempty"`
	TableOptions              *TableOptions              `protobuf:"bytes,3,req,name=table_options" json:"table_options,omitempty"`
	TableStatus               *TableStatus               `protobuf:"varint,4,req,name=table_status,enum=otsprotocol.TableStatus" json:"table_status,omitempty"`
	ShardSplits               [][]byte                   `protobuf:"bytes,6,rep,name=shard_splits" json:"shard_splits,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *DescribeTableResponse) Reset()                    { *m = DescribeTableResponse{} }
func (m *DescribeTableResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeTableResponse) ProtoMessage()               {}
func (*DescribeTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *DescribeTableResponse) GetTableMeta() *TableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

func (m *DescribeTableResponse) GetReservedThroughputDetails() *ReservedThroughputDetails {
	if m != nil {
		return m.ReservedThroughputDetails
	}
	return nil
}

func (m *DescribeTableResponse) GetTableOptions() *TableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

func (m *DescribeTableResponse) GetTableStatus() TableStatus {
	if m != nil && m.TableStatus != nil {
		return *m.TableStatus
	}
	return TableStatus_ACTIVE
}

func (m *DescribeTableResponse) GetShardSplits() [][]byte {
	if m != nil {
		return m.ShardSplits
	}
	return nil
}

// #############################################  ListTable  #############################################
type ListTableRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListTableRequest) Reset()                    { *m = ListTableRequest{} }
func (m *ListTableRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTableRequest) ProtoMessage()               {}
func (*ListTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

// *
// 当前只返回一个简单的名称列表，需要讨论是否有业务场景需要获取除了表名之外的其他信息。
// 其他信息可以包含预留吞吐量以及表的状态，这个信息只能是一个粗略的信息，表的详细信息还是需要通过DescribeTable来获取。
type ListTableResponse struct {
	TableNames       []string `protobuf:"bytes,1,rep,name=table_names" json:"table_names,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListTableResponse) Reset()                    { *m = ListTableResponse{} }
func (m *ListTableResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTableResponse) ProtoMessage()               {}
func (*ListTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *ListTableResponse) GetTableNames() []string {
	if m != nil {
		return m.TableNames
	}
	return nil
}

// #############################################  DeleteTable  #############################################
type DeleteTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteTableRequest) Reset()                    { *m = DeleteTableRequest{} }
func (m *DeleteTableRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTableRequest) ProtoMessage()               {}
func (*DeleteTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *DeleteTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DeleteTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteTableResponse) Reset()                    { *m = DeleteTableResponse{} }
func (m *DeleteTableResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTableResponse) ProtoMessage()               {}
func (*DeleteTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

// #############################################  LoadTable  #############################################
type LoadTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoadTableRequest) Reset()                    { *m = LoadTableRequest{} }
func (m *LoadTableRequest) String() string            { return proto.CompactTextString(m) }
func (*LoadTableRequest) ProtoMessage()               {}
func (*LoadTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *LoadTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type LoadTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoadTableResponse) Reset()                    { *m = LoadTableResponse{} }
func (m *LoadTableResponse) String() string            { return proto.CompactTextString(m) }
func (*LoadTableResponse) ProtoMessage()               {}
func (*LoadTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

// #############################################  UnloadTable  #############################################
type UnloadTableRequest struct {
	TableName        *string `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UnloadTableRequest) Reset()                    { *m = UnloadTableRequest{} }
func (m *UnloadTableRequest) String() string            { return proto.CompactTextString(m) }
func (*UnloadTableRequest) ProtoMessage()               {}
func (*UnloadTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *UnloadTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type UnloadTableResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnloadTableResponse) Reset()                    { *m = UnloadTableResponse{} }
func (m *UnloadTableResponse) String() string            { return proto.CompactTextString(m) }
func (*UnloadTableResponse) ProtoMessage()               {}
func (*UnloadTableResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

// *
// 时间戳的取值最小值为0，最大值为INT64.MAX
// 1. 若要查询一个范围，则指定start_time和end_time
// 2. 若要查询一个特定时间戳，则指定specific_time
type TimeRange struct {
	StartTime        *int64 `protobuf:"varint,1,opt,name=start_time" json:"start_time,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,opt,name=end_time" json:"end_time,omitempty"`
	SpecificTime     *int64 `protobuf:"varint,3,opt,name=specific_time" json:"specific_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *TimeRange) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *TimeRange) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *TimeRange) GetSpecificTime() int64 {
	if m != nil && m.SpecificTime != nil {
		return *m.SpecificTime
	}
	return 0
}

type ReturnContent struct {
	ReturnType       *ReturnType `protobuf:"varint,1,opt,name=return_type,enum=otsprotocol.ReturnType" json:"return_type,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ReturnContent) Reset()                    { *m = ReturnContent{} }
func (m *ReturnContent) String() string            { return proto.CompactTextString(m) }
func (*ReturnContent) ProtoMessage()               {}
func (*ReturnContent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *ReturnContent) GetReturnType() ReturnType {
	if m != nil && m.ReturnType != nil {
		return *m.ReturnType
	}
	return ReturnType_RT_NONE
}

// *
// 1. 支持用户指定版本时间戳范围或者特定的版本时间来读取指定版本的列
// 2. 目前暂不支持行内的断点
type GetRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []byte     `protobuf:"bytes,2,req,name=primary_key" json:"primary_key,omitempty"`
	ColumnsToGet     []string   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	TimeRange        *TimeRange `protobuf:"bytes,4,opt,name=time_range" json:"time_range,omitempty"`
	MaxVersions      *int32     `protobuf:"varint,5,opt,name=max_versions" json:"max_versions,omitempty"`
	CacheBlocks      *bool      `protobuf:"varint,6,opt,name=cache_blocks,def=1" json:"cache_blocks,omitempty"`
	Filter           []byte     `protobuf:"bytes,7,opt,name=filter" json:"filter,omitempty"`
	StartColumn      *string    `protobuf:"bytes,8,opt,name=start_column" json:"start_column,omitempty"`
	EndColumn        *string    `protobuf:"bytes,9,opt,name=end_column" json:"end_column,omitempty"`
	Token            []byte     `protobuf:"bytes,10,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GetRowRequest) Reset()                    { *m = GetRowRequest{} }
func (m *GetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRowRequest) ProtoMessage()               {}
func (*GetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

const Default_GetRowRequest_CacheBlocks bool = true

func (m *GetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRowRequest) GetPrimaryKey() []byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *GetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

func (m *GetRowRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *GetRowRequest) GetMaxVersions() int32 {
	if m != nil && m.MaxVersions != nil {
		return *m.MaxVersions
	}
	return 0
}

func (m *GetRowRequest) GetCacheBlocks() bool {
	if m != nil && m.CacheBlocks != nil {
		return *m.CacheBlocks
	}
	return Default_GetRowRequest_CacheBlocks
}

func (m *GetRowRequest) GetFilter() []byte {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GetRowRequest) GetStartColumn() string {
	if m != nil && m.StartColumn != nil {
		return *m.StartColumn
	}
	return ""
}

func (m *GetRowRequest) GetEndColumn() string {
	if m != nil && m.EndColumn != nil {
		return *m.EndColumn
	}
	return ""
}

func (m *GetRowRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,2,req,name=row" json:"row,omitempty"`
	NextToken        []byte            `protobuf:"bytes,3,opt,name=next_token" json:"next_token,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetRowResponse) Reset()                    { *m = GetRowResponse{} }
func (m *GetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRowResponse) ProtoMessage()               {}
func (*GetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *GetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *GetRowResponse) GetNextToken() []byte {
	if m != nil {
		return m.NextToken
	}
	return nil
}

// #############################################  UpdateRow  #############################################
type UpdateRowRequest struct {
	TableName        *string        `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	RowChange        []byte         `protobuf:"bytes,2,req,name=row_change" json:"row_change,omitempty"`
	Condition        *Condition     `protobuf:"bytes,3,req,name=condition" json:"condition,omitempty"`
	ReturnContent    *ReturnContent `protobuf:"bytes,4,opt,name=return_content" json:"return_content,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UpdateRowRequest) Reset()                    { *m = UpdateRowRequest{} }
func (m *UpdateRowRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRowRequest) ProtoMessage()               {}
func (*UpdateRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *UpdateRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateRowRequest) GetRowChange() []byte {
	if m != nil {
		return m.RowChange
	}
	return nil
}

func (m *UpdateRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *UpdateRowRequest) GetReturnContent() *ReturnContent {
	if m != nil {
		return m.ReturnContent
	}
	return nil
}

type UpdateRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,2,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *UpdateRowResponse) Reset()                    { *m = UpdateRowResponse{} }
func (m *UpdateRowResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateRowResponse) ProtoMessage()               {}
func (*UpdateRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *UpdateRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *UpdateRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

// *
// 这里允许用户为每列单独设置timestamp，而不是强制整行统一一个timestamp。
// 原因是列都是用统一的结构，该结构本身是带timestamp的，其次强制统一timestamp增强了规范性但是丧失了灵活性，且该规范性没有明显的好处，反而带来了结构的复杂。
type PutRowRequest struct {
	TableName        *string        `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Row              []byte         `protobuf:"bytes,2,req,name=row" json:"row,omitempty"`
	Condition        *Condition     `protobuf:"bytes,3,req,name=condition" json:"condition,omitempty"`
	ReturnContent    *ReturnContent `protobuf:"bytes,4,opt,name=return_content" json:"return_content,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PutRowRequest) Reset()                    { *m = PutRowRequest{} }
func (m *PutRowRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRowRequest) ProtoMessage()               {}
func (*PutRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *PutRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *PutRowRequest) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *PutRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *PutRowRequest) GetReturnContent() *ReturnContent {
	if m != nil {
		return m.ReturnContent
	}
	return nil
}

type PutRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,2,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PutRowResponse) Reset()                    { *m = PutRowResponse{} }
func (m *PutRowResponse) String() string            { return proto.CompactTextString(m) }
func (*PutRowResponse) ProtoMessage()               {}
func (*PutRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *PutRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *PutRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

// *
// OTS只支持删除该行的所有列所有版本，不支持：
//  1. 删除所有列的所有小于等于某个版本的所有版本
type DeleteRowRequest struct {
	TableName        *string        `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       []byte         `protobuf:"bytes,2,req,name=primary_key" json:"primary_key,omitempty"`
	Condition        *Condition     `protobuf:"bytes,3,req,name=condition" json:"condition,omitempty"`
	ReturnContent    *ReturnContent `protobuf:"bytes,4,opt,name=return_content" json:"return_content,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *DeleteRowRequest) Reset()                    { *m = DeleteRowRequest{} }
func (m *DeleteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRowRequest) ProtoMessage()               {}
func (*DeleteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

func (m *DeleteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *DeleteRowRequest) GetPrimaryKey() []byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *DeleteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DeleteRowRequest) GetReturnContent() *ReturnContent {
	if m != nil {
		return m.ReturnContent
	}
	return nil
}

type DeleteRowResponse struct {
	Consumed         *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,2,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteRowResponse) Reset()                    { *m = DeleteRowResponse{} }
func (m *DeleteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRowResponse) ProtoMessage()               {}
func (*DeleteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *DeleteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *DeleteRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

// *
// HBase支持Batch操作的每行都拥有不同的查询参数，OTS不支持。
type TableInBatchGetRowRequest struct {
	TableName        *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	PrimaryKey       [][]byte   `protobuf:"bytes,2,rep,name=primary_key" json:"primary_key,omitempty"`
	Token            [][]byte   `protobuf:"bytes,3,rep,name=token" json:"token,omitempty"`
	ColumnsToGet     []string   `protobuf:"bytes,4,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	TimeRange        *TimeRange `protobuf:"bytes,5,opt,name=time_range" json:"time_range,omitempty"`
	MaxVersions      *int32     `protobuf:"varint,6,opt,name=max_versions" json:"max_versions,omitempty"`
	CacheBlocks      *bool      `protobuf:"varint,7,opt,name=cache_blocks,def=1" json:"cache_blocks,omitempty"`
	Filter           []byte     `protobuf:"bytes,8,opt,name=filter" json:"filter,omitempty"`
	StartColumn      *string    `protobuf:"bytes,9,opt,name=start_column" json:"start_column,omitempty"`
	EndColumn        *string    `protobuf:"bytes,10,opt,name=end_column" json:"end_column,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *TableInBatchGetRowRequest) Reset()                    { *m = TableInBatchGetRowRequest{} }
func (m *TableInBatchGetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchGetRowRequest) ProtoMessage()               {}
func (*TableInBatchGetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

const Default_TableInBatchGetRowRequest_CacheBlocks bool = true

func (m *TableInBatchGetRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowRequest) GetPrimaryKey() [][]byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetToken() [][]byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetMaxVersions() int32 {
	if m != nil && m.MaxVersions != nil {
		return *m.MaxVersions
	}
	return 0
}

func (m *TableInBatchGetRowRequest) GetCacheBlocks() bool {
	if m != nil && m.CacheBlocks != nil {
		return *m.CacheBlocks
	}
	return Default_TableInBatchGetRowRequest_CacheBlocks
}

func (m *TableInBatchGetRowRequest) GetFilter() []byte {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *TableInBatchGetRowRequest) GetStartColumn() string {
	if m != nil && m.StartColumn != nil {
		return *m.StartColumn
	}
	return ""
}

func (m *TableInBatchGetRowRequest) GetEndColumn() string {
	if m != nil && m.EndColumn != nil {
		return *m.EndColumn
	}
	return ""
}

type BatchGetRowRequest struct {
	Tables           []*TableInBatchGetRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *BatchGetRowRequest) Reset()                    { *m = BatchGetRowRequest{} }
func (m *BatchGetRowRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchGetRowRequest) ProtoMessage()               {}
func (*BatchGetRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{35} }

func (m *BatchGetRowRequest) GetTables() []*TableInBatchGetRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchGetRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,4,opt,name=row" json:"row,omitempty"`
	NextToken        []byte            `protobuf:"bytes,5,opt,name=next_token" json:"next_token,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchGetRowResponse) Reset()                    { *m = RowInBatchGetRowResponse{} }
func (m *RowInBatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchGetRowResponse) ProtoMessage()               {}
func (*RowInBatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{36} }

func (m *RowInBatchGetRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return false
}

func (m *RowInBatchGetRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *RowInBatchGetRowResponse) GetNextToken() []byte {
	if m != nil {
		return m.NextToken
	}
	return nil
}

type TableInBatchGetRowResponse struct {
	TableName        *string                     `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchGetRowResponse `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *TableInBatchGetRowResponse) Reset()                    { *m = TableInBatchGetRowResponse{} }
func (m *TableInBatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchGetRowResponse) ProtoMessage()               {}
func (*TableInBatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{37} }

func (m *TableInBatchGetRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchGetRowResponse) GetRows() []*RowInBatchGetRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BatchGetRowResponse struct {
	Tables           []*TableInBatchGetRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *BatchGetRowResponse) Reset()                    { *m = BatchGetRowResponse{} }
func (m *BatchGetRowResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchGetRowResponse) ProtoMessage()               {}
func (*BatchGetRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{38} }

func (m *BatchGetRowResponse) GetTables() []*TableInBatchGetRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchWriteRowRequest struct {
	Type             *OperationType `protobuf:"varint,1,req,name=type,enum=otsprotocol.OperationType" json:"type,omitempty"`
	RowChange        []byte         `protobuf:"bytes,2,req,name=row_change" json:"row_change,omitempty"`
	Condition        *Condition     `protobuf:"bytes,3,req,name=condition" json:"condition,omitempty"`
	ReturnContent    *ReturnContent `protobuf:"bytes,4,opt,name=return_content" json:"return_content,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RowInBatchWriteRowRequest) Reset()                    { *m = RowInBatchWriteRowRequest{} }
func (m *RowInBatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchWriteRowRequest) ProtoMessage()               {}
func (*RowInBatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{39} }

func (m *RowInBatchWriteRowRequest) GetType() OperationType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return OperationType_PUT
}

func (m *RowInBatchWriteRowRequest) GetRowChange() []byte {
	if m != nil {
		return m.RowChange
	}
	return nil
}

func (m *RowInBatchWriteRowRequest) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *RowInBatchWriteRowRequest) GetReturnContent() *ReturnContent {
	if m != nil {
		return m.ReturnContent
	}
	return nil
}

type TableInBatchWriteRowRequest struct {
	TableName        *string                      `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchWriteRowRequest `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *TableInBatchWriteRowRequest) Reset()                    { *m = TableInBatchWriteRowRequest{} }
func (m *TableInBatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowRequest) ProtoMessage()               {}
func (*TableInBatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{40} }

func (m *TableInBatchWriteRowRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowRequest) GetRows() []*RowInBatchWriteRowRequest {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BatchWriteRowRequest struct {
	Tables           []*TableInBatchWriteRowRequest `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *BatchWriteRowRequest) Reset()                    { *m = BatchWriteRowRequest{} }
func (m *BatchWriteRowRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchWriteRowRequest) ProtoMessage()               {}
func (*BatchWriteRowRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{41} }

func (m *BatchWriteRowRequest) GetTables() []*TableInBatchWriteRowRequest {
	if m != nil {
		return m.Tables
	}
	return nil
}

type RowInBatchWriteRowResponse struct {
	IsOk             *bool             `protobuf:"varint,1,req,name=is_ok" json:"is_ok,omitempty"`
	Error            *Error            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Consumed         *ConsumedCapacity `protobuf:"bytes,3,opt,name=consumed" json:"consumed,omitempty"`
	Row              []byte            `protobuf:"bytes,4,opt,name=row" json:"row,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RowInBatchWriteRowResponse) Reset()                    { *m = RowInBatchWriteRowResponse{} }
func (m *RowInBatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*RowInBatchWriteRowResponse) ProtoMessage()               {}
func (*RowInBatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{42} }

func (m *RowInBatchWriteRowResponse) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return false
}

func (m *RowInBatchWriteRowResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RowInBatchWriteRowResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *RowInBatchWriteRowResponse) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

type TableInBatchWriteRowResponse struct {
	TableName        *string                       `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Rows             []*RowInBatchWriteRowResponse `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TableInBatchWriteRowResponse) Reset()                    { *m = TableInBatchWriteRowResponse{} }
func (m *TableInBatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*TableInBatchWriteRowResponse) ProtoMessage()               {}
func (*TableInBatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{43} }

func (m *TableInBatchWriteRowResponse) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TableInBatchWriteRowResponse) GetRows() []*RowInBatchWriteRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

type BatchWriteRowResponse struct {
	Tables           []*TableInBatchWriteRowResponse `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *BatchWriteRowResponse) Reset()                    { *m = BatchWriteRowResponse{} }
func (m *BatchWriteRowResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchWriteRowResponse) ProtoMessage()               {}
func (*BatchWriteRowResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{44} }

func (m *BatchWriteRowResponse) GetTables() []*TableInBatchWriteRowResponse {
	if m != nil {
		return m.Tables
	}
	return nil
}

// *
// HBase支持以下参数：
//     1. TimeRange或指定time
//     2. Filter（根据列值或列名来过滤）
// 我们只支持给同版本的选择条件。
type GetRangeRequest struct {
	TableName                *string    `protobuf:"bytes,1,req,name=table_name" json:"table_name,omitempty"`
	Direction                *Direction `protobuf:"varint,2,req,name=direction,enum=otsprotocol.Direction" json:"direction,omitempty"`
	ColumnsToGet             []string   `protobuf:"bytes,3,rep,name=columns_to_get" json:"columns_to_get,omitempty"`
	TimeRange                *TimeRange `protobuf:"bytes,4,opt,name=time_range" json:"time_range,omitempty"`
	MaxVersions              *int32     `protobuf:"varint,5,opt,name=max_versions" json:"max_versions,omitempty"`
	Limit                    *int32     `protobuf:"varint,6,opt,name=limit" json:"limit,omitempty"`
	InclusiveStartPrimaryKey []byte     `protobuf:"bytes,7,req,name=inclusive_start_primary_key" json:"inclusive_start_primary_key,omitempty"`
	ExclusiveEndPrimaryKey   []byte     `protobuf:"bytes,8,req,name=exclusive_end_primary_key" json:"exclusive_end_primary_key,omitempty"`
	CacheBlocks              *bool      `protobuf:"varint,9,opt,name=cache_blocks,def=1" json:"cache_blocks,omitempty"`
	Filter                   []byte     `protobuf:"bytes,10,opt,name=filter" json:"filter,omitempty"`
	StartColumn              *string    `protobuf:"bytes,11,opt,name=start_column" json:"start_column,omitempty"`
	EndColumn                *string    `protobuf:"bytes,12,opt,name=end_column" json:"end_column,omitempty"`
	Token                    []byte     `protobuf:"bytes,13,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized         []byte     `json:"-"`
}

func (m *GetRangeRequest) Reset()                    { *m = GetRangeRequest{} }
func (m *GetRangeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRangeRequest) ProtoMessage()               {}
func (*GetRangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{45} }

const Default_GetRangeRequest_CacheBlocks bool = true

func (m *GetRangeRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetRangeRequest) GetDirection() Direction {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Direction_FORWARD
}

func (m *GetRangeRequest) GetColumnsToGet() []string {
	if m != nil {
		return m.ColumnsToGet
	}
	return nil
}

func (m *GetRangeRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *GetRangeRequest) GetMaxVersions() int32 {
	if m != nil && m.MaxVersions != nil {
		return *m.MaxVersions
	}
	return 0
}

func (m *GetRangeRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *GetRangeRequest) GetInclusiveStartPrimaryKey() []byte {
	if m != nil {
		return m.InclusiveStartPrimaryKey
	}
	return nil
}

func (m *GetRangeRequest) GetExclusiveEndPrimaryKey() []byte {
	if m != nil {
		return m.ExclusiveEndPrimaryKey
	}
	return nil
}

func (m *GetRangeRequest) GetCacheBlocks() bool {
	if m != nil && m.CacheBlocks != nil {
		return *m.CacheBlocks
	}
	return Default_GetRangeRequest_CacheBlocks
}

func (m *GetRangeRequest) GetFilter() []byte {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GetRangeRequest) GetStartColumn() string {
	if m != nil && m.StartColumn != nil {
		return *m.StartColumn
	}
	return ""
}

func (m *GetRangeRequest) GetEndColumn() string {
	if m != nil && m.EndColumn != nil {
		return *m.EndColumn
	}
	return ""
}

func (m *GetRangeRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetRangeResponse struct {
	Consumed            *ConsumedCapacity `protobuf:"bytes,1,req,name=consumed" json:"consumed,omitempty"`
	Rows                []byte            `protobuf:"bytes,2,req,name=rows" json:"rows,omitempty"`
	NextStartPrimaryKey []byte            `protobuf:"bytes,3,opt,name=next_start_primary_key" json:"next_start_primary_key,omitempty"`
	NextToken           []byte            `protobuf:"bytes,4,opt,name=next_token" json:"next_token,omitempty"`
	XXX_unrecognized    []byte            `json:"-"`
}

func (m *GetRangeResponse) Reset()                    { *m = GetRangeResponse{} }
func (m *GetRangeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRangeResponse) ProtoMessage()               {}
func (*GetRangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{46} }

func (m *GetRangeResponse) GetConsumed() *ConsumedCapacity {
	if m != nil {
		return m.Consumed
	}
	return nil
}

func (m *GetRangeResponse) GetRows() []byte {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *GetRangeResponse) GetNextStartPrimaryKey() []byte {
	if m != nil {
		return m.NextStartPrimaryKey
	}
	return nil
}

func (m *GetRangeResponse) GetNextToken() []byte {
	if m != nil {
		return m.NextToken
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "otsprotocol.Error")
	proto.RegisterType((*PrimaryKeySchema)(nil), "otsprotocol.PrimaryKeySchema")
	proto.RegisterType((*PartitionRange)(nil), "otsprotocol.PartitionRange")
	proto.RegisterType((*TableOptions)(nil), "otsprotocol.TableOptions")
	proto.RegisterType((*TableMeta)(nil), "otsprotocol.TableMeta")
	proto.RegisterType((*Condition)(nil), "otsprotocol.Condition")
	proto.RegisterType((*CapacityUnit)(nil), "otsprotocol.CapacityUnit")
	proto.RegisterType((*ReservedThroughputDetails)(nil), "otsprotocol.ReservedThroughputDetails")
	proto.RegisterType((*ReservedThroughput)(nil), "otsprotocol.ReservedThroughput")
	proto.RegisterType((*ConsumedCapacity)(nil), "otsprotocol.ConsumedCapacity")
	proto.RegisterType((*CreateTableRequest)(nil), "otsprotocol.CreateTableRequest")
	proto.RegisterType((*CreateTableResponse)(nil), "otsprotocol.CreateTableResponse")
	proto.RegisterType((*UpdateTableRequest)(nil), "otsprotocol.UpdateTableRequest")
	proto.RegisterType((*UpdateTableResponse)(nil), "otsprotocol.UpdateTableResponse")
	proto.RegisterType((*DescribeTableRequest)(nil), "otsprotocol.DescribeTableRequest")
	proto.RegisterType((*DescribeTableResponse)(nil), "otsprotocol.DescribeTableResponse")
	proto.RegisterType((*ListTableRequest)(nil), "otsprotocol.ListTableRequest")
	proto.RegisterType((*ListTableResponse)(nil), "otsprotocol.ListTableResponse")
	proto.RegisterType((*DeleteTableRequest)(nil), "otsprotocol.DeleteTableRequest")
	proto.RegisterType((*DeleteTableResponse)(nil), "otsprotocol.DeleteTableResponse")
	proto.RegisterType((*LoadTableRequest)(nil), "otsprotocol.LoadTableRequest")
	proto.RegisterType((*LoadTableResponse)(nil), "otsprotocol.LoadTableResponse")
	proto.RegisterType((*UnloadTableRequest)(nil), "otsprotocol.UnloadTableRequest")
	proto.RegisterType((*UnloadTableResponse)(nil), "otsprotocol.UnloadTableResponse")
	proto.RegisterType((*TimeRange)(nil), "otsprotocol.TimeRange")
	proto.RegisterType((*ReturnContent)(nil), "otsprotocol.ReturnContent")
	proto.RegisterType((*GetRowRequest)(nil), "otsprotocol.GetRowRequest")
	proto.RegisterType((*GetRowResponse)(nil), "otsprotocol.GetRowResponse")
	proto.RegisterType((*UpdateRowRequest)(nil), "otsprotocol.UpdateRowRequest")
	proto.RegisterType((*UpdateRowResponse)(nil), "otsprotocol.UpdateRowResponse")
	proto.RegisterType((*PutRowRequest)(nil), "otsprotocol.PutRowRequest")
	proto.RegisterType((*PutRowResponse)(nil), "otsprotocol.PutRowResponse")
	proto.RegisterType((*DeleteRowRequest)(nil), "otsprotocol.DeleteRowRequest")
	proto.RegisterType((*DeleteRowResponse)(nil), "otsprotocol.DeleteRowResponse")
	proto.RegisterType((*TableInBatchGetRowRequest)(nil), "otsprotocol.TableInBatchGetRowRequest")
	proto.RegisterType((*BatchGetRowRequest)(nil), "otsprotocol.BatchGetRowRequest")
	proto.RegisterType((*RowInBatchGetRowResponse)(nil), "otsprotocol.RowInBatchGetRowResponse")
	proto.RegisterType((*TableInBatchGetRowResponse)(nil), "otsprotocol.TableInBatchGetRowResponse")
	proto.RegisterType((*BatchGetRowResponse)(nil), "otsprotocol.BatchGetRowResponse")
	proto.RegisterType((*RowInBatchWriteRowRequest)(nil), "otsprotocol.RowInBatchWriteRowRequest")
	proto.RegisterType((*TableInBatchWriteRowRequest)(nil), "otsprotocol.TableInBatchWriteRowRequest")
	proto.RegisterType((*BatchWriteRowRequest)(nil), "otsprotocol.BatchWriteRowRequest")
	proto.RegisterType((*RowInBatchWriteRowResponse)(nil), "otsprotocol.RowInBatchWriteRowResponse")
	proto.RegisterType((*TableInBatchWriteRowResponse)(nil), "otsprotocol.TableInBatchWriteRowResponse")
	proto.RegisterType((*BatchWriteRowResponse)(nil), "otsprotocol.BatchWriteRowResponse")
	proto.RegisterType((*GetRangeRequest)(nil), "otsprotocol.GetRangeRequest")
	proto.RegisterType((*GetRangeResponse)(nil), "otsprotocol.GetRangeResponse")
	proto.RegisterEnum("otsprotocol.PrimaryKeyType", PrimaryKeyType_name, PrimaryKeyType_value)
	proto.RegisterEnum("otsprotocol.PrimaryKeyOption", PrimaryKeyOption_name, PrimaryKeyOption_value)
	proto.RegisterEnum("otsprotocol.BloomFilterType", BloomFilterType_name, BloomFilterType_value)
	proto.RegisterEnum("otsprotocol.TableStatus", TableStatus_name, TableStatus_value)
	proto.RegisterEnum("otsprotocol.RowExistenceExpectation", RowExistenceExpectation_name, RowExistenceExpectation_value)
	proto.RegisterEnum("otsprotocol.ReturnType", ReturnType_name, ReturnType_value)
	proto.RegisterEnum("otsprotocol.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("otsprotocol.Direction", Direction_name, Direction_value)
}

func init() { proto.RegisterFile("table_store.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x58, 0x4b, 0x73, 0xdb, 0x46,
	0x12, 0x36, 0x08, 0x82, 0x8f, 0xe6, 0xc3, 0xd0, 0x50, 0xb2, 0x29, 0xc9, 0xde, 0x95, 0xb1, 0xb6,
	0x0c, 0x71, 0xbd, 0xb2, 0x4b, 0xbb, 0x5e, 0xef, 0xf3, 0x20, 0x91, 0xb0, 0xc2, 0x92, 0x4c, 0xd2,
	0x10, 0x15, 0x3b, 0x27, 0x14, 0x04, 0x8e, 0x25, 0x94, 0x40, 0x80, 0x01, 0x86, 0x7a, 0xf8, 0x9a,
	0x72, 0x55, 0x0e, 0xa9, 0xca, 0x25, 0x87, 0x24, 0x87, 0xfc, 0x84, 0x9c, 0xf3, 0x77, 0x72, 0xc9,
	0x5f, 0xc8, 0x35, 0x35, 0x03, 0x40, 0x04, 0x20, 0xc8, 0xb4, 0x65, 0x2b, 0xb9, 0x11, 0x83, 0x46,
	0x4f, 0xf7, 0xd7, 0xdf, 0x7c, 0x3d, 0x4d, 0x98, 0x21, 0xfa, 0x9e, 0x85, 0x35, 0x8f, 0x38, 0x2e,
	0x5e, 0x1d, 0xb9, 0x0e, 0x71, 0x50, 0xc9, 0x21, 0x1e, 0xfb, 0x65, 0x38, 0x96, 0xb4, 0x0c, 0x82,
	0xe2, 0xba, 0x8e, 0x8b, 0xca, 0x90, 0x35, 0x9c, 0x01, 0xae, 0x73, 0x4b, 0x19, 0xb9, 0x88, 0xae,
	0x43, 0x7e, 0x88, 0x3d, 0x4f, 0xdf, 0xc7, 0xf5, 0xcc, 0x12, 0x27, 0x17, 0xa5, 0xd7, 0x20, 0xf6,
	0x5c, 0x73, 0xa8, 0xbb, 0xa7, 0x5b, 0xf8, 0x74, 0xc7, 0x38, 0xc0, 0x43, 0x9d, 0x7e, 0x62, 0xeb,
	0xc3, 0xf0, 0x93, 0x15, 0xc8, 0x92, 0xd3, 0x11, 0xb5, 0xcf, 0xc8, 0xd5, 0xb5, 0xc5, 0xd5, 0xc8,
	0x2e, 0xab, 0x93, 0x4f, 0xfb, 0xa7, 0x23, 0x8c, 0xfe, 0x06, 0x39, 0x67, 0x44, 0x4c, 0xc7, 0xae,
	0xf3, 0x4b, 0x9c, 0x5c, 0x5d, 0xbb, 0x7d, 0x81, 0x71, 0x97, 0x19, 0x49, 0x0f, 0xa0, 0xda, 0xd3,
	0x5d, 0x62, 0xd2, 0x07, 0x55, 0xb7, 0xf7, 0x31, 0xaa, 0x80, 0xb0, 0x87, 0xf7, 0x4d, 0x9b, 0x6d,
	0x5d, 0x46, 0x25, 0xe0, 0xb1, 0x3d, 0x60, 0x3b, 0x97, 0xa5, 0x1f, 0x39, 0x28, 0xf7, 0x69, 0xd2,
	0xfe, 0xd7, 0x1e, 0x9a, 0x85, 0x32, 0x31, 0x87, 0x58, 0x23, 0x8e, 0x66, 0x99, 0x47, 0x34, 0x5c,
	0x4e, 0x16, 0xe8, 0xea, 0x50, 0x3f, 0xd1, 0x8e, 0xb0, 0xeb, 0x51, 0x2b, 0x96, 0xa6, 0x80, 0x9e,
	0xc0, 0xcc, 0x9e, 0xe5, 0x38, 0x43, 0xed, 0x95, 0x69, 0x11, 0xec, 0x6a, 0x2c, 0x23, 0x3f, 0xc8,
	0x5b, 0xb1, 0x20, 0x37, 0xa8, 0xd5, 0x53, 0x66, 0xc4, 0x52, 0x42, 0x00, 0x7b, 0x96, 0x63, 0x1c,
	0x6a, 0x9e, 0xf9, 0x1a, 0xd7, 0xb3, 0xcc, 0xd9, 0x3d, 0xb8, 0x3d, 0xc0, 0x47, 0xa6, 0x4e, 0xc3,
	0xd0, 0x0c, 0x6c, 0x59, 0xe1, 0x6e, 0x9a, 0x69, 0x6b, 0x1e, 0x36, 0xea, 0xc2, 0x12, 0x27, 0xf3,
	0xd2, 0x0e, 0x14, 0x59, 0xbc, 0xcf, 0x30, 0xd1, 0xa9, 0x1f, 0xbf, 0x62, 0x11, 0x64, 0xd7, 0xa0,
	0x34, 0xf2, 0x31, 0xd1, 0x0e, 0xf1, 0x69, 0x3d, 0xb3, 0xc4, 0xcb, 0xa5, 0x0b, 0x31, 0xf3, 0x6b,
	0x23, 0xed, 0x41, 0xb1, 0xe9, 0xd8, 0x03, 0x86, 0x19, 0xfa, 0x2f, 0x54, 0x5c, 0xe7, 0x58, 0xc3,
	0x27, 0xa6, 0x47, 0xb0, 0x6d, 0xf8, 0x7e, 0xab, 0x6b, 0x77, 0x63, 0x2e, 0x54, 0xe7, 0x58, 0x09,
	0x0d, 0x94, 0x93, 0x11, 0x36, 0x08, 0x0b, 0x1c, 0xd5, 0x41, 0x34, 0x1c, 0x6b, 0x3c, 0xb4, 0x35,
	0x23, 0x74, 0xc8, 0xc0, 0x2a, 0x4b, 0x7f, 0x85, 0x72, 0x53, 0x1f, 0xe9, 0x86, 0x49, 0x4e, 0x77,
	0x6d, 0x93, 0x50, 0x3e, 0xb8, 0x58, 0x1f, 0x04, 0x00, 0x57, 0x40, 0x38, 0x76, 0x4d, 0xe2, 0x13,
	0x48, 0x90, 0xde, 0x70, 0x30, 0xaf, 0x62, 0x0f, 0xbb, 0x47, 0x78, 0xd0, 0x3f, 0x70, 0x9d, 0xf1,
	0xfe, 0xc1, 0x68, 0x4c, 0x5a, 0x98, 0xe8, 0xa6, 0xe5, 0xa1, 0x47, 0x50, 0x31, 0x02, 0x57, 0xda,
	0xd8, 0x36, 0x09, 0x8b, 0xb0, 0xb4, 0x36, 0x1f, 0x8b, 0x30, 0xb6, 0xd9, 0x02, 0x20, 0x4b, 0xf7,
	0x88, 0x66, 0xda, 0x86, 0x8b, 0x75, 0x0f, 0x6b, 0xb4, 0xc6, 0x8c, 0x02, 0xfc, 0xd9, 0xbb, 0x01,
	0x8e, 0xbe, 0xe3, 0x19, 0xda, 0x4f, 0x01, 0x9d, 0x0f, 0xe3, 0xfd, 0xf7, 0x97, 0x5a, 0x20, 0x36,
	0x1d, 0xdb, 0x1b, 0x0f, 0xf1, 0x20, 0x5c, 0xbf, 0x84, 0x97, 0x9f, 0x39, 0x40, 0x4d, 0x17, 0xeb,
	0x04, 0x33, 0x0a, 0xa8, 0xf8, 0xf3, 0x31, 0xf6, 0x08, 0x6a, 0x84, 0x2c, 0x18, 0x62, 0xa2, 0x07,
	0x5e, 0x6e, 0xc4, 0xbc, 0x4c, 0x18, 0xf3, 0x3f, 0xa8, 0xb9, 0x41, 0x42, 0x1a, 0x39, 0xcb, 0x88,
	0x21, 0x51, 0x5a, 0xfb, 0x73, 0xbc, 0xc4, 0xa9, 0x89, 0xfb, 0x3b, 0xf9, 0x07, 0xd2, 0x63, 0x28,
	0x25, 0x43, 0x8e, 0x1d, 0xa7, 0x87, 0x00, 0xa3, 0xf0, 0x34, 0x7a, 0xf5, 0x2c, 0x23, 0x63, 0xe2,
	0xb4, 0xc7, 0x0e, 0xab, 0x34, 0x07, 0xb5, 0x58, 0x8a, 0xde, 0xc8, 0xb1, 0x3d, 0x2c, 0x7d, 0xcb,
	0x01, 0xda, 0x1d, 0x0d, 0x92, 0xa9, 0xa7, 0x1d, 0x80, 0x0b, 0x53, 0xe4, 0xae, 0x24, 0x45, 0xe9,
	0x1b, 0x0e, 0x6a, 0xb1, 0xd0, 0xfc, 0x90, 0xd1, 0x16, 0x2c, 0xa6, 0xc4, 0xa1, 0x0d, 0x7c, 0x12,
	0x07, 0x75, 0x5a, 0x9e, 0x12, 0x4f, 0x84, 0xf2, 0xf1, 0xb0, 0x32, 0x29, 0x64, 0x89, 0x85, 0xd5,
	0x80, 0xd9, 0x16, 0xf6, 0x0c, 0xd7, 0xdc, 0x9b, 0x0a, 0x99, 0xf4, 0x65, 0x06, 0xe6, 0x12, 0xc6,
	0x41, 0x12, 0xef, 0xc3, 0xad, 0x29, 0x09, 0x67, 0x3e, 0x2c, 0x61, 0x7e, 0x4a, 0xc2, 0x68, 0x15,
	0xca, 0x61, 0xfb, 0xd2, 0xc9, 0x98, 0x92, 0x8d, 0xca, 0x56, 0xfd, 0xfc, 0x07, 0x3b, 0xec, 0x3d,
	0xd5, 0x74, 0xef, 0x40, 0x77, 0x07, 0x9a, 0x37, 0xb2, 0x4c, 0xe2, 0xd5, 0x73, 0x4b, 0xbc, 0x5c,
	0x96, 0x10, 0x88, 0xdb, 0xa6, 0x47, 0xa2, 0x90, 0x49, 0x32, 0xcc, 0x44, 0xd6, 0x02, 0x64, 0x6a,
	0x50, 0x9a, 0xe0, 0x48, 0xcb, 0xc9, 0xcb, 0x45, 0x49, 0x06, 0xd4, 0xc2, 0x16, 0x9e, 0xce, 0x52,
	0xca, 0xf3, 0x98, 0x65, 0xc0, 0xf3, 0x65, 0x10, 0xb7, 0x1d, 0x7d, 0x30, 0xf5, 0xf3, 0x1a, 0xcc,
	0x44, 0xec, 0x82, 0x8f, 0x65, 0x40, 0xbb, 0xb6, 0xf5, 0x2e, 0x9f, 0xcf, 0x41, 0x2d, 0x66, 0x19,
	0x38, 0xf8, 0x04, 0x8a, 0x7d, 0x73, 0x88, 0xfd, 0xb6, 0x89, 0x00, 0x3c, 0xa2, 0xbb, 0xc4, 0xd7,
	0x43, 0x2a, 0xd3, 0x3c, 0x12, 0xa1, 0x80, 0xed, 0x41, 0xa8, 0x9e, 0x74, 0x65, 0x0e, 0x2a, 0xde,
	0x08, 0x1b, 0xe6, 0x2b, 0xd3, 0x88, 0x0a, 0xe7, 0xff, 0xa1, 0xa2, 0x62, 0x32, 0x76, 0xed, 0xa6,
	0x63, 0x13, 0x6c, 0x13, 0xf4, 0x00, 0x4a, 0x2e, 0x5b, 0xf0, 0xbb, 0x24, 0xc7, 0xba, 0xe4, 0xcd,
	0x04, 0x19, 0xe8, 0x7b, 0xda, 0x20, 0xa5, 0x5f, 0x39, 0xa8, 0x6c, 0x62, 0xa2, 0x3a, 0xc7, 0x6f,
	0x3b, 0xe9, 0xb5, 0x64, 0xab, 0xa3, 0xed, 0xfd, 0x06, 0x54, 0xfd, 0x0e, 0xe4, 0xd1, 0x1e, 0xbe,
	0x8f, 0x49, 0x9d, 0xa7, 0xa5, 0x61, 0x4c, 0xa6, 0x8d, 0xdd, 0xa5, 0xc9, 0xb1, 0x9e, 0x7b, 0x8e,
	0xc9, 0x67, 0xa9, 0x27, 0xdb, 0xbd, 0xc0, 0x7a, 0xd4, 0x02, 0x94, 0x0d, 0xdd, 0x38, 0xc0, 0x1a,
	0xeb, 0xdd, 0x94, 0x30, 0x9c, 0x5c, 0xf8, 0x4f, 0x96, 0xb8, 0x63, 0x8c, 0xaa, 0x90, 0xf3, 0x2f,
	0x01, 0xf5, 0x3c, 0xed, 0x76, 0x8c, 0x5c, 0x0c, 0x3c, 0x3f, 0x96, 0x7a, 0x81, 0xde, 0x8b, 0x68,
	0x12, 0x14, 0xbe, 0x60, 0xad, 0xc8, 0xd6, 0x2a, 0x20, 0x10, 0xe7, 0x10, 0xdb, 0x75, 0x60, 0x6d,
	0x72, 0x0f, 0xaa, 0x61, 0xe2, 0x01, 0xd1, 0x1e, 0x42, 0xc1, 0x08, 0x7a, 0x47, 0x70, 0x00, 0xe3,
	0xdd, 0xfc, 0x5c, 0x63, 0x29, 0x01, 0xef, 0x3a, 0xc7, 0x01, 0x1c, 0x08, 0xc0, 0xc6, 0x27, 0x44,
	0xf3, 0xf7, 0xe0, 0xd9, 0x1e, 0xdf, 0x71, 0x20, 0xfa, 0x8a, 0x35, 0x05, 0x60, 0x04, 0x40, 0xaf,
	0x02, 0xc6, 0x01, 0xc3, 0xcc, 0x77, 0xb8, 0x02, 0xc5, 0x49, 0x6b, 0xe7, 0x53, 0x04, 0x61, 0x72,
	0x93, 0x58, 0x83, 0x6a, 0x50, 0x73, 0xc3, 0x67, 0x41, 0x00, 0xfb, 0x42, 0x4a, 0xd9, 0x03, 0x9e,
	0x48, 0xcf, 0x61, 0x26, 0x12, 0xda, 0x07, 0x43, 0x40, 0xd3, 0xfd, 0x9a, 0x83, 0x4a, 0x6f, 0x3c,
	0x8d, 0x4c, 0x31, 0xd4, 0xae, 0x38, 0xc9, 0x0e, 0x54, 0xc3, 0x80, 0x3e, 0x4a, 0x86, 0xdf, 0x73,
	0x20, 0xfa, 0x6a, 0x72, 0x99, 0x13, 0x73, 0xf5, 0x15, 0x8d, 0xc4, 0xf6, 0x51, 0xf2, 0xfd, 0x22,
	0x03, 0xf3, 0x4c, 0xb9, 0xda, 0xf6, 0x86, 0x4e, 0x8c, 0x83, 0x4b, 0x48, 0x05, 0x2f, 0x97, 0x27,
	0x47, 0x8f, 0x67, 0x8f, 0xe7, 0x95, 0x23, 0x9b, 0xa2, 0x1c, 0xc2, 0x7b, 0x29, 0x47, 0x2e, 0x55,
	0x39, 0xf2, 0xa9, 0xca, 0x51, 0x48, 0x55, 0x8e, 0x62, 0x8a, 0x72, 0x00, 0x9b, 0xb2, 0xb6, 0x01,
	0xa5, 0x64, 0xff, 0x4f, 0xc8, 0xb1, 0xec, 0xfd, 0x96, 0x94, 0x6c, 0xb8, 0x17, 0xa2, 0x26, 0xfd,
	0xc0, 0x41, 0x5d, 0x75, 0x8e, 0x13, 0xef, 0x82, 0x72, 0x55, 0x40, 0x30, 0x3d, 0xcd, 0x39, 0x64,
	0x68, 0x16, 0xd0, 0x1d, 0x10, 0x30, 0x9d, 0x03, 0x83, 0x4b, 0x15, 0x8a, 0x6d, 0xe1, 0x4f, 0x88,
	0xd1, 0x02, 0xfb, 0x57, 0xa8, 0x77, 0x2b, 0x70, 0x96, 0x81, 0x10, 0x57, 0x2d, 0x81, 0x15, 0x1d,
	0xc3, 0x42, 0x5a, 0xf4, 0x41, 0x84, 0x69, 0x45, 0xff, 0x3b, 0x64, 0x5d, 0xe7, 0xd8, 0x0b, 0x66,
	0xa0, 0x7b, 0xc9, 0x01, 0x26, 0xd5, 0x91, 0xd4, 0x81, 0x5a, 0x9a, 0xff, 0x27, 0x09, 0x58, 0xef,
	0x4f, 0x85, 0x35, 0xf0, 0xf7, 0x13, 0x1d, 0x65, 0xce, 0x36, 0x7b, 0x41, 0x87, 0x9c, 0x48, 0xb5,
	0xe4, 0x60, 0x0e, 0xf6, 0x67, 0xac, 0xf8, 0x31, 0xea, 0x8e, 0xb0, 0xcb, 0xa6, 0xaa, 0x70, 0x66,
	0xfc, 0xbd, 0xb5, 0x78, 0x1f, 0x16, 0xa3, 0x89, 0x25, 0x63, 0x4f, 0x83, 0xfc, 0x1f, 0x31, 0xc8,
	0x97, 0x2f, 0x80, 0x3c, 0xe1, 0x49, 0xea, 0xc1, 0x6c, 0xea, 0x0e, 0xff, 0x4a, 0x80, 0x2e, 0x5f,
	0x08, 0x7a, 0xd2, 0xe3, 0x57, 0x1c, 0x2c, 0xa4, 0xed, 0xf7, 0xc7, 0xf0, 0x59, 0x32, 0xe1, 0x56,
	0x7a, 0xb4, 0x6f, 0x61, 0xef, 0xe3, 0x18, 0x94, 0xf7, 0xa7, 0x42, 0x19, 0xf0, 0x4d, 0x85, 0xb9,
	0xf4, 0x3d, 0xfe, 0x9d, 0x00, 0x73, 0xe5, 0x1d, 0xc0, 0x0c, 0x7c, 0xfe, 0x92, 0x81, 0xeb, 0x94,
	0xd6, 0x94, 0x7a, 0x6f, 0xab, 0xfe, 0x0a, 0x14, 0x07, 0xa6, 0x8b, 0x8d, 0x60, 0xec, 0xa7, 0x94,
	0x8e, 0xf3, 0xb1, 0x15, 0xbe, 0xbd, 0xc2, 0x6b, 0x5a, 0x05, 0x04, 0xcb, 0x1c, 0x9a, 0x24, 0xd0,
	0xde, 0xbf, 0xc0, 0xa2, 0x69, 0x1b, 0xd6, 0xd8, 0x33, 0x8f, 0xd8, 0x68, 0xe0, 0x12, 0x2d, 0xda,
	0x09, 0xf2, 0xec, 0x20, 0xdd, 0x81, 0x79, 0x7c, 0x12, 0x1a, 0x51, 0xa1, 0x8d, 0x9a, 0x14, 0x98,
	0x49, 0x52, 0xc3, 0x8b, 0xa9, 0x1a, 0x0e, 0xa9, 0x1a, 0x5e, 0x4a, 0xd1, 0xf0, 0x72, 0xfc, 0xf6,
	0x57, 0x61, 0x3c, 0x79, 0xc3, 0x81, 0x38, 0x01, 0xfa, 0xb2, 0xbd, 0xb2, 0x7c, 0xc6, 0x1c, 0x1a,
	0xf8, 0x9f, 0xe0, 0x06, 0xd3, 0xd2, 0xf3, 0xb9, 0xf3, 0x29, 0x5a, 0xcb, 0xf8, 0xda, 0x78, 0x0c,
	0xd5, 0xc4, 0xbf, 0x70, 0x25, 0xc8, 0xb7, 0x3b, 0x7d, 0x65, 0x53, 0x51, 0x45, 0x0e, 0x01, 0xe4,
	0x76, 0xfa, 0x6a, 0xbb, 0xb3, 0x29, 0x66, 0xe8, 0xef, 0x8d, 0x76, 0x67, 0x5d, 0xfd, 0x4c, 0xe4,
	0x1b, 0xcb, 0xd1, 0xff, 0xfd, 0xfc, 0xb9, 0x0c, 0x21, 0xa8, 0xae, 0xef, 0xf6, 0xbb, 0x5a, 0xbb,
	0xd3, 0x54, 0x95, 0x67, 0x4a, 0xa7, 0x2f, 0x72, 0x8d, 0x55, 0xb8, 0x9e, 0xfc, 0x4b, 0xac, 0x00,
	0xd9, 0x4e, 0xb7, 0xa3, 0x88, 0x1c, 0xfd, 0xd5, 0x54, 0xb6, 0xb7, 0xc5, 0x0c, 0xca, 0x03, 0xaf,
	0x76, 0x5f, 0x88, 0x7c, 0xe3, 0x39, 0x94, 0xa2, 0x93, 0x1b, 0x40, 0x6e, 0xbd, 0xd9, 0x6f, 0x7f,
	0x4a, 0xad, 0xcb, 0x50, 0x68, 0x77, 0x82, 0xa7, 0x0c, 0x8d, 0x72, 0xbb, 0xbb, 0xde, 0xa2, 0x91,
	0xf1, 0xa8, 0x02, 0xc5, 0xdd, 0x4e, 0xf8, 0x98, 0xa5, 0x96, 0xbb, 0xbd, 0xd6, 0x7a, 0x9f, 0x3e,
	0x09, 0x8d, 0x67, 0x70, 0xf3, 0xa2, 0xff, 0xb0, 0x00, 0x72, 0xed, 0xcd, 0x4e, 0x57, 0x55, 0xc4,
	0x6b, 0x48, 0x84, 0xb2, 0xf2, 0xb2, 0xa7, 0x34, 0xfb, 0x9a, 0xf2, 0xb2, 0xbd, 0xd3, 0x17, 0x39,
	0x34, 0x0b, 0x62, 0xb0, 0xd2, 0xe9, 0x86, 0xab, 0x99, 0xc6, 0x5d, 0x80, 0xc9, 0xf8, 0x42, 0xc3,
	0x50, 0xe9, 0xfb, 0x0e, 0x75, 0x51, 0x04, 0x41, 0xed, 0x6b, 0xbd, 0x2d, 0x91, 0x6b, 0x3c, 0x82,
	0x4a, 0x5c, 0xd4, 0xf3, 0xc0, 0xf7, 0x76, 0xfb, 0x3e, 0xa2, 0x2c, 0x38, 0xc5, 0x47, 0xb4, 0xa5,
	0x6c, 0x2b, 0x7d, 0x85, 0x21, 0x5a, 0x9c, 0x9c, 0x99, 0x12, 0xe4, 0x9f, 0x76, 0xd5, 0x17, 0xeb,
	0x6a, 0x4b, 0xbc, 0x46, 0xd3, 0xd9, 0x58, 0x6f, 0x6e, 0xb1, 0x27, 0xee, 0xb7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xae, 0x29, 0x35, 0x4b, 0xba, 0x15, 0x00, 0x00,
}
