// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global_table.proto

package otsprotocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncMode int32

const (
	SyncMode_SYNC_MODE_ROW    SyncMode = 1
	SyncMode_SYNC_MODE_COLUMN SyncMode = 2
)

var SyncMode_name = map[int32]string{
	1: "SYNC_MODE_ROW",
	2: "SYNC_MODE_COLUMN",
}

var SyncMode_value = map[string]int32{
	"SYNC_MODE_ROW":    1,
	"SYNC_MODE_COLUMN": 2,
}

func (x SyncMode) Enum() *SyncMode {
	p := new(SyncMode)
	*p = x
	return p
}

func (x SyncMode) String() string {
	return proto.EnumName(SyncMode_name, int32(x))
}

func (x *SyncMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncMode_value, data, "SyncMode")
	if err != nil {
		return err
	}
	*x = SyncMode(value)
	return nil
}

func (SyncMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{0}
}

type GlobalTableStatus int32

const (
	GlobalTableStatus_G_INIT    GlobalTableStatus = 1
	GlobalTableStatus_G_RE_CONF GlobalTableStatus = 2
	GlobalTableStatus_G_ACTIVE  GlobalTableStatus = 3
)

var GlobalTableStatus_name = map[int32]string{
	1: "G_INIT",
	2: "G_RE_CONF",
	3: "G_ACTIVE",
}

var GlobalTableStatus_value = map[string]int32{
	"G_INIT":    1,
	"G_RE_CONF": 2,
	"G_ACTIVE":  3,
}

func (x GlobalTableStatus) Enum() *GlobalTableStatus {
	p := new(GlobalTableStatus)
	*p = x
	return p
}

func (x GlobalTableStatus) String() string {
	return proto.EnumName(GlobalTableStatus_name, int32(x))
}

func (x *GlobalTableStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GlobalTableStatus_value, data, "GlobalTableStatus")
	if err != nil {
		return err
	}
	*x = GlobalTableStatus(value)
	return nil
}

func (GlobalTableStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{1}
}

type PhyTableStatus int32

const (
	PhyTableStatus_PHY_PENDING   PhyTableStatus = 1
	PhyTableStatus_PHY_INIT      PhyTableStatus = 2
	PhyTableStatus_PHY_SYNCDATA  PhyTableStatus = 3
	PhyTableStatus_PHY_READY     PhyTableStatus = 4
	PhyTableStatus_PHY_ACTIVE    PhyTableStatus = 5
	PhyTableStatus_PHY_UNBINDING PhyTableStatus = 6
	PhyTableStatus_PHY_UNBOUND   PhyTableStatus = 7
)

var PhyTableStatus_name = map[int32]string{
	1: "PHY_PENDING",
	2: "PHY_INIT",
	3: "PHY_SYNCDATA",
	4: "PHY_READY",
	5: "PHY_ACTIVE",
	6: "PHY_UNBINDING",
	7: "PHY_UNBOUND",
}

var PhyTableStatus_value = map[string]int32{
	"PHY_PENDING":   1,
	"PHY_INIT":      2,
	"PHY_SYNCDATA":  3,
	"PHY_READY":     4,
	"PHY_ACTIVE":    5,
	"PHY_UNBINDING": 6,
	"PHY_UNBOUND":   7,
}

func (x PhyTableStatus) Enum() *PhyTableStatus {
	p := new(PhyTableStatus)
	*p = x
	return p
}

func (x PhyTableStatus) String() string {
	return proto.EnumName(PhyTableStatus_name, int32(x))
}

func (x *PhyTableStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PhyTableStatus_value, data, "PhyTableStatus")
	if err != nil {
		return err
	}
	*x = PhyTableStatus(value)
	return nil
}

func (PhyTableStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{2}
}

type SyncStage int32

const (
	SyncStage_SYNC_INIT SyncStage = 1
	SyncStage_SYNC_FULL SyncStage = 2
	SyncStage_SYNC_INCR SyncStage = 3
)

var SyncStage_name = map[int32]string{
	1: "SYNC_INIT",
	2: "SYNC_FULL",
	3: "SYNC_INCR",
}

var SyncStage_value = map[string]int32{
	"SYNC_INIT": 1,
	"SYNC_FULL": 2,
	"SYNC_INCR": 3,
}

func (x SyncStage) Enum() *SyncStage {
	p := new(SyncStage)
	*p = x
	return p
}

func (x SyncStage) String() string {
	return proto.EnumName(SyncStage_name, int32(x))
}

func (x *SyncStage) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncStage_value, data, "SyncStage")
	if err != nil {
		return err
	}
	*x = SyncStage(value)
	return nil
}

func (SyncStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{3}
}

type ServeMode int32

const (
	// HOT_STANDBY = 1;
	ServeMode_PRIMARY_SECONDARY ServeMode = 2
	ServeMode_PEER_TO_PEER      ServeMode = 3
)

var ServeMode_name = map[int32]string{
	2: "PRIMARY_SECONDARY",
	3: "PEER_TO_PEER",
}

var ServeMode_value = map[string]int32{
	"PRIMARY_SECONDARY": 2,
	"PEER_TO_PEER":      3,
}

func (x ServeMode) Enum() *ServeMode {
	p := new(ServeMode)
	*p = x
	return p
}

func (x ServeMode) String() string {
	return proto.EnumName(ServeMode_name, int32(x))
}

func (x *ServeMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServeMode_value, data, "ServeMode")
	if err != nil {
		return err
	}
	*x = ServeMode(value)
	return nil
}

func (ServeMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{4}
}

type ResultCode int32

const (
	ResultCode_OK            ResultCode = 1
	ResultCode_INVALID_PARAM ResultCode = 2
	ResultCode_SERVER_ERROR  ResultCode = 3
)

var ResultCode_name = map[int32]string{
	1: "OK",
	2: "INVALID_PARAM",
	3: "SERVER_ERROR",
}

var ResultCode_value = map[string]int32{
	"OK":            1,
	"INVALID_PARAM": 2,
	"SERVER_ERROR":  3,
}

func (x ResultCode) Enum() *ResultCode {
	p := new(ResultCode)
	*p = x
	return p
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (x *ResultCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResultCode_value, data, "ResultCode")
	if err != nil {
		return err
	}
	*x = ResultCode(value)
	return nil
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{5}
}

type Response struct {
	RequestId            *string     `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Msg                  *string     `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Code                 *ResultCode `protobuf:"varint,3,req,name=code,enum=otsprotocol.ResultCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *Response) GetCode() ResultCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ResultCode_OK
}

type BaseTable struct {
	RegionId             *string  `protobuf:"bytes,1,req,name=regionId" json:"regionId,omitempty"`
	InstanceName         *string  `protobuf:"bytes,2,req,name=instanceName" json:"instanceName,omitempty"`
	TableName            *string  `protobuf:"bytes,3,req,name=tableName" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseTable) Reset()         { *m = BaseTable{} }
func (m *BaseTable) String() string { return proto.CompactTextString(m) }
func (*BaseTable) ProtoMessage()    {}
func (*BaseTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{1}
}

func (m *BaseTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseTable.Unmarshal(m, b)
}
func (m *BaseTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseTable.Marshal(b, m, deterministic)
}
func (m *BaseTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseTable.Merge(m, src)
}
func (m *BaseTable) XXX_Size() int {
	return xxx_messageInfo_BaseTable.Size(m)
}
func (m *BaseTable) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseTable.DiscardUnknown(m)
}

var xxx_messageInfo_BaseTable proto.InternalMessageInfo

func (m *BaseTable) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

func (m *BaseTable) GetInstanceName() string {
	if m != nil && m.InstanceName != nil {
		return *m.InstanceName
	}
	return ""
}

func (m *BaseTable) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type Placement struct {
	RegionId             *string  `protobuf:"bytes,1,req,name=regionId" json:"regionId,omitempty"`
	InstanceName         *string  `protobuf:"bytes,2,req,name=instanceName" json:"instanceName,omitempty"`
	Writable             *bool    `protobuf:"varint,3,req,name=writable,def=0" json:"writable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Placement) Reset()         { *m = Placement{} }
func (m *Placement) String() string { return proto.CompactTextString(m) }
func (*Placement) ProtoMessage()    {}
func (*Placement) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{2}
}

func (m *Placement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Placement.Unmarshal(m, b)
}
func (m *Placement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Placement.Marshal(b, m, deterministic)
}
func (m *Placement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Placement.Merge(m, src)
}
func (m *Placement) XXX_Size() int {
	return xxx_messageInfo_Placement.Size(m)
}
func (m *Placement) XXX_DiscardUnknown() {
	xxx_messageInfo_Placement.DiscardUnknown(m)
}

var xxx_messageInfo_Placement proto.InternalMessageInfo

const Default_Placement_Writable bool = false

func (m *Placement) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

func (m *Placement) GetInstanceName() string {
	if m != nil && m.InstanceName != nil {
		return *m.InstanceName
	}
	return ""
}

func (m *Placement) GetWritable() bool {
	if m != nil && m.Writable != nil {
		return *m.Writable
	}
	return Default_Placement_Writable
}

type Removal struct {
	RegionId             *string  `protobuf:"bytes,1,req,name=regionId" json:"regionId,omitempty"`
	InstanceName         *string  `protobuf:"bytes,2,req,name=instanceName" json:"instanceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Removal) Reset()         { *m = Removal{} }
func (m *Removal) String() string { return proto.CompactTextString(m) }
func (*Removal) ProtoMessage()    {}
func (*Removal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{3}
}

func (m *Removal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Removal.Unmarshal(m, b)
}
func (m *Removal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Removal.Marshal(b, m, deterministic)
}
func (m *Removal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Removal.Merge(m, src)
}
func (m *Removal) XXX_Size() int {
	return xxx_messageInfo_Removal.Size(m)
}
func (m *Removal) XXX_DiscardUnknown() {
	xxx_messageInfo_Removal.DiscardUnknown(m)
}

var xxx_messageInfo_Removal proto.InternalMessageInfo

func (m *Removal) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

func (m *Removal) GetInstanceName() string {
	if m != nil && m.InstanceName != nil {
		return *m.InstanceName
	}
	return ""
}

type CreateGlobalTableRequest struct {
	BaseTable            *BaseTable   `protobuf:"bytes,2,req,name=baseTable" json:"baseTable,omitempty"`
	Placements           []*Placement `protobuf:"bytes,3,rep,name=placements" json:"placements,omitempty"`
	SyncMode             *SyncMode    `protobuf:"varint,4,req,name=syncMode,enum=otsprotocol.SyncMode" json:"syncMode,omitempty"`
	ServeMode            *ServeMode   `protobuf:"varint,5,opt,name=serveMode,enum=otsprotocol.ServeMode" json:"serveMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateGlobalTableRequest) Reset()         { *m = CreateGlobalTableRequest{} }
func (m *CreateGlobalTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGlobalTableRequest) ProtoMessage()    {}
func (*CreateGlobalTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{4}
}

func (m *CreateGlobalTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGlobalTableRequest.Unmarshal(m, b)
}
func (m *CreateGlobalTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGlobalTableRequest.Marshal(b, m, deterministic)
}
func (m *CreateGlobalTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGlobalTableRequest.Merge(m, src)
}
func (m *CreateGlobalTableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGlobalTableRequest.Size(m)
}
func (m *CreateGlobalTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGlobalTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGlobalTableRequest proto.InternalMessageInfo

func (m *CreateGlobalTableRequest) GetBaseTable() *BaseTable {
	if m != nil {
		return m.BaseTable
	}
	return nil
}

func (m *CreateGlobalTableRequest) GetPlacements() []*Placement {
	if m != nil {
		return m.Placements
	}
	return nil
}

func (m *CreateGlobalTableRequest) GetSyncMode() SyncMode {
	if m != nil && m.SyncMode != nil {
		return *m.SyncMode
	}
	return SyncMode_SYNC_MODE_ROW
}

func (m *CreateGlobalTableRequest) GetServeMode() ServeMode {
	if m != nil && m.ServeMode != nil {
		return *m.ServeMode
	}
	return ServeMode_PRIMARY_SECONDARY
}

type CreateGlobalTableResponse struct {
	GlobalTableId        *string            `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	Status               *GlobalTableStatus `protobuf:"varint,3,req,name=status,enum=otsprotocol.GlobalTableStatus" json:"status,omitempty"`
	ServeMode            *ServeMode         `protobuf:"varint,4,opt,name=serveMode,enum=otsprotocol.ServeMode" json:"serveMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateGlobalTableResponse) Reset()         { *m = CreateGlobalTableResponse{} }
func (m *CreateGlobalTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGlobalTableResponse) ProtoMessage()    {}
func (*CreateGlobalTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{5}
}

func (m *CreateGlobalTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGlobalTableResponse.Unmarshal(m, b)
}
func (m *CreateGlobalTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGlobalTableResponse.Marshal(b, m, deterministic)
}
func (m *CreateGlobalTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGlobalTableResponse.Merge(m, src)
}
func (m *CreateGlobalTableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGlobalTableResponse.Size(m)
}
func (m *CreateGlobalTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGlobalTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGlobalTableResponse proto.InternalMessageInfo

func (m *CreateGlobalTableResponse) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *CreateGlobalTableResponse) GetStatus() GlobalTableStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GlobalTableStatus_G_INIT
}

func (m *CreateGlobalTableResponse) GetServeMode() ServeMode {
	if m != nil && m.ServeMode != nil {
		return *m.ServeMode
	}
	return ServeMode_PRIMARY_SECONDARY
}

type BindGlobalTableRequest struct {
	GlobalTableId        *string      `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	GlobalTableName      *string      `protobuf:"bytes,3,req,name=globalTableName" json:"globalTableName,omitempty"`
	Placements           []*Placement `protobuf:"bytes,4,rep,name=placements" json:"placements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BindGlobalTableRequest) Reset()         { *m = BindGlobalTableRequest{} }
func (m *BindGlobalTableRequest) String() string { return proto.CompactTextString(m) }
func (*BindGlobalTableRequest) ProtoMessage()    {}
func (*BindGlobalTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{6}
}

func (m *BindGlobalTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindGlobalTableRequest.Unmarshal(m, b)
}
func (m *BindGlobalTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindGlobalTableRequest.Marshal(b, m, deterministic)
}
func (m *BindGlobalTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindGlobalTableRequest.Merge(m, src)
}
func (m *BindGlobalTableRequest) XXX_Size() int {
	return xxx_messageInfo_BindGlobalTableRequest.Size(m)
}
func (m *BindGlobalTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindGlobalTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindGlobalTableRequest proto.InternalMessageInfo

func (m *BindGlobalTableRequest) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *BindGlobalTableRequest) GetGlobalTableName() string {
	if m != nil && m.GlobalTableName != nil {
		return *m.GlobalTableName
	}
	return ""
}

func (m *BindGlobalTableRequest) GetPlacements() []*Placement {
	if m != nil {
		return m.Placements
	}
	return nil
}

type BindGlobalTableResponse struct {
	GlobalTableId        *string            `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	Status               *GlobalTableStatus `protobuf:"varint,3,req,name=status,enum=otsprotocol.GlobalTableStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BindGlobalTableResponse) Reset()         { *m = BindGlobalTableResponse{} }
func (m *BindGlobalTableResponse) String() string { return proto.CompactTextString(m) }
func (*BindGlobalTableResponse) ProtoMessage()    {}
func (*BindGlobalTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{7}
}

func (m *BindGlobalTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindGlobalTableResponse.Unmarshal(m, b)
}
func (m *BindGlobalTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindGlobalTableResponse.Marshal(b, m, deterministic)
}
func (m *BindGlobalTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindGlobalTableResponse.Merge(m, src)
}
func (m *BindGlobalTableResponse) XXX_Size() int {
	return xxx_messageInfo_BindGlobalTableResponse.Size(m)
}
func (m *BindGlobalTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindGlobalTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindGlobalTableResponse proto.InternalMessageInfo

func (m *BindGlobalTableResponse) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *BindGlobalTableResponse) GetStatus() GlobalTableStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GlobalTableStatus_G_INIT
}

type UnbindGlobalTableRequest struct {
	GlobalTableId        *string    `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	GlobalTableName      *string    `protobuf:"bytes,3,req,name=globalTableName" json:"globalTableName,omitempty"`
	Removals             []*Removal `protobuf:"bytes,4,rep,name=removals" json:"removals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnbindGlobalTableRequest) Reset()         { *m = UnbindGlobalTableRequest{} }
func (m *UnbindGlobalTableRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindGlobalTableRequest) ProtoMessage()    {}
func (*UnbindGlobalTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{8}
}

func (m *UnbindGlobalTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindGlobalTableRequest.Unmarshal(m, b)
}
func (m *UnbindGlobalTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindGlobalTableRequest.Marshal(b, m, deterministic)
}
func (m *UnbindGlobalTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindGlobalTableRequest.Merge(m, src)
}
func (m *UnbindGlobalTableRequest) XXX_Size() int {
	return xxx_messageInfo_UnbindGlobalTableRequest.Size(m)
}
func (m *UnbindGlobalTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindGlobalTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindGlobalTableRequest proto.InternalMessageInfo

func (m *UnbindGlobalTableRequest) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *UnbindGlobalTableRequest) GetGlobalTableName() string {
	if m != nil && m.GlobalTableName != nil {
		return *m.GlobalTableName
	}
	return ""
}

func (m *UnbindGlobalTableRequest) GetRemovals() []*Removal {
	if m != nil {
		return m.Removals
	}
	return nil
}

type UnbindGlobalTableResponse struct {
	GlobalTableId        *string            `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	Status               *GlobalTableStatus `protobuf:"varint,3,req,name=status,enum=otsprotocol.GlobalTableStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UnbindGlobalTableResponse) Reset()         { *m = UnbindGlobalTableResponse{} }
func (m *UnbindGlobalTableResponse) String() string { return proto.CompactTextString(m) }
func (*UnbindGlobalTableResponse) ProtoMessage()    {}
func (*UnbindGlobalTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{9}
}

func (m *UnbindGlobalTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindGlobalTableResponse.Unmarshal(m, b)
}
func (m *UnbindGlobalTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindGlobalTableResponse.Marshal(b, m, deterministic)
}
func (m *UnbindGlobalTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindGlobalTableResponse.Merge(m, src)
}
func (m *UnbindGlobalTableResponse) XXX_Size() int {
	return xxx_messageInfo_UnbindGlobalTableResponse.Size(m)
}
func (m *UnbindGlobalTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindGlobalTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindGlobalTableResponse proto.InternalMessageInfo

func (m *UnbindGlobalTableResponse) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *UnbindGlobalTableResponse) GetStatus() GlobalTableStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GlobalTableStatus_G_INIT
}

type DescribeGlobalTableRequest struct {
	GlobalTableId        *string   `protobuf:"bytes,1,opt,name=globalTableId" json:"globalTableId,omitempty"`
	GlobalTableName      *string   `protobuf:"bytes,2,req,name=globalTableName" json:"globalTableName,omitempty"`
	PhyTable             *PhyTable `protobuf:"bytes,3,opt,name=phyTable" json:"phyTable,omitempty"`
	ReturnRpo            *bool     `protobuf:"varint,4,opt,name=returnRpo" json:"returnRpo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DescribeGlobalTableRequest) Reset()         { *m = DescribeGlobalTableRequest{} }
func (m *DescribeGlobalTableRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeGlobalTableRequest) ProtoMessage()    {}
func (*DescribeGlobalTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{10}
}

func (m *DescribeGlobalTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeGlobalTableRequest.Unmarshal(m, b)
}
func (m *DescribeGlobalTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeGlobalTableRequest.Marshal(b, m, deterministic)
}
func (m *DescribeGlobalTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeGlobalTableRequest.Merge(m, src)
}
func (m *DescribeGlobalTableRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeGlobalTableRequest.Size(m)
}
func (m *DescribeGlobalTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeGlobalTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeGlobalTableRequest proto.InternalMessageInfo

func (m *DescribeGlobalTableRequest) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *DescribeGlobalTableRequest) GetGlobalTableName() string {
	if m != nil && m.GlobalTableName != nil {
		return *m.GlobalTableName
	}
	return ""
}

func (m *DescribeGlobalTableRequest) GetPhyTable() *PhyTable {
	if m != nil {
		return m.PhyTable
	}
	return nil
}

func (m *DescribeGlobalTableRequest) GetReturnRpo() bool {
	if m != nil && m.ReturnRpo != nil {
		return *m.ReturnRpo
	}
	return false
}

type DescribeGlobalTableResponse struct {
	GlobalTableId        *string            `protobuf:"bytes,2,req,name=globalTableId" json:"globalTableId,omitempty"`
	Status               *GlobalTableStatus `protobuf:"varint,3,req,name=status,enum=otsprotocol.GlobalTableStatus" json:"status,omitempty"`
	PhyTables            []*PhyTable        `protobuf:"bytes,4,rep,name=phyTables" json:"phyTables,omitempty"`
	ServeMode            *ServeMode         `protobuf:"varint,5,opt,name=serveMode,enum=otsprotocol.ServeMode" json:"serveMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DescribeGlobalTableResponse) Reset()         { *m = DescribeGlobalTableResponse{} }
func (m *DescribeGlobalTableResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeGlobalTableResponse) ProtoMessage()    {}
func (*DescribeGlobalTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{11}
}

func (m *DescribeGlobalTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeGlobalTableResponse.Unmarshal(m, b)
}
func (m *DescribeGlobalTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeGlobalTableResponse.Marshal(b, m, deterministic)
}
func (m *DescribeGlobalTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeGlobalTableResponse.Merge(m, src)
}
func (m *DescribeGlobalTableResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeGlobalTableResponse.Size(m)
}
func (m *DescribeGlobalTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeGlobalTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeGlobalTableResponse proto.InternalMessageInfo

func (m *DescribeGlobalTableResponse) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *DescribeGlobalTableResponse) GetStatus() GlobalTableStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GlobalTableStatus_G_INIT
}

func (m *DescribeGlobalTableResponse) GetPhyTables() []*PhyTable {
	if m != nil {
		return m.PhyTables
	}
	return nil
}

func (m *DescribeGlobalTableResponse) GetServeMode() ServeMode {
	if m != nil && m.ServeMode != nil {
		return *m.ServeMode
	}
	return ServeMode_PRIMARY_SECONDARY
}

type PhyTable struct {
	RegionId        *string         `protobuf:"bytes,1,req,name=regionId" json:"regionId,omitempty"`
	InstanceName    *string         `protobuf:"bytes,2,req,name=instanceName" json:"instanceName,omitempty"`
	TableName       *string         `protobuf:"bytes,3,req,name=tableName" json:"tableName,omitempty"`
	Writable        *bool           `protobuf:"varint,4,req,name=writable" json:"writable,omitempty"`
	Status          *PhyTableStatus `protobuf:"varint,5,opt,name=status,enum=otsprotocol.PhyTableStatus" json:"status,omitempty"`
	StatusTimestamp *int64          `protobuf:"varint,6,opt,name=statusTimestamp" json:"statusTimestamp,omitempty"`
	TableId         *string         `protobuf:"bytes,7,opt,name=tableId" json:"tableId,omitempty"`
	// optional int32 tableHashKey = 8;
	// optional string endpoint = 9;
	Stage *SyncStage `protobuf:"varint,10,opt,name=stage,enum=otsprotocol.SyncStage" json:"stage,omitempty"`
	// optional int64 metaVersion = 11;
	IsFailed             *bool    `protobuf:"varint,12,opt,name=isFailed" json:"isFailed,omitempty"`
	Message              *string  `protobuf:"bytes,13,opt,name=message" json:"message,omitempty"`
	Role                 *string  `protobuf:"bytes,14,opt,name=role" json:"role,omitempty"`
	RpoNanos             *int64   `protobuf:"varint,15,opt,name=rpoNanos" json:"rpoNanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhyTable) Reset()         { *m = PhyTable{} }
func (m *PhyTable) String() string { return proto.CompactTextString(m) }
func (*PhyTable) ProtoMessage()    {}
func (*PhyTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{12}
}

func (m *PhyTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhyTable.Unmarshal(m, b)
}
func (m *PhyTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhyTable.Marshal(b, m, deterministic)
}
func (m *PhyTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhyTable.Merge(m, src)
}
func (m *PhyTable) XXX_Size() int {
	return xxx_messageInfo_PhyTable.Size(m)
}
func (m *PhyTable) XXX_DiscardUnknown() {
	xxx_messageInfo_PhyTable.DiscardUnknown(m)
}

var xxx_messageInfo_PhyTable proto.InternalMessageInfo

func (m *PhyTable) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

func (m *PhyTable) GetInstanceName() string {
	if m != nil && m.InstanceName != nil {
		return *m.InstanceName
	}
	return ""
}

func (m *PhyTable) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *PhyTable) GetWritable() bool {
	if m != nil && m.Writable != nil {
		return *m.Writable
	}
	return false
}

func (m *PhyTable) GetStatus() PhyTableStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PhyTableStatus_PHY_PENDING
}

func (m *PhyTable) GetStatusTimestamp() int64 {
	if m != nil && m.StatusTimestamp != nil {
		return *m.StatusTimestamp
	}
	return 0
}

func (m *PhyTable) GetTableId() string {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return ""
}

func (m *PhyTable) GetStage() SyncStage {
	if m != nil && m.Stage != nil {
		return *m.Stage
	}
	return SyncStage_SYNC_INIT
}

func (m *PhyTable) GetIsFailed() bool {
	if m != nil && m.IsFailed != nil {
		return *m.IsFailed
	}
	return false
}

func (m *PhyTable) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *PhyTable) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *PhyTable) GetRpoNanos() int64 {
	if m != nil && m.RpoNanos != nil {
		return *m.RpoNanos
	}
	return 0
}

type UpdateGlobalTableRequest struct {
	GlobalTableId        *string         `protobuf:"bytes,1,req,name=globalTableId" json:"globalTableId,omitempty"`
	GlobalTableName      *string         `protobuf:"bytes,2,req,name=globalTableName" json:"globalTableName,omitempty"`
	PhyTable             *UpdatePhyTable `protobuf:"bytes,3,opt,name=phyTable" json:"phyTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateGlobalTableRequest) Reset()         { *m = UpdateGlobalTableRequest{} }
func (m *UpdateGlobalTableRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGlobalTableRequest) ProtoMessage()    {}
func (*UpdateGlobalTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{13}
}

func (m *UpdateGlobalTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGlobalTableRequest.Unmarshal(m, b)
}
func (m *UpdateGlobalTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGlobalTableRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGlobalTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGlobalTableRequest.Merge(m, src)
}
func (m *UpdateGlobalTableRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGlobalTableRequest.Size(m)
}
func (m *UpdateGlobalTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGlobalTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGlobalTableRequest proto.InternalMessageInfo

func (m *UpdateGlobalTableRequest) GetGlobalTableId() string {
	if m != nil && m.GlobalTableId != nil {
		return *m.GlobalTableId
	}
	return ""
}

func (m *UpdateGlobalTableRequest) GetGlobalTableName() string {
	if m != nil && m.GlobalTableName != nil {
		return *m.GlobalTableName
	}
	return ""
}

func (m *UpdateGlobalTableRequest) GetPhyTable() *UpdatePhyTable {
	if m != nil {
		return m.PhyTable
	}
	return nil
}

type UpdatePhyTable struct {
	RegionId     *string `protobuf:"bytes,1,req,name=regionId" json:"regionId,omitempty"`
	InstanceName *string `protobuf:"bytes,2,req,name=instanceName" json:"instanceName,omitempty"`
	TableName    *string `protobuf:"bytes,3,req,name=tableName" json:"tableName,omitempty"`
	Writable     *bool   `protobuf:"varint,4,opt,name=writable" json:"writable,omitempty"`
	// set phy table is eligible for primary, only need at PRIMARY_SECONDARY serve mode
	PrimaryEligible      *bool    `protobuf:"varint,5,opt,name=primaryEligible" json:"primaryEligible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePhyTable) Reset()         { *m = UpdatePhyTable{} }
func (m *UpdatePhyTable) String() string { return proto.CompactTextString(m) }
func (*UpdatePhyTable) ProtoMessage()    {}
func (*UpdatePhyTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{14}
}

func (m *UpdatePhyTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhyTable.Unmarshal(m, b)
}
func (m *UpdatePhyTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhyTable.Marshal(b, m, deterministic)
}
func (m *UpdatePhyTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhyTable.Merge(m, src)
}
func (m *UpdatePhyTable) XXX_Size() int {
	return xxx_messageInfo_UpdatePhyTable.Size(m)
}
func (m *UpdatePhyTable) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhyTable.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhyTable proto.InternalMessageInfo

func (m *UpdatePhyTable) GetRegionId() string {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return ""
}

func (m *UpdatePhyTable) GetInstanceName() string {
	if m != nil && m.InstanceName != nil {
		return *m.InstanceName
	}
	return ""
}

func (m *UpdatePhyTable) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdatePhyTable) GetWritable() bool {
	if m != nil && m.Writable != nil {
		return *m.Writable
	}
	return false
}

func (m *UpdatePhyTable) GetPrimaryEligible() bool {
	if m != nil && m.PrimaryEligible != nil {
		return *m.PrimaryEligible
	}
	return false
}

type UpdateGlobalTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGlobalTableResponse) Reset()         { *m = UpdateGlobalTableResponse{} }
func (m *UpdateGlobalTableResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGlobalTableResponse) ProtoMessage()    {}
func (*UpdateGlobalTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c4a0e119268392, []int{15}
}

func (m *UpdateGlobalTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGlobalTableResponse.Unmarshal(m, b)
}
func (m *UpdateGlobalTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGlobalTableResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGlobalTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGlobalTableResponse.Merge(m, src)
}
func (m *UpdateGlobalTableResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGlobalTableResponse.Size(m)
}
func (m *UpdateGlobalTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGlobalTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGlobalTableResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("otsprotocol.SyncMode", SyncMode_name, SyncMode_value)
	proto.RegisterEnum("otsprotocol.GlobalTableStatus", GlobalTableStatus_name, GlobalTableStatus_value)
	proto.RegisterEnum("otsprotocol.PhyTableStatus", PhyTableStatus_name, PhyTableStatus_value)
	proto.RegisterEnum("otsprotocol.SyncStage", SyncStage_name, SyncStage_value)
	proto.RegisterEnum("otsprotocol.ServeMode", ServeMode_name, ServeMode_value)
	proto.RegisterEnum("otsprotocol.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterType((*Response)(nil), "otsprotocol.Response")
	proto.RegisterType((*BaseTable)(nil), "otsprotocol.BaseTable")
	proto.RegisterType((*Placement)(nil), "otsprotocol.Placement")
	proto.RegisterType((*Removal)(nil), "otsprotocol.Removal")
	proto.RegisterType((*CreateGlobalTableRequest)(nil), "otsprotocol.CreateGlobalTableRequest")
	proto.RegisterType((*CreateGlobalTableResponse)(nil), "otsprotocol.CreateGlobalTableResponse")
	proto.RegisterType((*BindGlobalTableRequest)(nil), "otsprotocol.BindGlobalTableRequest")
	proto.RegisterType((*BindGlobalTableResponse)(nil), "otsprotocol.BindGlobalTableResponse")
	proto.RegisterType((*UnbindGlobalTableRequest)(nil), "otsprotocol.UnbindGlobalTableRequest")
	proto.RegisterType((*UnbindGlobalTableResponse)(nil), "otsprotocol.UnbindGlobalTableResponse")
	proto.RegisterType((*DescribeGlobalTableRequest)(nil), "otsprotocol.DescribeGlobalTableRequest")
	proto.RegisterType((*DescribeGlobalTableResponse)(nil), "otsprotocol.DescribeGlobalTableResponse")
	proto.RegisterType((*PhyTable)(nil), "otsprotocol.PhyTable")
	proto.RegisterType((*UpdateGlobalTableRequest)(nil), "otsprotocol.UpdateGlobalTableRequest")
	proto.RegisterType((*UpdatePhyTable)(nil), "otsprotocol.UpdatePhyTable")
	proto.RegisterType((*UpdateGlobalTableResponse)(nil), "otsprotocol.UpdateGlobalTableResponse")
}

func init() { proto.RegisterFile("global_table.proto", fileDescriptor_c5c4a0e119268392) }

var fileDescriptor_c5c4a0e119268392 = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0xea, 0x46,
	0x17, 0x96, 0x6d, 0x92, 0xd8, 0x27, 0x09, 0x38, 0xa3, 0xfb, 0xe1, 0xdc, 0xbc, 0x6f, 0x45, 0xad,
	0x2e, 0x10, 0xad, 0xa2, 0xde, 0x9b, 0xab, 0xdb, 0x0f, 0x75, 0x43, 0xc0, 0xa1, 0x56, 0x83, 0x41,
	0x03, 0xa4, 0x62, 0x65, 0x19, 0x98, 0x72, 0x2d, 0x19, 0x9b, 0x7a, 0x9c, 0x7b, 0xc5, 0xbe, 0x7f,
	0xa0, 0xfb, 0x2e, 0x2a, 0xf5, 0x07, 0x74, 0xd3, 0x6d, 0xff, 0x4e, 0xf7, 0xfd, 0x07, 0xd5, 0x8c,
	0xbf, 0x30, 0xb8, 0x6a, 0xd4, 0xa8, 0xac, 0xf0, 0x79, 0xe6, 0xcc, 0x39, 0xcf, 0x3c, 0xe7, 0x9c,
	0x19, 0x00, 0x2d, 0xbc, 0x60, 0xea, 0x78, 0x76, 0xe4, 0x4c, 0x3d, 0x72, 0xb9, 0x0a, 0x83, 0x28,
	0x40, 0xc7, 0x41, 0x44, 0xf9, 0xd7, 0x2c, 0xf0, 0xf4, 0xb7, 0x20, 0x63, 0x42, 0x57, 0x81, 0x4f,
	0x09, 0xfa, 0x3f, 0x40, 0x48, 0xbe, 0xbf, 0x27, 0x34, 0xb2, 0xdd, 0xb9, 0x26, 0xd4, 0x85, 0x86,
	0x82, 0x95, 0x04, 0x31, 0xe7, 0x48, 0x05, 0x69, 0x49, 0x17, 0x9a, 0xc8, 0x71, 0xf6, 0x89, 0x3e,
	0x86, 0xca, 0x2c, 0x98, 0x13, 0x4d, 0xaa, 0x8b, 0x8d, 0xea, 0xab, 0xe7, 0x97, 0x1b, 0x81, 0x2f,
	0x31, 0xa1, 0xf7, 0x5e, 0xd4, 0x0e, 0xe6, 0x04, 0x73, 0x27, 0xdd, 0x05, 0xe5, 0xda, 0xa1, 0x64,
	0xc4, 0x98, 0xa0, 0x17, 0x20, 0x87, 0x64, 0xe1, 0x06, 0xbe, 0xc9, 0x12, 0x89, 0x0d, 0x05, 0x67,
	0x36, 0xd2, 0xe1, 0xc4, 0xf5, 0x69, 0xe4, 0xf8, 0x33, 0x62, 0x39, 0x4b, 0xa2, 0x89, 0x7c, 0xbd,
	0x80, 0xa1, 0xff, 0x81, 0xc2, 0x8f, 0xc4, 0x1d, 0x24, 0xee, 0x90, 0x03, 0xba, 0x0f, 0xca, 0xc0,
	0x73, 0x66, 0x64, 0x49, 0xfc, 0xe8, 0xd1, 0xa9, 0x3e, 0x04, 0xf9, 0x7d, 0xe8, 0xf2, 0xe0, 0x3c,
	0x93, 0xfc, 0xe5, 0xc1, 0x77, 0x8e, 0x47, 0x09, 0xce, 0x60, 0xdd, 0x84, 0x23, 0x4c, 0x96, 0xc1,
	0x3b, 0xc7, 0x7b, 0x6c, 0x36, 0xfd, 0x4f, 0x01, 0xb4, 0x76, 0x48, 0x9c, 0x88, 0x74, 0x79, 0xe5,
	0xb8, 0x5c, 0x38, 0xae, 0x01, 0x7a, 0x0d, 0xca, 0x34, 0x95, 0x90, 0xef, 0x3e, 0x7e, 0xf5, 0xac,
	0x20, 0x7a, 0x26, 0x30, 0xce, 0x1d, 0xd1, 0x1b, 0x80, 0x55, 0xaa, 0x06, 0xd5, 0xa4, 0xba, 0xb4,
	0xb3, 0x2d, 0x13, 0x0b, 0x6f, 0x78, 0xa2, 0x97, 0x20, 0xd3, 0xb5, 0x3f, 0xeb, 0xb1, 0x0a, 0x57,
	0x78, 0x85, 0x9f, 0x16, 0x76, 0x0d, 0x93, 0x45, 0x9c, 0xb9, 0x31, 0x82, 0x94, 0x84, 0xef, 0x08,
	0xdf, 0x73, 0x50, 0x17, 0x1a, 0xd5, 0xad, 0x4c, 0xc3, 0x74, 0x15, 0xe7, 0x8e, 0xfa, 0xaf, 0x02,
	0x9c, 0x97, 0x9c, 0x39, 0xe9, 0xca, 0x8f, 0xe0, 0x74, 0x91, 0xc3, 0xe6, 0x3c, 0x91, 0xad, 0x08,
	0xa2, 0x37, 0x70, 0x48, 0x23, 0x27, 0xba, 0xa7, 0x49, 0x33, 0x7e, 0x50, 0x48, 0xbb, 0x11, 0x77,
	0xc8, 0xbd, 0x70, 0xe2, 0x5d, 0x64, 0x5c, 0x79, 0x28, 0xe3, 0x9f, 0x05, 0x78, 0x76, 0xed, 0xfa,
	0xf3, 0x92, 0x1a, 0x3d, 0x8c, 0x6e, 0x03, 0x6a, 0x1b, 0xc0, 0x46, 0x17, 0x6f, 0xc3, 0x5b, 0xd5,
	0xab, 0x3c, 0xb4, 0x7a, 0xfa, 0x7b, 0x78, 0xbe, 0xc3, 0x70, 0x1f, 0x8a, 0xea, 0x3f, 0x09, 0xa0,
	0x8d, 0xfd, 0xe9, 0x7e, 0xd4, 0xf9, 0x94, 0x8d, 0x1b, 0x9f, 0xbc, 0x54, 0x9b, 0x27, 0x5b, 0xb7,
	0x10, 0x5f, 0xc4, 0x99, 0x97, 0xbe, 0x86, 0xf3, 0x12, 0x76, 0x7b, 0x51, 0xe6, 0x77, 0x01, 0x5e,
	0x74, 0x08, 0x9d, 0x85, 0xee, 0x94, 0x3c, 0x44, 0x9b, 0xf8, 0x06, 0xfe, 0x67, 0x6d, 0xc4, 0x72,
	0x6d, 0x5e, 0x82, 0xbc, 0x7a, 0xbb, 0x1e, 0x25, 0x17, 0x97, 0xd0, 0x38, 0xde, 0x9a, 0xdf, 0x41,
	0xb2, 0x88, 0x33, 0x37, 0x76, 0xad, 0x86, 0x24, 0xba, 0x0f, 0x7d, 0xbc, 0x0a, 0xf8, 0x34, 0xc8,
	0x38, 0x07, 0xf4, 0x3f, 0x04, 0xb8, 0x28, 0xe5, 0xbf, 0x97, 0x49, 0xbd, 0x02, 0x25, 0xe5, 0x99,
	0xd6, 0xfa, 0x6f, 0xce, 0x93, 0xfb, 0xfd, 0xcb, 0x0b, 0xe9, 0x47, 0x09, 0xe4, 0x34, 0xda, 0x7f,
	0xfb, 0x54, 0xb1, 0xe8, 0xd9, 0xeb, 0xc2, 0x2e, 0x59, 0x39, 0x7f, 0x56, 0xd0, 0x55, 0xa6, 0x54,
	0xcc, 0xfc, 0xa2, 0xf4, 0xb8, 0x5b, 0x32, 0x35, 0xa0, 0x16, 0x7f, 0x8d, 0xdc, 0x25, 0xa1, 0x91,
	0xb3, 0x5c, 0x69, 0x87, 0x75, 0xa1, 0x21, 0xe1, 0x6d, 0x18, 0x69, 0x70, 0x14, 0x25, 0x85, 0x3a,
	0xe2, 0x9d, 0x96, 0x9a, 0xe8, 0x13, 0x38, 0xa0, 0x91, 0xb3, 0x20, 0x1a, 0x94, 0x29, 0xb6, 0xf6,
	0x67, 0x43, 0xb6, 0x8a, 0x63, 0x27, 0x76, 0x04, 0x97, 0xde, 0x38, 0xae, 0x47, 0xe6, 0xda, 0x09,
	0xef, 0x99, 0xcc, 0x66, 0x39, 0x96, 0x84, 0x52, 0x16, 0xeb, 0x34, 0xce, 0x91, 0x98, 0x08, 0x41,
	0x25, 0x0c, 0x3c, 0xa2, 0x55, 0x39, 0xcc, 0xbf, 0xb9, 0xd4, 0xab, 0xc0, 0x72, 0xfc, 0x80, 0x6a,
	0x35, 0x4e, 0x3a, 0xb3, 0xf5, 0x5f, 0xd8, 0xb5, 0xb2, 0x9a, 0x97, 0x3f, 0x8c, 0x25, 0xa3, 0x23,
	0x3e, 0x66, 0x74, 0x3e, 0xdb, 0x19, 0x9d, 0xa2, 0xf6, 0x31, 0x91, 0xdd, 0x01, 0xd2, 0x7f, 0x13,
	0xa0, 0x5a, 0x5c, 0xdc, 0x6b, 0xff, 0x08, 0x85, 0xfe, 0x69, 0x40, 0x6d, 0x15, 0xba, 0x4b, 0x27,
	0x5c, 0x1b, 0x9e, 0xbb, 0x70, 0x99, 0xcb, 0x01, 0x77, 0xd9, 0x86, 0xf5, 0x0b, 0x38, 0x2f, 0xd1,
	0x36, 0x1e, 0xeb, 0xe6, 0x15, 0xc8, 0xe9, 0x53, 0x8f, 0xce, 0xe0, 0x74, 0x38, 0xb1, 0xda, 0x76,
	0xaf, 0xdf, 0x31, 0x6c, 0xdc, 0xff, 0x56, 0x15, 0xd0, 0x13, 0x50, 0x73, 0xa8, 0xdd, 0xbf, 0x1d,
	0xf7, 0x2c, 0x55, 0x6c, 0x7e, 0x05, 0x67, 0x3b, 0xa3, 0x8c, 0x00, 0x0e, 0xbb, 0xb6, 0x69, 0x99,
	0x23, 0x55, 0x40, 0xa7, 0xa0, 0x74, 0x6d, 0xcc, 0x76, 0x58, 0x37, 0xaa, 0x88, 0x4e, 0x40, 0xee,
	0xda, 0xad, 0xf6, 0xc8, 0xbc, 0x33, 0x54, 0xa9, 0xf9, 0x83, 0x00, 0xd5, 0x62, 0x7f, 0xa3, 0x1a,
	0x1c, 0x0f, 0xbe, 0x9e, 0xd8, 0x03, 0xc3, 0xea, 0x98, 0x56, 0x57, 0x15, 0xd8, 0x0e, 0x06, 0xf0,
	0x70, 0x22, 0x52, 0xe1, 0x84, 0x59, 0x8c, 0x49, 0xa7, 0x35, 0x6a, 0xa9, 0x12, 0x4b, 0xc0, 0x10,
	0x6c, 0xb4, 0x3a, 0x13, 0xb5, 0x82, 0xaa, 0x00, 0xcc, 0x4c, 0x52, 0x1c, 0xb0, 0x93, 0x30, 0x7b,
	0x6c, 0x5d, 0x9b, 0x71, 0xc4, 0xc3, 0x34, 0xc5, 0xd8, 0xba, 0xee, 0x8f, 0xad, 0x8e, 0x7a, 0xd4,
	0xfc, 0x1c, 0x94, 0xac, 0xdb, 0x59, 0x3c, 0x7e, 0xce, 0x9c, 0x3f, 0x37, 0x6f, 0xc6, 0xb7, 0xb7,
	0xaa, 0xb8, 0xb1, 0xda, 0xc6, 0xaa, 0xd4, 0x7c, 0x0d, 0x4a, 0x76, 0xb3, 0xa0, 0xa7, 0x70, 0x36,
	0xc0, 0x66, 0xaf, 0x85, 0x27, 0xf6, 0xd0, 0x68, 0xf7, 0xad, 0x4e, 0x0b, 0x4f, 0x12, 0xca, 0x86,
	0x81, 0xed, 0x51, 0xdf, 0x66, 0xbf, 0xaa, 0xd4, 0xfc, 0x02, 0x20, 0xff, 0xdb, 0x8c, 0x0e, 0x41,
	0xec, 0x7f, 0xa3, 0x0a, 0x8c, 0xa9, 0x69, 0xdd, 0xb5, 0x6e, 0xcd, 0x8e, 0x3d, 0x68, 0xe1, 0x56,
	0x2f, 0xde, 0x3a, 0x34, 0xf0, 0x9d, 0x81, 0x6d, 0x03, 0xe3, 0x3e, 0x56, 0xa5, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x21, 0xa1, 0x46, 0xe9, 0x0b, 0x00, 0x00,
}
