syntax = "proto2";

package otsprotocol;

message Error {
    required string code = 1;
    optional string message = 2;
}

enum PrimaryKeyType {
    INTEGER = 1;
    STRING = 2;
    BINARY = 3;
}

enum PrimaryKeyOption {
    AUTO_INCREMENT = 1;
}

enum DataBlockType {
    DBT_PLAIN_BUFFER = 0;
    DBT_SIMPLE_ROW_MATRIX = 1;
}

enum CompressType {
    CPT_NONE = 0;
}

message PrimaryKeySchema {
    required string name = 1;
    required PrimaryKeyType type = 2;
    optional PrimaryKeyOption option = 3;
}

message PartitionRange {
    required bytes begin = 1; // encoded as SQLVariant
    required bytes end = 2; // encoded as SQLVariant
}

enum BloomFilterType {
    NONE = 1;
    CELL = 2;
    ROW = 3;
}

message TableOptions {
    optional int32 time_to_live = 1; // Can be dynamically changed
    optional int32 max_versions = 2; // Can be dynamically changed
    optional BloomFilterType bloom_filter_type = 3; // Can be dynamically changed
    optional int32 block_size = 4; // Can be dynamically changed
    optional int64 deviation_cell_version_in_sec = 5; // Can be dynamically modified
    optional bool allow_update = 6;
    optional bool update_full_row = 7; // Cannot be dynamically modified
}

message TableMeta {
    required string table_name = 1;
    repeated PrimaryKeySchema primary_key = 2;
    repeated DefinedColumnSchema defined_column = 3;
    repeated IndexMeta index_meta = 4;
}

/**
 * Table status changes only correspond to user operations; internal machine failovers or other conditions do not result in table status changes.
 * There are three considerations:
 *     One, in general scenarios, users will only check the table's status after performing a modification operation on the table;
 *     Two, there is a delay between the time when an internal machine failover causes access anomalies and when the user can see the table's status change. It is impossible to fully match the table's unserviceable state with the state the user observes.
 *     Three, after an internal machine failover, it should not be considered as a change in the entire table's state but rather as a state change of a partition. The corresponding table state would be PARTIAL_FAILOVER. However, the granularity of this "partial" cannot be clearly represented, which might confuse users even more.
 */
enum TableStatus {
    ACTIVE = 1; // The table is in a servable state.
    INACTIVE = 2; // The user disables the table through UnloadTable.
    LOADING = 3; // The table is being created, and the partition has not been fully loaded yet; or the table has just been enabled from the INACTIVE state.
    UNLOADING = 4; // The table is being deleted (during the period from delete table to partition completely unloaded) or the table is unloaded from ACTIVE status.
    UPDATING = 5; // The table is being updated (table property changes, reserved throughput changes).
}

enum RowExistenceExpectation {
    IGNORE = 0;
    EXPECT_EXIST = 1;
    EXPECT_NOT_EXIST = 2;
}

message Condition {
    required RowExistenceExpectation row_existence = 1;
    optional bytes column_condition      = 2;
}

message CapacityUnit {
    optional int32 read = 1;
    optional int32 write = 2;
}

message ReservedThroughputDetails {
    required CapacityUnit capacity_unit = 1; // The reserved throughput value of the table.
    required int64 last_increase_time = 2; // The time of the last increase in reserved throughput.
    optional int64 last_decrease_time = 3; // The time of the last reduction in reserved throughput.
}

message ReservedThroughput {
    required CapacityUnit capacity_unit = 1;
}

message ConsumedCapacity {
    required CapacityUnit capacity_unit = 1;
}

message StreamSpecification {
    required bool enable_stream = 1;
    optional int32 expiration_time = 2;
    repeated string columns_to_get = 3;
}

message StreamDetails {
    required bool enable_stream = 1;
    optional string stream_id = 2;
    optional int32 expiration_time = 3;
    optional int64 last_enable_time = 4;
    repeated string columns_to_get = 5;
}

enum SSEKeyType {
    SSE_KMS_SERVICE = 1;
    SSE_BYOK = 2;
}

message SSESpecification {
    required bool enable = 1;
    optional SSEKeyType key_type = 2;
    optional bytes key_id = 3; // only useful when key_type is SSE_BYOK
    optional bytes role_arn = 4; // only useful when key_type is SSE_BYOK
}

message SSEDetails {
    required bool enable = 1;
    optional SSEKeyType key_type = 2;
    optional bytes key_id = 3;
    optional bytes role_arn = 4; // only useful when key_type is SSE_BYOK
}

/* #############################################  CreateTable  ############################################# */
/**
 * table_meta is used to store the non-modifiable schema properties of a table. The modifiable ReservedThroughput and TableOptions are separated out as parameters for UpdateTable.
 * After adding GlobalIndex and LocalIndex, the structure will become:
 * message CreateTableRequest {
 *         required TableMeta table_meta = 1;
 *         required ReservedThroughput reserved_throughput = 2;
 *         required TableOptions table_options = 3;
 *         repeated LocalIndex local_indexes = 4; // LocalIndex no longer separately includes ReservedThroughput and TableOptions; it shares configurations with the main table.
 *         repeated GlobalIndex global_indexes = 5; // GlobalIndex separately includes ReservedThroughput and TableOptions
 * }
 */
message CreateTableRequest {
    required TableMeta table_meta = 1;
    required ReservedThroughput reserved_throughput = 2; // Not placed in TableOptions because UpdateTableResponse returns ReservedThroughputDetails, and TableOptions does not have a similar return structure.
    optional TableOptions table_options = 3;
    repeated PartitionRange partitions = 4;
    optional StreamSpecification stream_spec = 5;
    optional SSESpecification sse_spec = 6;
    repeated IndexMeta index_metas = 7;
    optional bool enable_local_txn = 8;
}

message CreateTableResponse {
}

/* ######################################################################################################### */


/* #############################################  UpdateTable  ############################################# */
message UpdateTableRequest {
    required string table_name = 1;
    optional ReservedThroughput reserved_throughput = 2;
    optional TableOptions table_options = 3;
    optional StreamSpecification stream_spec = 4;
}

message UpdateTableResponse {
    required ReservedThroughputDetails reserved_throughput_details = 1;
    required TableOptions table_options = 2;
    optional StreamDetails stream_details = 3;
}
/* ######################################################################################################### */

/* #############################################  DescribeTable  ############################################# */
message DescribeTableRequest {
    required string table_name = 1;
}

message DescribeTableResponse {
    required TableMeta table_meta = 1;
    required ReservedThroughputDetails reserved_throughput_details = 2;
    required TableOptions table_options = 3;
    required TableStatus table_status = 4;
    optional StreamDetails stream_details = 5;
    repeated bytes shard_splits = 6;
    optional SSEDetails sse_details = 7;
    repeated IndexMeta index_metas = 8;
    optional DescribeTableInnerInfo inner_info = 12;
}
/* ########################################################################################################### */

/* #############################################  ListTable  ############################################# */
message ListTableRequest {
}

/**
 * Currently, only a simple list of names is returned. We need to discuss whether there are any business scenarios that require obtaining information other than the table name.
 * The other information can include reserved throughput and table status; however, this information can only be rough. Detailed table information still needs to be obtained through DescribeTable.
 */
message ListTableResponse {
    repeated string table_names = 1;
}
/* ####################################################################################################### */

/* #############################################  DeleteTable  ############################################# */
message DeleteTableRequest {
    required string table_name = 1;
}

message DeleteTableResponse {
}
/* ######################################################################################################### */

/* #############################################  LoadTable  ############################################# */
message LoadTableRequest {
    required string table_name = 1;
}

message LoadTableResponse {
}
/* ######################################################################################################### */

/* #############################################  UnloadTable  ############################################# */
message UnloadTableRequest {
    required string table_name = 1;
}

message UnloadTableResponse {

}
/* ########################################################################################################## */

/**
 * The minimum value for the timestamp is 0, and the maximum value is INT64.MAX.
 * 1. To query a range, specify start_time and end_time.
 * 2. To query a specific timestamp, specify specific_time.
 */
message TimeRange {
    optional int64 start_time = 1;
    optional int64 end_time = 2;
    optional int64 specific_time = 3;
}

/* #############################################  GetRow  ############################################# */

enum ReturnType {
    RT_NONE = 0;
    RT_PK = 1;
    RT_AFTER_MODIFY = 2;
}

message ReturnContent {
    optional ReturnType return_type = 1;
    repeated string return_column_names = 2;
}

/**
 * 1. Supports users specifying a version timestamp range or a specific version time to read the designated version of columns.
 * 2. Currently, breakpoints within a row are not supported.
 */
message GetRowRequest {
    required string table_name = 1;
    required bytes primary_key = 2; // encoded as InplaceRowChangeSet, but only has primary key
    repeated string columns_to_get = 3; // If not specified, all columns will be read.
    optional TimeRange time_range = 4;
    optional int32 max_versions = 5;
    optional bool cache_blocks = 6 [default = true]; // Whether the data read this time enters the BlockCache
    optional bytes filter = 7;
    optional string start_column = 8;
    optional string end_column = 9;
    optional bytes token = 10;
    optional string transaction_id = 11;
}

message GetRowResponse {
    required ConsumedCapacity consumed = 1;
    required bytes row = 2; // encoded as InplaceRowChangeSet
    optional bytes next_token = 3;
}
/* #################################################################################################### */

/* #############################################  UpdateRow  ############################################# */
message UpdateRowRequest {
    required string table_name = 1;
    required bytes row_change = 2;
    required Condition condition = 3;
    optional ReturnContent return_content = 4;
    optional string transaction_id = 5;
}

message UpdateRowResponse {
    required ConsumedCapacity consumed = 1;
    optional bytes row = 2;
}

/* ####################################################################################################### */

/* #############################################  PutRow  ############################################# */


/**
 * Here, users are allowed to set the timestamp for each column individually, rather than being forced to use a uniform timestamp for the entire row.
 * The reason is that all columns use a unified structure, which itself includes a timestamp. Enforcing a uniform timestamp increases standardization but reduces flexibility, and this standardization does not provide any obvious benefits while adding complexity to the structure.
 */
message PutRowRequest {
    required string table_name = 1;
    required bytes row = 2; // encoded as InplaceRowChangeSet
    required Condition condition = 3;
    optional ReturnContent return_content = 4;
    optional string transaction_id = 5;
}

message PutRowResponse {
    required ConsumedCapacity consumed = 1;
    optional bytes row = 2;
}
/* #################################################################################################### */

/* #############################################  DeleteRow  ############################################# */
/**
 * OTS only supports deleting all versions of all columns in a row, and does not support:
 *  1. Deleting all versions of all columns that are less than or equal to a certain version
 */
message DeleteRowRequest {
    required string table_name = 1;
    required bytes primary_key = 2; // encoded as InplaceRowChangeSet, but only has primary key
    required Condition condition = 3;
    optional ReturnContent return_content = 4;
    optional string transaction_id = 5;
}

message DeleteRowResponse {
    required ConsumedCapacity consumed = 1;
    optional bytes row = 2;
}
/* ####################################################################################################### */

/* #############################################  BatchGetRow  ############################################# */
/**
 * In HBase, each row in a Batch operation can have different query parameters, which is not supported by OTS.
 */
message TableInBatchGetRowRequest {
    required string table_name = 1;
    repeated bytes primary_key = 2; // encoded as InplaceRowChangeSet, but only has primary key
    repeated bytes token = 3;
    repeated string columns_to_get = 4;  // If not specified, all columns will be read.
    optional TimeRange time_range = 5;
    optional int32 max_versions = 6;
    optional bool cache_blocks = 7 [default = true]; // Whether the data read this time enters the BlockCache
    optional bytes filter = 8;
    optional string start_column = 9;
    optional string end_column = 10;
}

message BatchGetRowRequest {
    repeated TableInBatchGetRowRequest tables = 1;
}

message RowInBatchGetRowResponse {
    required bool is_ok = 1;
    optional Error error = 2;
    optional ConsumedCapacity consumed = 3;
    optional bytes row = 4; // encoded as InplaceRowChangeSet
    optional bytes next_token = 5;
}

message TableInBatchGetRowResponse {
    required string table_name = 1;
    repeated RowInBatchGetRowResponse rows = 2;
}

message BatchGetRowResponse {
    repeated TableInBatchGetRowResponse tables = 1;
}
/* ######################################################################################################### */

/* #############################################  BatchWriteRow  ############################################# */

enum OperationType {
    PUT = 1;
    UPDATE = 2;
    DELETE = 3;
}

message RowInBatchWriteRowRequest {
    required OperationType type = 1;
    required bytes row_change = 2; // encoded as InplaceRowChangeSet
    required Condition condition = 3;
    optional ReturnContent return_content = 4;
}

message TableInBatchWriteRowRequest {
    required string table_name = 1;
    repeated RowInBatchWriteRowRequest rows = 2;
}

message BatchWriteRowRequest {
    repeated TableInBatchWriteRowRequest tables = 1;
    optional string transaction_id = 2;
    optional bool is_atomic = 3;
}

message RowInBatchWriteRowResponse {
    required bool is_ok = 1;
    optional Error error = 2;
    optional ConsumedCapacity consumed = 3;
    optional bytes row = 4;
}

message TableInBatchWriteRowResponse {
    required string table_name = 1;
    repeated RowInBatchWriteRowResponse rows = 2;
}

message BatchWriteRowResponse {
    repeated TableInBatchWriteRowResponse tables = 1;
}
/* ########################################################################################################### */

/* #############################################  GetRange  ############################################# */
enum Direction {
    FORWARD = 0;
    BACKWARD = 1;
}

/**
 * HBase supports the following parameters:
 *     1. TimeRange or specified time
 *     2. Filter (for filtering by column value or column name)
 * We only support selection conditions for the same version.
 */
message GetRangeRequest {
    required string table_name = 1;
    required Direction direction = 2;
    repeated string columns_to_get = 3;  // If not specified, all columns will be read.
    optional TimeRange time_range = 4;
    optional int32 max_versions = 5;
    optional int32 limit = 6;
    required bytes inclusive_start_primary_key = 7; // encoded as InplaceRowChangeSet, but only has primary key
    required bytes exclusive_end_primary_key = 8; // encoded as InplaceRowChangeSet, but only has primary key
    optional bool cache_blocks = 9 [default = true]; // Whether the data read this time is entered into BlockCache
    optional bytes filter = 10;
    optional string start_column = 11;
    optional string end_column = 12;
    optional bytes token = 13;
    optional string transaction_id = 14;
    optional DataBlockType data_block_type_hint = 15 [default = DBT_PLAIN_BUFFER];
    optional bool return_entire_primary_keys = 16 [default = true];
    optional CompressType compress_type_hint = 17 [default = CPT_NONE];
}

message GetRangeResponse {
    required ConsumedCapacity consumed = 1;
    required bytes rows = 2; // encoded as InplaceRowChangeSet
    optional bytes next_start_primary_key = 3; // If it is empty, it means all the data has been read. Encoded as InplaceRowChangeSet, but only contains the primary key.
    optional bytes next_token = 4;
    optional DataBlockType data_block_type = 5;
    optional CompressType compress_type = 6;
}
/* ###################################################################################################### */
/* #############################################  Stream  ############################################# */

message ListStreamRequest {
    optional string table_name = 1;
}

message Stream {
    required string stream_id = 1;
    required string table_name = 2;
    required int64 creation_time = 3;
}

message ListStreamResponse {
    repeated Stream streams = 1;
}

message StreamShard {
    required string shard_id = 1;
    optional string parent_id = 2;
    optional string parent_sibling_id = 3;
}

enum StreamStatus {
    STREAM_ENABLING = 1;
    STREAM_ACTIVE = 2;
}

message DescribeStreamRequest {
    required string stream_id = 1;
    optional string inclusive_start_shard_id = 2;
    optional int32 shard_limit = 3;
}

message DescribeStreamResponse {
    required string stream_id = 1;
    required int32 expiration_time = 2;
    required string table_name = 3;
    required int64 creation_time = 4;
    required StreamStatus stream_status = 5;
    repeated StreamShard shards = 6;
    optional string next_shard_id = 7;
}

message GetShardIteratorRequest {
    required string stream_id = 1;
    required string shard_id = 2;
    optional int64 timestamp = 3;
    optional string token = 4;
}

message GetShardIteratorResponse {
    required string shard_iterator = 1;
    optional string next_token = 2;
}

enum NewRowReturnPolicy {
    NO_NEW_ROW = 1;
    WITH_NEW_ROW = 2; // for row version table, return new row for update operation
    NEW_ROW_ONLY = 3; // for row version table, only return new row for update operation
}

message GetStreamRecordRequest {
    required string shard_iterator = 1;
    optional int32 limit = 2;
    optional string table_name = 3;
    optional NewRowReturnPolicy new_row_return_policy = 4;
    optional bool return_sys_columns = 5;
}

enum ActionType {
    PUT_ROW = 1;
    UPDATE_ROW = 2;
    DELETE_ROW = 3;
}

message GetStreamRecordResponse {
    message NewRowInfo {
        optional bool has_new_row = 1; // Used to distinguish between a non-existent row and an empty row(only PK).
        optional bytes columns = 2;
    }
    message StreamRecord {
        required ActionType action_type = 1;
        required bytes record = 2;
        optional bytes origin_record = 3;
        optional bytes table_name = 4;
        optional int64 version_generator_value = 5;
        optional NewRowInfo new_row_info = 6;
        optional bytes sys_columns = 7;
    }
    repeated StreamRecord stream_records = 1;
    optional string next_shard_iterator = 2;
    optional ConsumedCapacity consumed = 3;
    optional bool may_more_record = 4;
    optional int64 version_generator_value = 5;
}

/* +++++ ComputeSplitPointsBySize  +++++ */
message ComputeSplitPointsBySizeRequest {
    required string table_name = 1;
    required int64 split_size = 2; // in 100MB
    optional int64 split_size_unit_in_byte = 3;
    optional int32 split_point_limit = 4;
}

message ComputeSplitPointsBySizeResponse {
    required ConsumedCapacity consumed = 1;
    repeated PrimaryKeySchema schema = 2;

    /**
     * Split points between splits, in the increasing order
     *
     * A split is a consecutive range of primary keys,
     * whose data size is about split_size specified in the request.
     * The size could be hard to be precise.
     *
     * A split point is an array of primary-key column w.r.t. table schema,
     * which is never longer than that of table schema.
     * Tailing -inf will be omitted to reduce transmission payloads.
     */
    repeated bytes split_points = 3;

    /**
     * Locations where splits lies in.
     *
     * By the managed nature of TableStore, these locations are no more than hints.
     * If a location is not suitable to be seen, an empty string will be placed.
     */
     message SplitLocation {
         required string location = 1;
         required sint64 repeat = 2;
     }
     repeated SplitLocation locations = 4;
}
/* -------------------------------------- */

enum DefinedColumnType {
    DCT_INTEGER = 1;
    DCT_DOUBLE = 2;
    DCT_BOOLEAN = 3;
    DCT_STRING = 4;
    // field 5 is reserved for date type, not supported yet
    // field 6 is reserved for decimal type, not supported yet
    DCT_BLOB = 7;
}

message DefinedColumnSchema {
    required string name = 1;
    required DefinedColumnType type = 2;
}

enum IndexUpdateMode {
    IUM_ASYNC_INDEX = 0;
    IUM_SYNC_INDEX = 1;
}

enum IndexType {
    IT_GLOBAL_INDEX = 0;
    IT_LOCAL_INDEX = 1;
}

enum IndexSyncPhase {
    ISP_INVALID = 0;
    ISP_FULL = 1;
    ISP_INCR = 2;
}

message IndexMeta {
    required string name = 1;
    repeated string primary_key = 2;
    repeated string defined_column = 3;
    required IndexUpdateMode index_update_mode = 4;
    required IndexType index_type = 5;
    optional IndexSyncPhase index_sync_phase = 6;
}

message DescribeTableInnerInfo {
    optional string cluster_name = 1;
}

message CreateIndexRequest {
    required string main_table_name = 1;
    required IndexMeta index_meta = 2;
    optional bool include_base_data = 3;
}

message CreateIndexResponse {
}

message DropIndexRequest {
    required string main_table_name = 1;
    required string index_name = 2;
}

message DropIndexResponse {
}

message AddDefinedColumnRequest {
    required string table_name = 1;
    repeated DefinedColumnSchema columns = 2;
}

message AddDefinedColumnResponse {
}

message DeleteDefinedColumnRequest {
    required string table_name = 1;
    repeated string columns = 2;
}

message DeleteDefinedColumnResponse {
}

/* ###########################################  LocalTransaction  ########################################### */
message StartLocalTransactionRequest {
    required string table_name = 1;
    required bytes key = 2; // encoded as SQLVariant
}

message StartLocalTransactionResponse {
    required string transaction_id = 1;
};

message CommitTransactionRequest {
    required string transaction_id = 1;
}

message CommitTransactionResponse {
};

message AbortTransactionRequest {
    required string transaction_id = 1;
}

message AbortTransactionResponse {
};

/* ######################################################################################################### */

/* computeSplits */
message ComputeSplitsRequest {
    optional string table_name = 1;
    optional SearchIndexSplitsOptions search_index_splits_options = 2;
}

message SearchIndexSplitsOptions{
    optional string index_name = 1;
}

message ComputeSplitsResponse {
    optional bytes session_id = 1;
    optional int32 splits_size = 2;
}

/* SQLQuery */
enum SQLPayloadVersion {
    SQL_PLAIN_BUFFER = 1;
    SQL_FLAT_BUFFERS = 2;
}

enum SQLStatementType {
    SQL_SELECT = 1;
    SQL_CREATE_TABLE = 2;
    SQL_SHOW_TABLE = 3;
    SQL_DESCRIBE_TABLE = 4;
    SQL_DROP_TABLE = 5;
    SQL_ALTER_TABLE = 6;
}

message SQLQueryRequest {
    required string query = 1;
    optional SQLPayloadVersion version = 2;
    optional int64 sql_version = 3;
    optional string search_token = 5;
}

message TableConsumedCapacity {
    optional string table_name = 1;
    optional ConsumedCapacity consumed = 2;
    optional ReservedThroughput reserved_throughput = 3;
    optional bool is_timeseries_meta = 4;
}

message SearchConsumedCapacity {
    optional string table_name = 1;
    optional string index_name = 2;
    optional ConsumedCapacity consumed = 3;
    optional ReservedThroughput reserved_throughput = 4;
}

message SQLQueryResponse {
    repeated TableConsumedCapacity consumes = 1;
    optional bytes rows = 2;
    optional SQLPayloadVersion version = 3;
    optional SQLStatementType type = 4;
    repeated SearchConsumedCapacity search_consumes = 5;
    optional string next_search_token = 8;
}
