// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timeseries.proto

package otsprotocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetaQueryConditionType int32

const (
	MetaQueryConditionType_COMPOSITE_CONDITION   MetaQueryConditionType = 1
	MetaQueryConditionType_MEASUREMENT_CONDITION MetaQueryConditionType = 2
	MetaQueryConditionType_SOURCE_CONDITION      MetaQueryConditionType = 3
	MetaQueryConditionType_TAG_CONDITION         MetaQueryConditionType = 4
	MetaQueryConditionType_UPDATE_TIME_CONDITION MetaQueryConditionType = 5
	MetaQueryConditionType_ATTRIBUTE_CONDITION   MetaQueryConditionType = 6
)

var MetaQueryConditionType_name = map[int32]string{
	1: "COMPOSITE_CONDITION",
	2: "MEASUREMENT_CONDITION",
	3: "SOURCE_CONDITION",
	4: "TAG_CONDITION",
	5: "UPDATE_TIME_CONDITION",
	6: "ATTRIBUTE_CONDITION",
}

var MetaQueryConditionType_value = map[string]int32{
	"COMPOSITE_CONDITION":   1,
	"MEASUREMENT_CONDITION": 2,
	"SOURCE_CONDITION":      3,
	"TAG_CONDITION":         4,
	"UPDATE_TIME_CONDITION": 5,
	"ATTRIBUTE_CONDITION":   6,
}

func (x MetaQueryConditionType) Enum() *MetaQueryConditionType {
	p := new(MetaQueryConditionType)
	*p = x
	return p
}

func (x MetaQueryConditionType) String() string {
	return proto.EnumName(MetaQueryConditionType_name, int32(x))
}

func (x *MetaQueryConditionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetaQueryConditionType_value, data, "MetaQueryConditionType")
	if err != nil {
		return err
	}
	*x = MetaQueryConditionType(value)
	return nil
}

func (MetaQueryConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{0}
}

type MetaQueryCompositeOperator int32

const (
	MetaQueryCompositeOperator_OP_AND MetaQueryCompositeOperator = 1
	MetaQueryCompositeOperator_OP_OR  MetaQueryCompositeOperator = 2
	MetaQueryCompositeOperator_OP_NOT MetaQueryCompositeOperator = 3
)

var MetaQueryCompositeOperator_name = map[int32]string{
	1: "OP_AND",
	2: "OP_OR",
	3: "OP_NOT",
}

var MetaQueryCompositeOperator_value = map[string]int32{
	"OP_AND": 1,
	"OP_OR":  2,
	"OP_NOT": 3,
}

func (x MetaQueryCompositeOperator) Enum() *MetaQueryCompositeOperator {
	p := new(MetaQueryCompositeOperator)
	*p = x
	return p
}

func (x MetaQueryCompositeOperator) String() string {
	return proto.EnumName(MetaQueryCompositeOperator_name, int32(x))
}

func (x *MetaQueryCompositeOperator) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetaQueryCompositeOperator_value, data, "MetaQueryCompositeOperator")
	if err != nil {
		return err
	}
	*x = MetaQueryCompositeOperator(value)
	return nil
}

func (MetaQueryCompositeOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{1}
}

type MetaQuerySingleOperator int32

const (
	MetaQuerySingleOperator_OP_EQUAL         MetaQuerySingleOperator = 1
	MetaQuerySingleOperator_OP_GREATER_THAN  MetaQuerySingleOperator = 2
	MetaQuerySingleOperator_OP_GREATER_EQUAL MetaQuerySingleOperator = 3
	MetaQuerySingleOperator_OP_LESS_THAN     MetaQuerySingleOperator = 4
	MetaQuerySingleOperator_OP_LESS_EQUAL    MetaQuerySingleOperator = 5
	MetaQuerySingleOperator_OP_PREFIX        MetaQuerySingleOperator = 6
)

var MetaQuerySingleOperator_name = map[int32]string{
	1: "OP_EQUAL",
	2: "OP_GREATER_THAN",
	3: "OP_GREATER_EQUAL",
	4: "OP_LESS_THAN",
	5: "OP_LESS_EQUAL",
	6: "OP_PREFIX",
}

var MetaQuerySingleOperator_value = map[string]int32{
	"OP_EQUAL":         1,
	"OP_GREATER_THAN":  2,
	"OP_GREATER_EQUAL": 3,
	"OP_LESS_THAN":     4,
	"OP_LESS_EQUAL":    5,
	"OP_PREFIX":        6,
}

func (x MetaQuerySingleOperator) Enum() *MetaQuerySingleOperator {
	p := new(MetaQuerySingleOperator)
	*p = x
	return p
}

func (x MetaQuerySingleOperator) String() string {
	return proto.EnumName(MetaQuerySingleOperator_name, int32(x))
}

func (x *MetaQuerySingleOperator) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetaQuerySingleOperator_value, data, "MetaQuerySingleOperator")
	if err != nil {
		return err
	}
	*x = MetaQuerySingleOperator(value)
	return nil
}

func (MetaQuerySingleOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{2}
}

type RowsSerializeType int32

const (
	RowsSerializeType_RST_FLAT_BUFFER RowsSerializeType = 0
)

var RowsSerializeType_name = map[int32]string{
	0: "RST_FLAT_BUFFER",
}

var RowsSerializeType_value = map[string]int32{
	"RST_FLAT_BUFFER": 0,
}

func (x RowsSerializeType) Enum() *RowsSerializeType {
	p := new(RowsSerializeType)
	*p = x
	return p
}

func (x RowsSerializeType) String() string {
	return proto.EnumName(RowsSerializeType_name, int32(x))
}

func (x *RowsSerializeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RowsSerializeType_value, data, "RowsSerializeType")
	if err != nil {
		return err
	}
	*x = RowsSerializeType(value)
	return nil
}

func (RowsSerializeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{3}
}

type MetaUpdateMode int32

const (
	MetaUpdateMode_MUM_NORMAL MetaUpdateMode = 0
	MetaUpdateMode_MUM_IGNORE MetaUpdateMode = 1
)

var MetaUpdateMode_name = map[int32]string{
	0: "MUM_NORMAL",
	1: "MUM_IGNORE",
}

var MetaUpdateMode_value = map[string]int32{
	"MUM_NORMAL": 0,
	"MUM_IGNORE": 1,
}

func (x MetaUpdateMode) Enum() *MetaUpdateMode {
	p := new(MetaUpdateMode)
	*p = x
	return p
}

func (x MetaUpdateMode) String() string {
	return proto.EnumName(MetaUpdateMode_name, int32(x))
}

func (x *MetaUpdateMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetaUpdateMode_value, data, "MetaUpdateMode")
	if err != nil {
		return err
	}
	*x = MetaUpdateMode(value)
	return nil
}

func (MetaUpdateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{4}
}

type TimeseriesTableOptions struct {
	TimeToLive           *int32   `protobuf:"varint,1,opt,name=time_to_live,json=timeToLive" json:"time_to_live,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeseriesTableOptions) Reset()         { *m = TimeseriesTableOptions{} }
func (m *TimeseriesTableOptions) String() string { return proto.CompactTextString(m) }
func (*TimeseriesTableOptions) ProtoMessage()    {}
func (*TimeseriesTableOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{0}
}

func (m *TimeseriesTableOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeseriesTableOptions.Unmarshal(m, b)
}
func (m *TimeseriesTableOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeseriesTableOptions.Marshal(b, m, deterministic)
}
func (m *TimeseriesTableOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeseriesTableOptions.Merge(m, src)
}
func (m *TimeseriesTableOptions) XXX_Size() int {
	return xxx_messageInfo_TimeseriesTableOptions.Size(m)
}
func (m *TimeseriesTableOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeseriesTableOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TimeseriesTableOptions proto.InternalMessageInfo

func (m *TimeseriesTableOptions) GetTimeToLive() int32 {
	if m != nil && m.TimeToLive != nil {
		return *m.TimeToLive
	}
	return 0
}

type TimeseriesTableMeta struct {
	TableName            *string                 `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	TableOptions         *TimeseriesTableOptions `protobuf:"bytes,2,opt,name=table_options,json=tableOptions" json:"table_options,omitempty"`
	Status               *string                 `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TimeseriesTableMeta) Reset()         { *m = TimeseriesTableMeta{} }
func (m *TimeseriesTableMeta) String() string { return proto.CompactTextString(m) }
func (*TimeseriesTableMeta) ProtoMessage()    {}
func (*TimeseriesTableMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{1}
}

func (m *TimeseriesTableMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeseriesTableMeta.Unmarshal(m, b)
}
func (m *TimeseriesTableMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeseriesTableMeta.Marshal(b, m, deterministic)
}
func (m *TimeseriesTableMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeseriesTableMeta.Merge(m, src)
}
func (m *TimeseriesTableMeta) XXX_Size() int {
	return xxx_messageInfo_TimeseriesTableMeta.Size(m)
}
func (m *TimeseriesTableMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeseriesTableMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TimeseriesTableMeta proto.InternalMessageInfo

func (m *TimeseriesTableMeta) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *TimeseriesTableMeta) GetTableOptions() *TimeseriesTableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

func (m *TimeseriesTableMeta) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

type CreateTimeseriesTableRequest struct {
	TableMeta            *TimeseriesTableMeta `protobuf:"bytes,1,req,name=table_meta,json=tableMeta" json:"table_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTimeseriesTableRequest) Reset()         { *m = CreateTimeseriesTableRequest{} }
func (m *CreateTimeseriesTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTimeseriesTableRequest) ProtoMessage()    {}
func (*CreateTimeseriesTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{2}
}

func (m *CreateTimeseriesTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTimeseriesTableRequest.Unmarshal(m, b)
}
func (m *CreateTimeseriesTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTimeseriesTableRequest.Marshal(b, m, deterministic)
}
func (m *CreateTimeseriesTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTimeseriesTableRequest.Merge(m, src)
}
func (m *CreateTimeseriesTableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTimeseriesTableRequest.Size(m)
}
func (m *CreateTimeseriesTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTimeseriesTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTimeseriesTableRequest proto.InternalMessageInfo

func (m *CreateTimeseriesTableRequest) GetTableMeta() *TimeseriesTableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

type CreateTimeseriesTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTimeseriesTableResponse) Reset()         { *m = CreateTimeseriesTableResponse{} }
func (m *CreateTimeseriesTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTimeseriesTableResponse) ProtoMessage()    {}
func (*CreateTimeseriesTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{3}
}

func (m *CreateTimeseriesTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTimeseriesTableResponse.Unmarshal(m, b)
}
func (m *CreateTimeseriesTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTimeseriesTableResponse.Marshal(b, m, deterministic)
}
func (m *CreateTimeseriesTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTimeseriesTableResponse.Merge(m, src)
}
func (m *CreateTimeseriesTableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTimeseriesTableResponse.Size(m)
}
func (m *CreateTimeseriesTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTimeseriesTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTimeseriesTableResponse proto.InternalMessageInfo

type ListTimeseriesTableRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTimeseriesTableRequest) Reset()         { *m = ListTimeseriesTableRequest{} }
func (m *ListTimeseriesTableRequest) String() string { return proto.CompactTextString(m) }
func (*ListTimeseriesTableRequest) ProtoMessage()    {}
func (*ListTimeseriesTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{4}
}

func (m *ListTimeseriesTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimeseriesTableRequest.Unmarshal(m, b)
}
func (m *ListTimeseriesTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimeseriesTableRequest.Marshal(b, m, deterministic)
}
func (m *ListTimeseriesTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimeseriesTableRequest.Merge(m, src)
}
func (m *ListTimeseriesTableRequest) XXX_Size() int {
	return xxx_messageInfo_ListTimeseriesTableRequest.Size(m)
}
func (m *ListTimeseriesTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimeseriesTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimeseriesTableRequest proto.InternalMessageInfo

type ListTimeseriesTableResponse struct {
	TableMetas           []*TimeseriesTableMeta `protobuf:"bytes,1,rep,name=table_metas,json=tableMetas" json:"table_metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListTimeseriesTableResponse) Reset()         { *m = ListTimeseriesTableResponse{} }
func (m *ListTimeseriesTableResponse) String() string { return proto.CompactTextString(m) }
func (*ListTimeseriesTableResponse) ProtoMessage()    {}
func (*ListTimeseriesTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{5}
}

func (m *ListTimeseriesTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimeseriesTableResponse.Unmarshal(m, b)
}
func (m *ListTimeseriesTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimeseriesTableResponse.Marshal(b, m, deterministic)
}
func (m *ListTimeseriesTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimeseriesTableResponse.Merge(m, src)
}
func (m *ListTimeseriesTableResponse) XXX_Size() int {
	return xxx_messageInfo_ListTimeseriesTableResponse.Size(m)
}
func (m *ListTimeseriesTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimeseriesTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimeseriesTableResponse proto.InternalMessageInfo

func (m *ListTimeseriesTableResponse) GetTableMetas() []*TimeseriesTableMeta {
	if m != nil {
		return m.TableMetas
	}
	return nil
}

type DeleteTimeseriesTableRequest struct {
	TableName            *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTimeseriesTableRequest) Reset()         { *m = DeleteTimeseriesTableRequest{} }
func (m *DeleteTimeseriesTableRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTimeseriesTableRequest) ProtoMessage()    {}
func (*DeleteTimeseriesTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{6}
}

func (m *DeleteTimeseriesTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTimeseriesTableRequest.Unmarshal(m, b)
}
func (m *DeleteTimeseriesTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTimeseriesTableRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTimeseriesTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTimeseriesTableRequest.Merge(m, src)
}
func (m *DeleteTimeseriesTableRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTimeseriesTableRequest.Size(m)
}
func (m *DeleteTimeseriesTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTimeseriesTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTimeseriesTableRequest proto.InternalMessageInfo

func (m *DeleteTimeseriesTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DeleteTimeseriesTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTimeseriesTableResponse) Reset()         { *m = DeleteTimeseriesTableResponse{} }
func (m *DeleteTimeseriesTableResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTimeseriesTableResponse) ProtoMessage()    {}
func (*DeleteTimeseriesTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{7}
}

func (m *DeleteTimeseriesTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTimeseriesTableResponse.Unmarshal(m, b)
}
func (m *DeleteTimeseriesTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTimeseriesTableResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTimeseriesTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTimeseriesTableResponse.Merge(m, src)
}
func (m *DeleteTimeseriesTableResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTimeseriesTableResponse.Size(m)
}
func (m *DeleteTimeseriesTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTimeseriesTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTimeseriesTableResponse proto.InternalMessageInfo

type UpdateTimeseriesTableRequest struct {
	TableName            *string                 `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	TableOptions         *TimeseriesTableOptions `protobuf:"bytes,2,opt,name=table_options,json=tableOptions" json:"table_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateTimeseriesTableRequest) Reset()         { *m = UpdateTimeseriesTableRequest{} }
func (m *UpdateTimeseriesTableRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTimeseriesTableRequest) ProtoMessage()    {}
func (*UpdateTimeseriesTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{8}
}

func (m *UpdateTimeseriesTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTimeseriesTableRequest.Unmarshal(m, b)
}
func (m *UpdateTimeseriesTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTimeseriesTableRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTimeseriesTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTimeseriesTableRequest.Merge(m, src)
}
func (m *UpdateTimeseriesTableRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTimeseriesTableRequest.Size(m)
}
func (m *UpdateTimeseriesTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTimeseriesTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTimeseriesTableRequest proto.InternalMessageInfo

func (m *UpdateTimeseriesTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateTimeseriesTableRequest) GetTableOptions() *TimeseriesTableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

type UpdateTimeseriesTableResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTimeseriesTableResponse) Reset()         { *m = UpdateTimeseriesTableResponse{} }
func (m *UpdateTimeseriesTableResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTimeseriesTableResponse) ProtoMessage()    {}
func (*UpdateTimeseriesTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{9}
}

func (m *UpdateTimeseriesTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTimeseriesTableResponse.Unmarshal(m, b)
}
func (m *UpdateTimeseriesTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTimeseriesTableResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTimeseriesTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTimeseriesTableResponse.Merge(m, src)
}
func (m *UpdateTimeseriesTableResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTimeseriesTableResponse.Size(m)
}
func (m *UpdateTimeseriesTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTimeseriesTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTimeseriesTableResponse proto.InternalMessageInfo

type DescribeTimeseriesTableRequest struct {
	TableName            *string  `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTimeseriesTableRequest) Reset()         { *m = DescribeTimeseriesTableRequest{} }
func (m *DescribeTimeseriesTableRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeTimeseriesTableRequest) ProtoMessage()    {}
func (*DescribeTimeseriesTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{10}
}

func (m *DescribeTimeseriesTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTimeseriesTableRequest.Unmarshal(m, b)
}
func (m *DescribeTimeseriesTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTimeseriesTableRequest.Marshal(b, m, deterministic)
}
func (m *DescribeTimeseriesTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTimeseriesTableRequest.Merge(m, src)
}
func (m *DescribeTimeseriesTableRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeTimeseriesTableRequest.Size(m)
}
func (m *DescribeTimeseriesTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTimeseriesTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTimeseriesTableRequest proto.InternalMessageInfo

func (m *DescribeTimeseriesTableRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

type DescribeTimeseriesTableResponse struct {
	TableMeta            *TimeseriesTableMeta `protobuf:"bytes,1,req,name=table_meta,json=tableMeta" json:"table_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DescribeTimeseriesTableResponse) Reset()         { *m = DescribeTimeseriesTableResponse{} }
func (m *DescribeTimeseriesTableResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeTimeseriesTableResponse) ProtoMessage()    {}
func (*DescribeTimeseriesTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{11}
}

func (m *DescribeTimeseriesTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTimeseriesTableResponse.Unmarshal(m, b)
}
func (m *DescribeTimeseriesTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTimeseriesTableResponse.Marshal(b, m, deterministic)
}
func (m *DescribeTimeseriesTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTimeseriesTableResponse.Merge(m, src)
}
func (m *DescribeTimeseriesTableResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeTimeseriesTableResponse.Size(m)
}
func (m *DescribeTimeseriesTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTimeseriesTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTimeseriesTableResponse proto.InternalMessageInfo

func (m *DescribeTimeseriesTableResponse) GetTableMeta() *TimeseriesTableMeta {
	if m != nil {
		return m.TableMeta
	}
	return nil
}

type MetaQueryCondition struct {
	Type                 *MetaQueryConditionType `protobuf:"varint,1,req,name=type,enum=otsprotocol.MetaQueryConditionType" json:"type,omitempty"`
	ProtoData            []byte                  `protobuf:"bytes,2,req,name=proto_data,json=protoData" json:"proto_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MetaQueryCondition) Reset()         { *m = MetaQueryCondition{} }
func (m *MetaQueryCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryCondition) ProtoMessage()    {}
func (*MetaQueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{12}
}

func (m *MetaQueryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryCondition.Unmarshal(m, b)
}
func (m *MetaQueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryCondition.Merge(m, src)
}
func (m *MetaQueryCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryCondition.Size(m)
}
func (m *MetaQueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryCondition proto.InternalMessageInfo

func (m *MetaQueryCondition) GetType() MetaQueryConditionType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MetaQueryConditionType_COMPOSITE_CONDITION
}

func (m *MetaQueryCondition) GetProtoData() []byte {
	if m != nil {
		return m.ProtoData
	}
	return nil
}

type MetaQueryCompositeCondition struct {
	Op                   *MetaQueryCompositeOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQueryCompositeOperator" json:"op,omitempty"`
	SubConditions        []*MetaQueryCondition       `protobuf:"bytes,2,rep,name=sub_conditions,json=subConditions" json:"sub_conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MetaQueryCompositeCondition) Reset()         { *m = MetaQueryCompositeCondition{} }
func (m *MetaQueryCompositeCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryCompositeCondition) ProtoMessage()    {}
func (*MetaQueryCompositeCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{13}
}

func (m *MetaQueryCompositeCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryCompositeCondition.Unmarshal(m, b)
}
func (m *MetaQueryCompositeCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryCompositeCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryCompositeCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryCompositeCondition.Merge(m, src)
}
func (m *MetaQueryCompositeCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryCompositeCondition.Size(m)
}
func (m *MetaQueryCompositeCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryCompositeCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryCompositeCondition proto.InternalMessageInfo

func (m *MetaQueryCompositeCondition) GetOp() MetaQueryCompositeOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQueryCompositeOperator_OP_AND
}

func (m *MetaQueryCompositeCondition) GetSubConditions() []*MetaQueryCondition {
	if m != nil {
		return m.SubConditions
	}
	return nil
}

type MetaQueryMeasurementCondition struct {
	Op                   *MetaQuerySingleOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQuerySingleOperator" json:"op,omitempty"`
	Value                *string                  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaQueryMeasurementCondition) Reset()         { *m = MetaQueryMeasurementCondition{} }
func (m *MetaQueryMeasurementCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryMeasurementCondition) ProtoMessage()    {}
func (*MetaQueryMeasurementCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{14}
}

func (m *MetaQueryMeasurementCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryMeasurementCondition.Unmarshal(m, b)
}
func (m *MetaQueryMeasurementCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryMeasurementCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryMeasurementCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryMeasurementCondition.Merge(m, src)
}
func (m *MetaQueryMeasurementCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryMeasurementCondition.Size(m)
}
func (m *MetaQueryMeasurementCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryMeasurementCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryMeasurementCondition proto.InternalMessageInfo

func (m *MetaQueryMeasurementCondition) GetOp() MetaQuerySingleOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQuerySingleOperator_OP_EQUAL
}

func (m *MetaQueryMeasurementCondition) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type MetaQuerySourceCondition struct {
	Op                   *MetaQuerySingleOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQuerySingleOperator" json:"op,omitempty"`
	Value                *string                  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaQuerySourceCondition) Reset()         { *m = MetaQuerySourceCondition{} }
func (m *MetaQuerySourceCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQuerySourceCondition) ProtoMessage()    {}
func (*MetaQuerySourceCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{15}
}

func (m *MetaQuerySourceCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQuerySourceCondition.Unmarshal(m, b)
}
func (m *MetaQuerySourceCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQuerySourceCondition.Marshal(b, m, deterministic)
}
func (m *MetaQuerySourceCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQuerySourceCondition.Merge(m, src)
}
func (m *MetaQuerySourceCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQuerySourceCondition.Size(m)
}
func (m *MetaQuerySourceCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQuerySourceCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQuerySourceCondition proto.InternalMessageInfo

func (m *MetaQuerySourceCondition) GetOp() MetaQuerySingleOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQuerySingleOperator_OP_EQUAL
}

func (m *MetaQuerySourceCondition) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type MetaQueryTagCondition struct {
	Op                   *MetaQuerySingleOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQuerySingleOperator" json:"op,omitempty"`
	TagName              *string                  `protobuf:"bytes,2,req,name=tag_name,json=tagName" json:"tag_name,omitempty"`
	Value                *string                  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaQueryTagCondition) Reset()         { *m = MetaQueryTagCondition{} }
func (m *MetaQueryTagCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryTagCondition) ProtoMessage()    {}
func (*MetaQueryTagCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{16}
}

func (m *MetaQueryTagCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryTagCondition.Unmarshal(m, b)
}
func (m *MetaQueryTagCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryTagCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryTagCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryTagCondition.Merge(m, src)
}
func (m *MetaQueryTagCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryTagCondition.Size(m)
}
func (m *MetaQueryTagCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryTagCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryTagCondition proto.InternalMessageInfo

func (m *MetaQueryTagCondition) GetOp() MetaQuerySingleOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQuerySingleOperator_OP_EQUAL
}

func (m *MetaQueryTagCondition) GetTagName() string {
	if m != nil && m.TagName != nil {
		return *m.TagName
	}
	return ""
}

func (m *MetaQueryTagCondition) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type MetaQueryAttributeCondition struct {
	Op                   *MetaQuerySingleOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQuerySingleOperator" json:"op,omitempty"`
	AttrName             *string                  `protobuf:"bytes,2,req,name=attr_name,json=attrName" json:"attr_name,omitempty"`
	Value                *string                  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaQueryAttributeCondition) Reset()         { *m = MetaQueryAttributeCondition{} }
func (m *MetaQueryAttributeCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryAttributeCondition) ProtoMessage()    {}
func (*MetaQueryAttributeCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{17}
}

func (m *MetaQueryAttributeCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryAttributeCondition.Unmarshal(m, b)
}
func (m *MetaQueryAttributeCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryAttributeCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryAttributeCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryAttributeCondition.Merge(m, src)
}
func (m *MetaQueryAttributeCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryAttributeCondition.Size(m)
}
func (m *MetaQueryAttributeCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryAttributeCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryAttributeCondition proto.InternalMessageInfo

func (m *MetaQueryAttributeCondition) GetOp() MetaQuerySingleOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQuerySingleOperator_OP_EQUAL
}

func (m *MetaQueryAttributeCondition) GetAttrName() string {
	if m != nil && m.AttrName != nil {
		return *m.AttrName
	}
	return ""
}

func (m *MetaQueryAttributeCondition) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type MetaQueryUpdateTimeCondition struct {
	Op                   *MetaQuerySingleOperator `protobuf:"varint,1,req,name=op,enum=otsprotocol.MetaQuerySingleOperator" json:"op,omitempty"`
	Value                *int64                   `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaQueryUpdateTimeCondition) Reset()         { *m = MetaQueryUpdateTimeCondition{} }
func (m *MetaQueryUpdateTimeCondition) String() string { return proto.CompactTextString(m) }
func (*MetaQueryUpdateTimeCondition) ProtoMessage()    {}
func (*MetaQueryUpdateTimeCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{18}
}

func (m *MetaQueryUpdateTimeCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaQueryUpdateTimeCondition.Unmarshal(m, b)
}
func (m *MetaQueryUpdateTimeCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaQueryUpdateTimeCondition.Marshal(b, m, deterministic)
}
func (m *MetaQueryUpdateTimeCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaQueryUpdateTimeCondition.Merge(m, src)
}
func (m *MetaQueryUpdateTimeCondition) XXX_Size() int {
	return xxx_messageInfo_MetaQueryUpdateTimeCondition.Size(m)
}
func (m *MetaQueryUpdateTimeCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaQueryUpdateTimeCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MetaQueryUpdateTimeCondition proto.InternalMessageInfo

func (m *MetaQueryUpdateTimeCondition) GetOp() MetaQuerySingleOperator {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return MetaQuerySingleOperator_OP_EQUAL
}

func (m *MetaQueryUpdateTimeCondition) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type TimeseriesKey struct {
	Measurement          *string  `protobuf:"bytes,1,req,name=measurement" json:"measurement,omitempty"`
	Source               *string  `protobuf:"bytes,2,req,name=source" json:"source,omitempty"`
	Tags                 *string  `protobuf:"bytes,3,req,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeseriesKey) Reset()         { *m = TimeseriesKey{} }
func (m *TimeseriesKey) String() string { return proto.CompactTextString(m) }
func (*TimeseriesKey) ProtoMessage()    {}
func (*TimeseriesKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{19}
}

func (m *TimeseriesKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeseriesKey.Unmarshal(m, b)
}
func (m *TimeseriesKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeseriesKey.Marshal(b, m, deterministic)
}
func (m *TimeseriesKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeseriesKey.Merge(m, src)
}
func (m *TimeseriesKey) XXX_Size() int {
	return xxx_messageInfo_TimeseriesKey.Size(m)
}
func (m *TimeseriesKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeseriesKey.DiscardUnknown(m)
}

var xxx_messageInfo_TimeseriesKey proto.InternalMessageInfo

func (m *TimeseriesKey) GetMeasurement() string {
	if m != nil && m.Measurement != nil {
		return *m.Measurement
	}
	return ""
}

func (m *TimeseriesKey) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *TimeseriesKey) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

type TimeseriesMeta struct {
	TimeSeriesKey        *TimeseriesKey `protobuf:"bytes,1,req,name=time_series_key,json=timeSeriesKey" json:"time_series_key,omitempty"`
	Attributes           *string        `protobuf:"bytes,2,opt,name=attributes" json:"attributes,omitempty"`
	UpdateTime           *int64         `protobuf:"varint,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TimeseriesMeta) Reset()         { *m = TimeseriesMeta{} }
func (m *TimeseriesMeta) String() string { return proto.CompactTextString(m) }
func (*TimeseriesMeta) ProtoMessage()    {}
func (*TimeseriesMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{20}
}

func (m *TimeseriesMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeseriesMeta.Unmarshal(m, b)
}
func (m *TimeseriesMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeseriesMeta.Marshal(b, m, deterministic)
}
func (m *TimeseriesMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeseriesMeta.Merge(m, src)
}
func (m *TimeseriesMeta) XXX_Size() int {
	return xxx_messageInfo_TimeseriesMeta.Size(m)
}
func (m *TimeseriesMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeseriesMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TimeseriesMeta proto.InternalMessageInfo

func (m *TimeseriesMeta) GetTimeSeriesKey() *TimeseriesKey {
	if m != nil {
		return m.TimeSeriesKey
	}
	return nil
}

func (m *TimeseriesMeta) GetAttributes() string {
	if m != nil && m.Attributes != nil {
		return *m.Attributes
	}
	return ""
}

func (m *TimeseriesMeta) GetUpdateTime() int64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

type QueryTimeseriesMetaRequest struct {
	TableName            *string             `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	Condition            *MetaQueryCondition `protobuf:"bytes,2,opt,name=condition" json:"condition,omitempty"`
	GetTotalHit          *bool               `protobuf:"varint,3,opt,name=get_total_hit,json=getTotalHit" json:"get_total_hit,omitempty"`
	Token                []byte              `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Limit                *int32              `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryTimeseriesMetaRequest) Reset()         { *m = QueryTimeseriesMetaRequest{} }
func (m *QueryTimeseriesMetaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTimeseriesMetaRequest) ProtoMessage()    {}
func (*QueryTimeseriesMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{21}
}

func (m *QueryTimeseriesMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTimeseriesMetaRequest.Unmarshal(m, b)
}
func (m *QueryTimeseriesMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTimeseriesMetaRequest.Marshal(b, m, deterministic)
}
func (m *QueryTimeseriesMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTimeseriesMetaRequest.Merge(m, src)
}
func (m *QueryTimeseriesMetaRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTimeseriesMetaRequest.Size(m)
}
func (m *QueryTimeseriesMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTimeseriesMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTimeseriesMetaRequest proto.InternalMessageInfo

func (m *QueryTimeseriesMetaRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *QueryTimeseriesMetaRequest) GetCondition() *MetaQueryCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *QueryTimeseriesMetaRequest) GetGetTotalHit() bool {
	if m != nil && m.GetTotalHit != nil {
		return *m.GetTotalHit
	}
	return false
}

func (m *QueryTimeseriesMetaRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *QueryTimeseriesMetaRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type QueryTimeseriesMetaResponse struct {
	TimeseriesMetas      []*TimeseriesMeta `protobuf:"bytes,1,rep,name=timeseries_metas,json=timeseriesMetas" json:"timeseries_metas,omitempty"`
	TotalHit             *int64            `protobuf:"varint,2,opt,name=total_hit,json=totalHit" json:"total_hit,omitempty"`
	NextToken            []byte            `protobuf:"bytes,3,opt,name=next_token,json=nextToken" json:"next_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryTimeseriesMetaResponse) Reset()         { *m = QueryTimeseriesMetaResponse{} }
func (m *QueryTimeseriesMetaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTimeseriesMetaResponse) ProtoMessage()    {}
func (*QueryTimeseriesMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{22}
}

func (m *QueryTimeseriesMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTimeseriesMetaResponse.Unmarshal(m, b)
}
func (m *QueryTimeseriesMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTimeseriesMetaResponse.Marshal(b, m, deterministic)
}
func (m *QueryTimeseriesMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTimeseriesMetaResponse.Merge(m, src)
}
func (m *QueryTimeseriesMetaResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTimeseriesMetaResponse.Size(m)
}
func (m *QueryTimeseriesMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTimeseriesMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTimeseriesMetaResponse proto.InternalMessageInfo

func (m *QueryTimeseriesMetaResponse) GetTimeseriesMetas() []*TimeseriesMeta {
	if m != nil {
		return m.TimeseriesMetas
	}
	return nil
}

func (m *QueryTimeseriesMetaResponse) GetTotalHit() int64 {
	if m != nil && m.TotalHit != nil {
		return *m.TotalHit
	}
	return 0
}

func (m *QueryTimeseriesMetaResponse) GetNextToken() []byte {
	if m != nil {
		return m.NextToken
	}
	return nil
}

type TimeseriesRows struct {
	Type                 *RowsSerializeType `protobuf:"varint,1,req,name=type,enum=otsprotocol.RowsSerializeType" json:"type,omitempty"`
	RowsData             []byte             `protobuf:"bytes,2,req,name=rows_data,json=rowsData" json:"rows_data,omitempty"`
	FlatbufferCrc32C     *int32             `protobuf:"varint,3,opt,name=flatbuffer_crc32c,json=flatbufferCrc32c" json:"flatbuffer_crc32c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TimeseriesRows) Reset()         { *m = TimeseriesRows{} }
func (m *TimeseriesRows) String() string { return proto.CompactTextString(m) }
func (*TimeseriesRows) ProtoMessage()    {}
func (*TimeseriesRows) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{23}
}

func (m *TimeseriesRows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeseriesRows.Unmarshal(m, b)
}
func (m *TimeseriesRows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeseriesRows.Marshal(b, m, deterministic)
}
func (m *TimeseriesRows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeseriesRows.Merge(m, src)
}
func (m *TimeseriesRows) XXX_Size() int {
	return xxx_messageInfo_TimeseriesRows.Size(m)
}
func (m *TimeseriesRows) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeseriesRows.DiscardUnknown(m)
}

var xxx_messageInfo_TimeseriesRows proto.InternalMessageInfo

func (m *TimeseriesRows) GetType() RowsSerializeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RowsSerializeType_RST_FLAT_BUFFER
}

func (m *TimeseriesRows) GetRowsData() []byte {
	if m != nil {
		return m.RowsData
	}
	return nil
}

func (m *TimeseriesRows) GetFlatbufferCrc32C() int32 {
	if m != nil && m.FlatbufferCrc32C != nil {
		return *m.FlatbufferCrc32C
	}
	return 0
}

type PutTimeseriesDataRequest struct {
	TableName            *string         `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	RowsData             *TimeseriesRows `protobuf:"bytes,2,req,name=rows_data,json=rowsData" json:"rows_data,omitempty"`
	MetaUpdateMode       *MetaUpdateMode `protobuf:"varint,3,opt,name=meta_update_mode,json=metaUpdateMode,enum=otsprotocol.MetaUpdateMode" json:"meta_update_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutTimeseriesDataRequest) Reset()         { *m = PutTimeseriesDataRequest{} }
func (m *PutTimeseriesDataRequest) String() string { return proto.CompactTextString(m) }
func (*PutTimeseriesDataRequest) ProtoMessage()    {}
func (*PutTimeseriesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{24}
}

func (m *PutTimeseriesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutTimeseriesDataRequest.Unmarshal(m, b)
}
func (m *PutTimeseriesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutTimeseriesDataRequest.Marshal(b, m, deterministic)
}
func (m *PutTimeseriesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutTimeseriesDataRequest.Merge(m, src)
}
func (m *PutTimeseriesDataRequest) XXX_Size() int {
	return xxx_messageInfo_PutTimeseriesDataRequest.Size(m)
}
func (m *PutTimeseriesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutTimeseriesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutTimeseriesDataRequest proto.InternalMessageInfo

func (m *PutTimeseriesDataRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *PutTimeseriesDataRequest) GetRowsData() *TimeseriesRows {
	if m != nil {
		return m.RowsData
	}
	return nil
}

func (m *PutTimeseriesDataRequest) GetMetaUpdateMode() MetaUpdateMode {
	if m != nil && m.MetaUpdateMode != nil {
		return *m.MetaUpdateMode
	}
	return MetaUpdateMode_MUM_NORMAL
}

type FailedRowInfo struct {
	RowIndex             *int32   `protobuf:"varint,1,req,name=row_index,json=rowIndex" json:"row_index,omitempty"`
	ErrorCode            *string  `protobuf:"bytes,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage         *string  `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedRowInfo) Reset()         { *m = FailedRowInfo{} }
func (m *FailedRowInfo) String() string { return proto.CompactTextString(m) }
func (*FailedRowInfo) ProtoMessage()    {}
func (*FailedRowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{25}
}

func (m *FailedRowInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedRowInfo.Unmarshal(m, b)
}
func (m *FailedRowInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedRowInfo.Marshal(b, m, deterministic)
}
func (m *FailedRowInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedRowInfo.Merge(m, src)
}
func (m *FailedRowInfo) XXX_Size() int {
	return xxx_messageInfo_FailedRowInfo.Size(m)
}
func (m *FailedRowInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedRowInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FailedRowInfo proto.InternalMessageInfo

func (m *FailedRowInfo) GetRowIndex() int32 {
	if m != nil && m.RowIndex != nil {
		return *m.RowIndex
	}
	return 0
}

func (m *FailedRowInfo) GetErrorCode() string {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ""
}

func (m *FailedRowInfo) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type MetaUpdateStatus struct {
	RowIds               []uint32 `protobuf:"varint,1,rep,name=row_ids,json=rowIds" json:"row_ids,omitempty"`
	MetaUpdateTimes      []uint32 `protobuf:"varint,2,rep,name=meta_update_times,json=metaUpdateTimes" json:"meta_update_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaUpdateStatus) Reset()         { *m = MetaUpdateStatus{} }
func (m *MetaUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*MetaUpdateStatus) ProtoMessage()    {}
func (*MetaUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{26}
}

func (m *MetaUpdateStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaUpdateStatus.Unmarshal(m, b)
}
func (m *MetaUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaUpdateStatus.Marshal(b, m, deterministic)
}
func (m *MetaUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaUpdateStatus.Merge(m, src)
}
func (m *MetaUpdateStatus) XXX_Size() int {
	return xxx_messageInfo_MetaUpdateStatus.Size(m)
}
func (m *MetaUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MetaUpdateStatus proto.InternalMessageInfo

func (m *MetaUpdateStatus) GetRowIds() []uint32 {
	if m != nil {
		return m.RowIds
	}
	return nil
}

func (m *MetaUpdateStatus) GetMetaUpdateTimes() []uint32 {
	if m != nil {
		return m.MetaUpdateTimes
	}
	return nil
}

type PutTimeseriesDataResponse struct {
	FailedRows           []*FailedRowInfo  `protobuf:"bytes,1,rep,name=failed_rows,json=failedRows" json:"failed_rows,omitempty"`
	MetaUpdateStatus     *MetaUpdateStatus `protobuf:"bytes,2,opt,name=meta_update_status,json=metaUpdateStatus" json:"meta_update_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutTimeseriesDataResponse) Reset()         { *m = PutTimeseriesDataResponse{} }
func (m *PutTimeseriesDataResponse) String() string { return proto.CompactTextString(m) }
func (*PutTimeseriesDataResponse) ProtoMessage()    {}
func (*PutTimeseriesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{27}
}

func (m *PutTimeseriesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutTimeseriesDataResponse.Unmarshal(m, b)
}
func (m *PutTimeseriesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutTimeseriesDataResponse.Marshal(b, m, deterministic)
}
func (m *PutTimeseriesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutTimeseriesDataResponse.Merge(m, src)
}
func (m *PutTimeseriesDataResponse) XXX_Size() int {
	return xxx_messageInfo_PutTimeseriesDataResponse.Size(m)
}
func (m *PutTimeseriesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutTimeseriesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutTimeseriesDataResponse proto.InternalMessageInfo

func (m *PutTimeseriesDataResponse) GetFailedRows() []*FailedRowInfo {
	if m != nil {
		return m.FailedRows
	}
	return nil
}

func (m *PutTimeseriesDataResponse) GetMetaUpdateStatus() *MetaUpdateStatus {
	if m != nil {
		return m.MetaUpdateStatus
	}
	return nil
}

type GetTimeseriesDataRequest struct {
	TableName            *string        `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	TimeSeriesKey        *TimeseriesKey `protobuf:"bytes,2,req,name=time_series_key,json=timeSeriesKey" json:"time_series_key,omitempty"`
	BeginTime            *int64         `protobuf:"varint,3,opt,name=begin_time,json=beginTime" json:"begin_time,omitempty"`
	EndTime              *int64         `protobuf:"varint,4,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	SpecificTime         *int64         `protobuf:"varint,5,opt,name=specific_time,json=specificTime" json:"specific_time,omitempty"`
	Token                []byte         `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	Limit                *int32         `protobuf:"varint,7,opt,name=limit" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTimeseriesDataRequest) Reset()         { *m = GetTimeseriesDataRequest{} }
func (m *GetTimeseriesDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeseriesDataRequest) ProtoMessage()    {}
func (*GetTimeseriesDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{28}
}

func (m *GetTimeseriesDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeseriesDataRequest.Unmarshal(m, b)
}
func (m *GetTimeseriesDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeseriesDataRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeseriesDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeseriesDataRequest.Merge(m, src)
}
func (m *GetTimeseriesDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeseriesDataRequest.Size(m)
}
func (m *GetTimeseriesDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeseriesDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeseriesDataRequest proto.InternalMessageInfo

func (m *GetTimeseriesDataRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *GetTimeseriesDataRequest) GetTimeSeriesKey() *TimeseriesKey {
	if m != nil {
		return m.TimeSeriesKey
	}
	return nil
}

func (m *GetTimeseriesDataRequest) GetBeginTime() int64 {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return 0
}

func (m *GetTimeseriesDataRequest) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *GetTimeseriesDataRequest) GetSpecificTime() int64 {
	if m != nil && m.SpecificTime != nil {
		return *m.SpecificTime
	}
	return 0
}

func (m *GetTimeseriesDataRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetTimeseriesDataRequest) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type GetTimeseriesDataResponse struct {
	RowsData             []byte   `protobuf:"bytes,1,req,name=rows_data,json=rowsData" json:"rows_data,omitempty"`
	NextToken            []byte   `protobuf:"bytes,2,opt,name=next_token,json=nextToken" json:"next_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeseriesDataResponse) Reset()         { *m = GetTimeseriesDataResponse{} }
func (m *GetTimeseriesDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetTimeseriesDataResponse) ProtoMessage()    {}
func (*GetTimeseriesDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{29}
}

func (m *GetTimeseriesDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeseriesDataResponse.Unmarshal(m, b)
}
func (m *GetTimeseriesDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeseriesDataResponse.Marshal(b, m, deterministic)
}
func (m *GetTimeseriesDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeseriesDataResponse.Merge(m, src)
}
func (m *GetTimeseriesDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetTimeseriesDataResponse.Size(m)
}
func (m *GetTimeseriesDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeseriesDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeseriesDataResponse proto.InternalMessageInfo

func (m *GetTimeseriesDataResponse) GetRowsData() []byte {
	if m != nil {
		return m.RowsData
	}
	return nil
}

func (m *GetTimeseriesDataResponse) GetNextToken() []byte {
	if m != nil {
		return m.NextToken
	}
	return nil
}

type UpdateTimeseriesMetaRequest struct {
	TableName            *string           `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	TimeseriesMeta       []*TimeseriesMeta `protobuf:"bytes,2,rep,name=timeseries_meta,json=timeseriesMeta" json:"timeseries_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateTimeseriesMetaRequest) Reset()         { *m = UpdateTimeseriesMetaRequest{} }
func (m *UpdateTimeseriesMetaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTimeseriesMetaRequest) ProtoMessage()    {}
func (*UpdateTimeseriesMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{30}
}

func (m *UpdateTimeseriesMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTimeseriesMetaRequest.Unmarshal(m, b)
}
func (m *UpdateTimeseriesMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTimeseriesMetaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTimeseriesMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTimeseriesMetaRequest.Merge(m, src)
}
func (m *UpdateTimeseriesMetaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTimeseriesMetaRequest.Size(m)
}
func (m *UpdateTimeseriesMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTimeseriesMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTimeseriesMetaRequest proto.InternalMessageInfo

func (m *UpdateTimeseriesMetaRequest) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *UpdateTimeseriesMetaRequest) GetTimeseriesMeta() []*TimeseriesMeta {
	if m != nil {
		return m.TimeseriesMeta
	}
	return nil
}

type UpdateTimeseriesMetaResponse struct {
	FailedRows           []*FailedRowInfo `protobuf:"bytes,1,rep,name=failed_rows,json=failedRows" json:"failed_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateTimeseriesMetaResponse) Reset()         { *m = UpdateTimeseriesMetaResponse{} }
func (m *UpdateTimeseriesMetaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTimeseriesMetaResponse) ProtoMessage()    {}
func (*UpdateTimeseriesMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f432f906d7ab9cb, []int{31}
}

func (m *UpdateTimeseriesMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTimeseriesMetaResponse.Unmarshal(m, b)
}
func (m *UpdateTimeseriesMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTimeseriesMetaResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTimeseriesMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTimeseriesMetaResponse.Merge(m, src)
}
func (m *UpdateTimeseriesMetaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTimeseriesMetaResponse.Size(m)
}
func (m *UpdateTimeseriesMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTimeseriesMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTimeseriesMetaResponse proto.InternalMessageInfo

func (m *UpdateTimeseriesMetaResponse) GetFailedRows() []*FailedRowInfo {
	if m != nil {
		return m.FailedRows
	}
	return nil
}

func init() {
	proto.RegisterEnum("otsprotocol.MetaQueryConditionType", MetaQueryConditionType_name, MetaQueryConditionType_value)
	proto.RegisterEnum("otsprotocol.MetaQueryCompositeOperator", MetaQueryCompositeOperator_name, MetaQueryCompositeOperator_value)
	proto.RegisterEnum("otsprotocol.MetaQuerySingleOperator", MetaQuerySingleOperator_name, MetaQuerySingleOperator_value)
	proto.RegisterEnum("otsprotocol.RowsSerializeType", RowsSerializeType_name, RowsSerializeType_value)
	proto.RegisterEnum("otsprotocol.MetaUpdateMode", MetaUpdateMode_name, MetaUpdateMode_value)
	proto.RegisterType((*TimeseriesTableOptions)(nil), "otsprotocol.TimeseriesTableOptions")
	proto.RegisterType((*TimeseriesTableMeta)(nil), "otsprotocol.TimeseriesTableMeta")
	proto.RegisterType((*CreateTimeseriesTableRequest)(nil), "otsprotocol.CreateTimeseriesTableRequest")
	proto.RegisterType((*CreateTimeseriesTableResponse)(nil), "otsprotocol.CreateTimeseriesTableResponse")
	proto.RegisterType((*ListTimeseriesTableRequest)(nil), "otsprotocol.ListTimeseriesTableRequest")
	proto.RegisterType((*ListTimeseriesTableResponse)(nil), "otsprotocol.ListTimeseriesTableResponse")
	proto.RegisterType((*DeleteTimeseriesTableRequest)(nil), "otsprotocol.DeleteTimeseriesTableRequest")
	proto.RegisterType((*DeleteTimeseriesTableResponse)(nil), "otsprotocol.DeleteTimeseriesTableResponse")
	proto.RegisterType((*UpdateTimeseriesTableRequest)(nil), "otsprotocol.UpdateTimeseriesTableRequest")
	proto.RegisterType((*UpdateTimeseriesTableResponse)(nil), "otsprotocol.UpdateTimeseriesTableResponse")
	proto.RegisterType((*DescribeTimeseriesTableRequest)(nil), "otsprotocol.DescribeTimeseriesTableRequest")
	proto.RegisterType((*DescribeTimeseriesTableResponse)(nil), "otsprotocol.DescribeTimeseriesTableResponse")
	proto.RegisterType((*MetaQueryCondition)(nil), "otsprotocol.MetaQueryCondition")
	proto.RegisterType((*MetaQueryCompositeCondition)(nil), "otsprotocol.MetaQueryCompositeCondition")
	proto.RegisterType((*MetaQueryMeasurementCondition)(nil), "otsprotocol.MetaQueryMeasurementCondition")
	proto.RegisterType((*MetaQuerySourceCondition)(nil), "otsprotocol.MetaQuerySourceCondition")
	proto.RegisterType((*MetaQueryTagCondition)(nil), "otsprotocol.MetaQueryTagCondition")
	proto.RegisterType((*MetaQueryAttributeCondition)(nil), "otsprotocol.MetaQueryAttributeCondition")
	proto.RegisterType((*MetaQueryUpdateTimeCondition)(nil), "otsprotocol.MetaQueryUpdateTimeCondition")
	proto.RegisterType((*TimeseriesKey)(nil), "otsprotocol.TimeseriesKey")
	proto.RegisterType((*TimeseriesMeta)(nil), "otsprotocol.TimeseriesMeta")
	proto.RegisterType((*QueryTimeseriesMetaRequest)(nil), "otsprotocol.QueryTimeseriesMetaRequest")
	proto.RegisterType((*QueryTimeseriesMetaResponse)(nil), "otsprotocol.QueryTimeseriesMetaResponse")
	proto.RegisterType((*TimeseriesRows)(nil), "otsprotocol.TimeseriesRows")
	proto.RegisterType((*PutTimeseriesDataRequest)(nil), "otsprotocol.PutTimeseriesDataRequest")
	proto.RegisterType((*FailedRowInfo)(nil), "otsprotocol.FailedRowInfo")
	proto.RegisterType((*MetaUpdateStatus)(nil), "otsprotocol.MetaUpdateStatus")
	proto.RegisterType((*PutTimeseriesDataResponse)(nil), "otsprotocol.PutTimeseriesDataResponse")
	proto.RegisterType((*GetTimeseriesDataRequest)(nil), "otsprotocol.GetTimeseriesDataRequest")
	proto.RegisterType((*GetTimeseriesDataResponse)(nil), "otsprotocol.GetTimeseriesDataResponse")
	proto.RegisterType((*UpdateTimeseriesMetaRequest)(nil), "otsprotocol.UpdateTimeseriesMetaRequest")
	proto.RegisterType((*UpdateTimeseriesMetaResponse)(nil), "otsprotocol.UpdateTimeseriesMetaResponse")
}

func init() { proto.RegisterFile("timeseries.proto", fileDescriptor_8f432f906d7ab9cb) }

var fileDescriptor_8f432f906d7ab9cb = []byte{
	// 1420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0x1a, 0x47,
	0x17, 0xce, 0x82, 0xb1, 0xbd, 0x87, 0x0f, 0xaf, 0x27, 0x5f, 0xd8, 0xd8, 0x31, 0xda, 0xbc, 0xd2,
	0x8b, 0x5c, 0x29, 0xaa, 0xdc, 0x4a, 0xad, 0x5a, 0x45, 0x11, 0xe1, 0xc3, 0x41, 0x31, 0x2c, 0x19,
	0x16, 0xa5, 0x52, 0x55, 0x4d, 0x07, 0x18, 0xe8, 0x36, 0xc0, 0xd2, 0x9d, 0x21, 0x89, 0x7b, 0xd1,
	0x8b, 0x5e, 0xa4, 0xbd, 0xea, 0x5d, 0x7b, 0x59, 0xa9, 0x17, 0xbd, 0xe8, 0x5f, 0xe8, 0x4f, 0xe8,
	0xaf, 0xaa, 0x66, 0x76, 0x81, 0x5d, 0x02, 0x4e, 0x62, 0xa7, 0x57, 0x70, 0x9e, 0x99, 0x33, 0xe7,
	0x39, 0x67, 0xce, 0x3c, 0x7b, 0xc0, 0x10, 0xce, 0x88, 0x71, 0xe6, 0x39, 0x8c, 0xdf, 0x9b, 0x78,
	0xae, 0x70, 0x51, 0xd2, 0x15, 0x5c, 0xfd, 0xeb, 0xba, 0x43, 0xf3, 0x33, 0xb8, 0x65, 0xcf, 0x37,
	0xd8, 0xb4, 0x33, 0x64, 0xd6, 0x44, 0x38, 0xee, 0x98, 0xa3, 0x3c, 0xa4, 0xa4, 0x2b, 0x11, 0x2e,
	0x19, 0x3a, 0xcf, 0x59, 0x56, 0xcb, 0x6b, 0x85, 0x04, 0x06, 0x89, 0xd9, 0xee, 0x99, 0xf3, 0x9c,
	0x99, 0xbf, 0x69, 0x70, 0x7d, 0xc9, 0xb9, 0xce, 0x04, 0x45, 0x87, 0x00, 0x42, 0x1a, 0x64, 0x4c,
	0x47, 0xd2, 0x2f, 0x56, 0xd0, 0xb1, 0xae, 0x90, 0x06, 0x1d, 0x31, 0xf4, 0x08, 0xd2, 0xfe, 0xb2,
	0xeb, 0x47, 0xca, 0xc6, 0xf2, 0x5a, 0x21, 0x79, 0x72, 0xf7, 0x5e, 0x88, 0xd7, 0xbd, 0xd5, 0xa4,
	0x70, 0x4a, 0x84, 0x29, 0xde, 0x82, 0x4d, 0x2e, 0xa8, 0x98, 0xf2, 0x6c, 0x3c, 0xaf, 0x15, 0x74,
	0x1c, 0x58, 0x26, 0x81, 0x83, 0x92, 0xc7, 0xa8, 0x60, 0x4b, 0xa7, 0x60, 0xf6, 0xdd, 0x94, 0x71,
	0x81, 0x1e, 0xcc, 0x08, 0x8e, 0x98, 0xa0, 0x8a, 0x60, 0xf2, 0x24, 0x7f, 0x51, 0x78, 0x99, 0x56,
	0x90, 0x82, 0xfc, 0x6b, 0x1e, 0xc1, 0xe1, 0x9a, 0x00, 0x7c, 0xe2, 0x8e, 0x39, 0x33, 0x0f, 0x60,
	0xff, 0xcc, 0xe1, 0x62, 0x75, 0x7c, 0xf3, 0x6b, 0xc8, 0xad, 0x5c, 0xf5, 0x9d, 0x51, 0x11, 0x92,
	0x0b, 0x7a, 0x3c, 0xab, 0xe5, 0xe3, 0x6f, 0xc5, 0x0f, 0xe6, 0xfc, 0xb8, 0x79, 0x1f, 0x0e, 0xca,
	0x6c, 0xc8, 0xd6, 0x56, 0xe0, 0xe2, 0x2b, 0x92, 0xf9, 0xad, 0x71, 0x0f, 0xf2, 0xfb, 0x49, 0x83,
	0x83, 0xf6, 0xa4, 0x47, 0x2f, 0x19, 0xe0, 0xfd, 0xf5, 0x80, 0xa4, 0xba, 0x86, 0x48, 0x40, 0xf5,
	0x01, 0xdc, 0x29, 0x33, 0xde, 0xf5, 0x9c, 0xce, 0x25, 0x8b, 0xd1, 0x81, 0xa3, 0xb5, 0x07, 0x04,
	0x37, 0x76, 0xe5, 0x86, 0x1a, 0x02, 0x92, 0xbf, 0x4f, 0xa6, 0xcc, 0x3b, 0x2f, 0xb9, 0xe3, 0x9e,
	0x23, 0x93, 0x43, 0x9f, 0xc0, 0x86, 0x38, 0x9f, 0xf8, 0x94, 0x32, 0x4b, 0xc5, 0x79, 0x7d, 0xbb,
	0x7d, 0x3e, 0x61, 0x58, 0x39, 0xc8, 0x8c, 0xd4, 0x46, 0xd2, 0xa3, 0x82, 0x66, 0x63, 0xf9, 0x58,
	0x21, 0x85, 0x75, 0x85, 0x94, 0xa9, 0xa0, 0xe6, 0xef, 0x1a, 0xe4, 0x42, 0xfe, 0xa3, 0x89, 0xcb,
	0x1d, 0xc1, 0xc2, 0x71, 0x63, 0xee, 0x24, 0x88, 0xfa, 0xff, 0x75, 0x51, 0x03, 0x2f, 0x6b, 0xc2,
	0x3c, 0x2a, 0x5c, 0x0f, 0xc7, 0xdc, 0x09, 0xaa, 0x42, 0x86, 0x4f, 0x3b, 0xa4, 0x3b, 0x3b, 0x49,
	0xde, 0xab, 0x6c, 0xde, 0xa3, 0x37, 0x50, 0xc7, 0x69, 0x3e, 0xed, 0xcc, 0x2d, 0x6e, 0x3e, 0x83,
	0xc3, 0xf9, 0xa6, 0x3a, 0xa3, 0x7c, 0xea, 0xb1, 0x11, 0x1b, 0x8b, 0x05, 0xc3, 0x8f, 0x43, 0x0c,
	0xff, 0xb7, 0xfa, 0xf0, 0x96, 0x33, 0x1e, 0x0c, 0xa3, 0xf4, 0x6e, 0x40, 0xe2, 0x39, 0x1d, 0x4e,
	0x99, 0xaa, 0x88, 0x8e, 0x7d, 0xc3, 0xec, 0x43, 0x76, 0xe1, 0xe4, 0x4e, 0xbd, 0x2e, 0xfb, 0x6f,
	0xe2, 0xfc, 0x00, 0x37, 0xe7, 0x4e, 0x36, 0x1d, 0x5c, 0x35, 0xc8, 0x1e, 0x6c, 0x0b, 0x3a, 0xf0,
	0x7b, 0xd6, 0x8f, 0xb3, 0x25, 0xe8, 0x40, 0xbd, 0xae, 0x79, 0xfc, 0x78, 0x38, 0xfe, 0xab, 0xf0,
	0xad, 0x17, 0x85, 0xf0, 0x9c, 0xce, 0x54, 0x5c, 0x39, 0xd7, 0x1c, 0xe8, 0x54, 0x08, 0x2f, 0xcc,
	0x63, 0x5b, 0x02, 0x17, 0x10, 0xf9, 0x16, 0x0e, 0xe6, 0x27, 0x2e, 0xde, 0xee, 0x7b, 0x2d, 0x7a,
	0x7c, 0x16, 0xeb, 0x2b, 0x48, 0x2f, 0x9e, 0xde, 0x63, 0x76, 0x8e, 0xf2, 0x90, 0x1c, 0x2d, 0x3a,
	0x2a, 0x78, 0xed, 0x61, 0x48, 0x7d, 0x55, 0x54, 0x1b, 0x04, 0xe9, 0x04, 0x16, 0x42, 0xb0, 0x21,
	0xe8, 0x80, 0x07, 0xb9, 0xa8, 0xff, 0xe6, 0xaf, 0x1a, 0x64, 0x16, 0xe7, 0xab, 0xaf, 0xdf, 0x43,
	0xd8, 0x51, 0xdf, 0x4d, 0x1f, 0x22, 0xcf, 0xd8, 0x79, 0x20, 0x08, 0xfb, 0x6b, 0x04, 0xe1, 0x31,
	0x3b, 0xc7, 0x69, 0xe9, 0xd2, 0x9a, 0x93, 0xbc, 0x03, 0x40, 0x67, 0x17, 0xe4, 0x6b, 0xa3, 0x8e,
	0x43, 0x08, 0x3a, 0x82, 0xe4, 0x54, 0x15, 0x8e, 0x48, 0x3f, 0xf5, 0xf5, 0x8b, 0x63, 0x98, 0xce,
	0x6b, 0x69, 0xfe, 0xa3, 0xc1, 0xbe, 0xdf, 0x68, 0x11, 0x72, 0x6f, 0xa9, 0xce, 0xf7, 0x41, 0x9f,
	0x3f, 0xe1, 0x40, 0x99, 0xdf, 0xf8, 0x82, 0x17, 0x1e, 0xc8, 0x84, 0xf4, 0x80, 0x09, 0x22, 0x5c,
	0x41, 0x87, 0xe4, 0x1b, 0x47, 0x28, 0x7e, 0xdb, 0x38, 0x39, 0x60, 0xc2, 0x96, 0xd8, 0x23, 0x47,
	0xc8, 0xdb, 0x12, 0xee, 0x33, 0x36, 0xce, 0x6e, 0xe4, 0xb5, 0x42, 0x0a, 0xfb, 0x86, 0x44, 0x87,
	0xce, 0xc8, 0x11, 0xd9, 0x84, 0x1a, 0x36, 0x7c, 0xc3, 0xfc, 0x43, 0x83, 0xdc, 0xca, 0x64, 0x02,
	0xf5, 0xad, 0x86, 0x87, 0x9c, 0xc8, 0x47, 0x33, 0xb7, 0xa6, 0xe4, 0xca, 0x7d, 0x47, 0x44, 0x6c,
	0x2e, 0x5b, 0x79, 0xc1, 0x39, 0xa6, 0x6a, 0xba, 0x2d, 0x66, 0x84, 0x0f, 0x01, 0xc6, 0xec, 0xa5,
	0xcc, 0x4a, 0xb2, 0x8e, 0x2b, 0xd6, 0xba, 0x44, 0x6c, 0x09, 0x98, 0xbf, 0x44, 0x1a, 0x01, 0xbb,
	0x2f, 0x38, 0x3a, 0x89, 0xa8, 0xf7, 0x9d, 0x08, 0x15, 0xb9, 0x41, 0x5e, 0x37, 0x1d, 0x3a, 0xdf,
	0xb3, 0x90, 0x70, 0xe7, 0x40, 0xf7, 0xdc, 0x17, 0x3c, 0xac, 0xdb, 0xdb, 0x12, 0x90, 0xb2, 0x8d,
	0x3e, 0x80, 0xdd, 0xfe, 0x90, 0x8a, 0xce, 0xb4, 0xdf, 0x67, 0x1e, 0xe9, 0x7a, 0xdd, 0x8f, 0x4e,
	0xba, 0x8a, 0x49, 0x02, 0x1b, 0x8b, 0x85, 0x92, 0xc2, 0xcd, 0xbf, 0x35, 0xc8, 0x36, 0xa7, 0xa1,
	0x19, 0x43, 0x1e, 0xf1, 0x96, 0xf7, 0xff, 0xe9, 0x32, 0x8b, 0xf5, 0x95, 0x94, 0x89, 0x84, 0x28,
	0x56, 0xc0, 0x90, 0xf5, 0x27, 0x41, 0x77, 0x8e, 0xdc, 0x9e, 0xdf, 0x9d, 0x99, 0xa5, 0x03, 0x64,
	0xc1, 0xfd, 0xa7, 0x5f, 0x77, 0x7b, 0x0c, 0x67, 0x46, 0x11, 0xdb, 0x9c, 0x40, 0xba, 0x4a, 0x9d,
	0x21, 0xeb, 0x61, 0xf7, 0x45, 0x6d, 0xdc, 0x77, 0x83, 0xba, 0x10, 0x67, 0xdc, 0x63, 0x2f, 0x15,
	0xdf, 0x84, 0x0a, 0x5a, 0x93, 0xb6, 0xcc, 0x86, 0x79, 0x9e, 0xeb, 0x91, 0xae, 0x0c, 0xe7, 0xbf,
	0x16, 0x5d, 0x21, 0x25, 0xb7, 0xc7, 0xd0, 0x5d, 0x48, 0xfb, 0xcb, 0x23, 0xc6, 0x39, 0x1d, 0xb0,
	0x60, 0x58, 0x4c, 0x29, 0xb0, 0xee, 0x63, 0xe6, 0x53, 0x30, 0x16, 0x9c, 0x5a, 0x6a, 0x8c, 0x44,
	0xb7, 0x61, 0x4b, 0x05, 0xed, 0xf9, 0xed, 0x94, 0xc6, 0x9b, 0x32, 0x64, 0x8f, 0xa3, 0x63, 0xd8,
	0x0d, 0x67, 0xa9, 0xfa, 0x48, 0x7d, 0xe9, 0xd2, 0x78, 0x67, 0x91, 0x89, 0x2a, 0x92, 0xf9, 0xa7,
	0x06, 0x7b, 0x2b, 0xee, 0x21, 0x68, 0xdd, 0xcf, 0x21, 0xd9, 0x57, 0x89, 0x12, 0x59, 0xc2, 0xa0,
	0x6b, 0xa3, 0x42, 0x11, 0x29, 0x04, 0x86, 0xfe, 0xcc, 0xe4, 0xe8, 0x31, 0xa0, 0x30, 0x8d, 0x60,
	0x14, 0xf6, 0xdf, 0xeb, 0xe1, 0x9a, 0x72, 0xfb, 0xa9, 0x61, 0x63, 0xb4, 0x84, 0x98, 0x3f, 0xc7,
	0x20, 0x7b, 0xca, 0x2e, 0xd7, 0x2f, 0x2b, 0x24, 0x2f, 0xf6, 0xae, 0x92, 0x77, 0x08, 0xd0, 0x61,
	0x03, 0x67, 0x1c, 0x56, 0x34, 0x5d, 0x21, 0xd2, 0x4d, 0x7e, 0xed, 0xd8, 0xb8, 0xe7, 0x2f, 0x6e,
	0xa8, 0xc5, 0x2d, 0x36, 0xee, 0xa9, 0xa5, 0xbb, 0x90, 0xe6, 0x13, 0xd6, 0x75, 0xfa, 0x4e, 0xd7,
	0x5f, 0x4f, 0xa8, 0xf5, 0xd4, 0x0c, 0x54, 0x9b, 0xe6, 0x7a, 0xb3, 0xb9, 0x52, 0x6f, 0xb6, 0xc2,
	0x7a, 0xf3, 0x14, 0xf6, 0x56, 0x54, 0x22, 0xb8, 0xb1, 0xc8, 0x0b, 0xd5, 0x96, 0x5e, 0x68, 0x54,
	0x24, 0x62, 0xcb, 0x22, 0xf1, 0xa3, 0x06, 0xb9, 0xe5, 0x61, 0xf5, 0x1d, 0x64, 0xb9, 0x0c, 0x3b,
	0x4b, 0x3a, 0x17, 0x8c, 0x57, 0x17, 0xca, 0x5c, 0x26, 0x2a, 0x73, 0xe6, 0x97, 0xaf, 0x4f, 0xee,
	0x11, 0x35, 0xbd, 0x4a, 0x4b, 0x1e, 0xff, 0xa5, 0xc1, 0xad, 0xd5, 0x93, 0x29, 0xba, 0x0d, 0xd7,
	0x4b, 0x56, 0xbd, 0x69, 0xb5, 0x6a, 0x76, 0x85, 0x94, 0xac, 0x46, 0xb9, 0x66, 0xd7, 0xac, 0x86,
	0xa1, 0xa1, 0x3d, 0xb8, 0x59, 0xaf, 0x14, 0x5b, 0x6d, 0x5c, 0xa9, 0x57, 0x1a, 0x76, 0x68, 0x29,
	0x86, 0x6e, 0x80, 0xd1, 0xb2, 0xda, 0xb8, 0x14, 0x76, 0x88, 0xa3, 0x5d, 0x48, 0xdb, 0xc5, 0xd3,
	0x10, 0xb4, 0x21, 0xcf, 0x68, 0x37, 0xcb, 0x45, 0xbb, 0x42, 0xec, 0x5a, 0x3d, 0xbc, 0x3b, 0x21,
	0xe3, 0x16, 0x6d, 0x1b, 0xd7, 0x1e, 0xb6, 0x23, 0x71, 0x37, 0x8f, 0x1f, 0xc0, 0xfe, 0xfa, 0x71,
	0x16, 0x01, 0x6c, 0x5a, 0x4d, 0x52, 0x6c, 0x94, 0x0d, 0x0d, 0xe9, 0x90, 0xb0, 0x9a, 0xc4, 0xc2,
	0x46, 0x2c, 0x80, 0x1b, 0x96, 0x6d, 0xc4, 0x8f, 0x5f, 0x69, 0x70, 0x7b, 0xcd, 0x44, 0x82, 0x52,
	0xb0, 0x6d, 0x35, 0x49, 0xe5, 0x49, 0xbb, 0x78, 0x66, 0x68, 0xe8, 0x3a, 0xec, 0x58, 0x4d, 0x72,
	0x8a, 0x2b, 0x45, 0xbb, 0x82, 0x89, 0xfd, 0xa8, 0x18, 0x24, 0x17, 0x02, 0xfd, 0xad, 0x71, 0x64,
	0x40, 0xca, 0x6a, 0x92, 0xb3, 0x4a, 0xab, 0xe5, 0xef, 0xdb, 0x90, 0xe9, 0xce, 0x10, 0x7f, 0x53,
	0x02, 0xa5, 0x41, 0xb7, 0x9a, 0xa4, 0x89, 0x2b, 0xd5, 0xda, 0x17, 0xc6, 0xe6, 0x71, 0x01, 0x76,
	0x5f, 0xfb, 0xa0, 0xc8, 0x98, 0xb8, 0x65, 0x93, 0xea, 0x59, 0xd1, 0x26, 0x0f, 0xdb, 0xd5, 0x6a,
	0x05, 0x1b, 0xd7, 0x8e, 0x3f, 0x84, 0x4c, 0x54, 0x7a, 0x51, 0x06, 0xa0, 0xde, 0xae, 0x93, 0x86,
	0x85, 0xeb, 0xc5, 0x33, 0xe3, 0xda, 0xcc, 0xae, 0x9d, 0x36, 0x2c, 0x5c, 0x31, 0xb4, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x51, 0x73, 0xf7, 0xd7, 0x40, 0x10, 0x00, 0x00,
}
